-- Generated by web/scripts/generate-capability-protocol.ts from
-- web/src/lib/server/public-api/catalog/credential.ts.
begin;
create extension if not exists pgtap with schema extensions;
select plan(1);

select set_eq(
  $$select kind from internal.messenger_identity_credential_kind$$,
  $$values ('buzz-secret'::text)$$,
  'the record names the messenger identity credential kinds the catalog declares'
);

select * from finish();
rollback;
