project_id = "mutvimjbvmoludotyehk"

[db.seed]
enabled = true
sql_paths = ['./seed.dev.sql']

[auth.passkey]
enabled = true

[auth.webauthn]
rp_display_name = "InternKim"
rp_id = "intern.kim"
rp_origins = ["https://intern.kim", "https://*.intern.kim"]

[auth.email.template.magic_link]
subject = "김인턴 계정 설정하기"
content_path = "./supabase/templates/magic-link.html"
