export const attendanceText = {
	ko: {
		pageTitle: '출결 · intern kim',
		title: '출결',
		subtitle: '팀 전체 근무 기록과 개인 근무 시간',
		allUsers: '전체 사용자',
		allLocations: '전체 장소',
		refresh: '출결 새로고침',
		currentStatus: '현재 상태',
		working: '근무 중',
		finished: '퇴근',
		absent: '미출근',
		upcoming: '예정',
		inProgress: '진행 중',
		clockIn: '출근',
		clockOut: '퇴근',
		clockInShort: '출',
		clockOutShort: '퇴',
		today: '오늘',
		thisWeek: '이번 주',
		thisMonth: '이번 달',
		todayAttendance: '오늘 출석',
		thisWeekAverage: '이번 주 평균',
		thisMonthAverage: '이번 달 평균',
		workedDayUnit: '일 근무',
		workedDayTemplate: '{count}일 근무',
		myWorkTime: '내 근무 시간',
		teamWorkTime: '팀 근무 시간',
		teamTabVisible: '팀 탭 공개',
		visibleToAll: '전원 공개',
		adminOnly: '관리자만',
		day: '일별',
		week: '주별',
		month: '월별',
		weekSuffix: '주',
		weekLabelTemplate: '{index}주',
		total: '합계',
		trend: '근무 시간 추세',
		monthlyCalendar: '월간 캘린더',
		attendanceRate: '출근율',
		locationDistribution: '위치 분포',
		noData: '데이터 없음',
		teamLog: '팀 로그',
		loading: '불러오는 중...',
		empty: '기록이 없습니다.',
		date: '날짜',
		user: '사용자',
		event: '이벤트',
		location: '장소',
		status: '상태',
		canceled: '취소됨',
		recorded: '기록',
		loadFailed: '출결 정보를 불러오지 못했습니다.',
		defaultLocation: '사무실',
		hourUnit: '시간',
		minuteUnit: '분',
		processingFailed: '처리 실패',
		tabTeam: '팀',
		tabPersonal: '개인',
		teamBlocked: '관리자가 팀 출결을 비공개로 설정했습니다.',
		peopleWorkingTemplate: '{count}명 근무 중',
		todayClockInTemplate: '오늘 출근 {worked}/{total}명',
		peopleCountTemplate: '{count}명',
		dayBasisTemplate: '{count}일 기준',
		subscriptionDayTemplate: '{count}일',
		calendarTitleTemplate: '{month} 캘린더',
		attendanceRateTitleTemplate: '{month} 출석률',
		currentPresence: '현재 상태',
		all: '전체',
		online: '온라인',
		away: '자리비움',
		dnd: '방해 금지',
		offline: '오프라인',
		todayDateTemplate: '오늘 {date}',
		selectedDayTemplate: '선택된 날 {date}',
		firstClockInDayTemplate: '{date} (첫 출근일)',
		defaultView: '기본으로',
		noMembers: '표시할 구성원이 없습니다.',
		eventNone: '이벤트 없음',
		source: '출처',
		sourceMattermostButton: 'Mattermost 버튼',
		sourceMattermostPost: 'Mattermost 메시지',
		resultPost: '결과 메시지',
		originalMessage: '원본 메시지',
		manualEntry: '메시지 없이 수동으로 추가된 기록',
		agentConfidenceTemplate: '에이전트 확신도: {percent}%',
		originalLocation: '원래 장소',
		current: '현재',
		editedAtTemplate: '{user} 가 {time} 에 수정',
		cancelReasonTemplate: '취소 사유: {reason}',
		locationOverride: '장소 수정',
		dateLocale: 'ko-KR',
		weekdaySunday: '일',
		weekdayMonday: '월',
		weekdayTuesday: '화',
		weekdayWednesday: '수',
		weekdayThursday: '목',
		weekdayFriday: '금',
		weekdaySaturday: '토'
	},
	en: {
		pageTitle: 'Attendance · intern kim',
		title: 'Attendance',
		subtitle: 'Team attendance records and personal work time',
		allUsers: 'All users',
		allLocations: 'All locations',
		refresh: 'Refresh attendance',
		currentStatus: 'Current status',
		working: 'Working',
		finished: 'Clocked out',
		absent: 'Not clocked in',
		upcoming: 'Upcoming',
		inProgress: 'In progress',
		clockIn: 'Clock in',
		clockOut: 'Clock out',
		clockInShort: 'In',
		clockOutShort: 'Out',
		today: 'Today',
		thisWeek: 'This week',
		thisMonth: 'This month',
		todayAttendance: 'Today attendance',
		thisWeekAverage: 'This week average',
		thisMonthAverage: 'This month average',
		workedDayUnit: 'work days',
		workedDayTemplate: '{count} work days',
		myWorkTime: 'My work time',
		teamWorkTime: 'Team work time',
		teamTabVisible: 'Show team tab',
		visibleToAll: 'Visible to everyone',
		adminOnly: 'Admins only',
		day: 'Daily',
		week: 'Weekly',
		month: 'Monthly',
		weekSuffix: '',
		weekLabelTemplate: 'Week {index}',
		total: 'Total',
		trend: 'Work time trend',
		monthlyCalendar: 'Monthly calendar',
		attendanceRate: 'Attendance rate',
		locationDistribution: 'Location distribution',
		noData: 'No data',
		teamLog: 'Team log',
		loading: 'Loading...',
		empty: 'No records.',
		date: 'Date',
		user: 'User',
		event: 'Event',
		location: 'Location',
		status: 'Status',
		canceled: 'Canceled',
		recorded: 'Recorded',
		loadFailed: 'Could not load attendance information.',
		defaultLocation: 'Office',
		hourUnit: 'h',
		minuteUnit: 'm',
		processingFailed: 'Processing failed',
		tabTeam: 'Team',
		tabPersonal: 'Personal',
		teamBlocked: 'The administrator has hidden team attendance.',
		peopleWorkingTemplate: '{count} working',
		todayClockInTemplate: '{worked}/{total} clocked in today',
		peopleCountTemplate: '{count} people',
		dayBasisTemplate: 'Based on {count} days',
		subscriptionDayTemplate: '{count} days',
		calendarTitleTemplate: '{month} calendar',
		attendanceRateTitleTemplate: '{month} attendance rate',
		currentPresence: 'Current presence',
		all: 'All',
		online: 'Online',
		away: 'Away',
		dnd: 'Do not disturb',
		offline: 'Offline',
		todayDateTemplate: 'Today {date}',
		selectedDayTemplate: 'Selected day {date}',
		firstClockInDayTemplate: '{date} (first clock-in day)',
		defaultView: 'Default',
		noMembers: 'No members to display.',
		eventNone: 'No events.',
		source: 'Source',
		sourceMattermostButton: 'Mattermost button',
		sourceMattermostPost: 'Mattermost message',
		resultPost: 'Result message',
		originalMessage: 'Original message',
		manualEntry: 'Manually added record without a message',
		agentConfidenceTemplate: 'Agent confidence: {percent}%',
		originalLocation: 'Original location',
		current: 'Current',
		editedAtTemplate: '{user} edited at {time}',
		cancelReasonTemplate: 'Cancel reason: {reason}',
		locationOverride: 'Location override',
		dateLocale: 'en-US',
		weekdaySunday: 'Sun',
		weekdayMonday: 'Mon',
		weekdayTuesday: 'Tue',
		weekdayWednesday: 'Wed',
		weekdayThursday: 'Thu',
		weekdayFriday: 'Fri',
		weekdaySaturday: 'Sat'
	}
} as const;

export type AttendanceText = typeof attendanceText.ko;
