export const attendanceText = {
	ko: {
		pageTitle: '근태 · intern kim',
		title: '근태',
		subtitle: '팀 전체 근무 기록과 개인 근무 시간',
		allLocations: '전체 장소',
		refresh: '근태 새로고침',
		currentStatus: '현재 상태',
		working: '근무 중',
		finished: '퇴근',
		absent: '미출근',
		absence: '부재',
		absenceKindLeave: '휴가',
		absenceKindOther: '기타',
		absenceFormTitle: '부재 등록',
		absenceKind: '부재 유형',
		absenceStartDate: '시작일',
		absenceEndDate: '종료일',
		absenceReason: '사유',
		absenceReasonPlaceholder: '필요하면 사유를 입력하세요',
		createAbsence: '부재 등록',
		absenceCreated: '부재를 등록했습니다.',
		absenceNoWeekdays: '등록할 평일이 없습니다.',
		absenceDetails: '부재 상세',
		absenceCreatedByTemplate: '{user} 등록',
		upcoming: '예정',
		inProgress: '진행 중',
		clockIn: '출근',
		clockOut: '퇴근',
		clockInShort: '출',
		clockOutShort: '퇴',
		today: '오늘',
		thisWeek: '이번 주',
		thisMonth: '이번 달',
		todayAttendance: '오늘 근태',
		thisWeekAverage: '이번 주 평균',
		thisMonthAverage: '이번 달 평균',
		workedDayUnit: '일 근무',
		workedDayTemplate: '{count}일 근무',
		myWorkTime: '내 근무 시간',
		day: '일별',
		week: '주별',
		month: '월별',
		weekSuffix: '주',
		weekLabelTemplate: '{index}주',
		monthLabelTemplate: '{index}월',
		total: '합계',
		trend: '근무 시간 추세',
		monthlyCalendar: '월간 캘린더',
		attendanceRate: '출근율',
		locationDistribution: '위치 분포',
		noData: '데이터 없음',
		teamLog: '팀 로그',
		loading: '불러오는 중...',
		empty: '기록이 없습니다.',
		date: '날짜',
		event: '이벤트',
		location: '장소',
		status: '상태',
		canceled: '취소됨',
		recorded: '기록',
		loadFailed: '근태 정보를 불러오지 못했습니다.',
		defaultLocation: '사무실',
		hourUnit: '시간',
		minuteUnit: '분',
		processingFailed: '처리 실패',
		teamBlocked: '관리자가 팀 근태를 비공개로 설정했습니다.',
		peopleWorkingTemplate: '{count}명 근무 중',
		todayClockInTemplate: '오늘 출근 {worked}/{total}명',
		peopleCountTemplate: '{count}명',
		dayBasisTemplate: '{count}일 기준',
		subscriptionDayTemplate: '{count}일',
		calendarTitleTemplate: '{month} 캘린더',
		attendanceRateTitleTemplate: '{month} 근태율',
		teamAttendanceCalendarTitleTemplate: '{month} 근태 달력',
		presentCountTemplate: '{present}/{total}',
		moreAbsencesTemplate: '+{count}건',
		teamMonthlyStatus: '월간 근무 현황표',
		teamMonthlyStatusTable: '월간 근무 현황표',
		mobileStatusView: '팀 현황',
		mobileToolsView: '내 기록',
		previousMonth: '이전 달',
		nextMonth: '다음 달',
		previousYear: '이전 연도',
		nextYear: '다음 연도',
		previousYearWindow: '이전 12년',
		nextYearWindow: '다음 12년',
		teamMember: '직원',
		teamMemberSearchPlaceholder: '직원 검색',
		noMembers: '표시할 구성원이 없습니다.',
		eventNone: '이벤트 없음',
		workRecords: '근무 기록',
		workSegments: '근무 구간',
		calendarEvents: '캘린더 일정',
		completedWork: '완료된 업무',
		noCalendarEvents: '해당 일정 없음',
		noCompletedWork: '완료된 업무 없음',
		calendarEventsLoadFailed: '일정을 불러오지 못했습니다.',
		completedWorkLoadFailed: '완료된 업무를 불러오지 못했습니다.',
		calendarAllDay: '종일',
		locationSegmentCountTemplate: '{count}구간',
		originalMessage: '원본 메시지',
		manualEntry: '메시지 없이 수동으로 추가된 기록',
		agentConfidenceTemplate: '에이전트 확신도: {percent}%',
		agentInitialClassification: '에이전트의 초기 분류',
		current: '현재',
		editedAtTemplate: '{user} 가 {time} 에 수정',
		cancelReasonTemplate: '취소 사유: {reason}',
		cancelReasonRepeatedClick: '반복 클릭으로 취소됨',
		cancelReasonAccidentalShortSegment: '짧은 실수 출퇴근으로 취소됨',
		cancelReasonSameLocationResume: '같은 장소 재출근으로 이어짐',
		classification: '분류',
		confirmClockOut: '퇴근 확정',
		skip: '스킵',
		edit: '수정',
		save: '저장',
		cancel: '취소',
		close: '닫기',
		eventTime: '시간',
		editReason: '수정 사유',
		editReasonPlaceholder: '수정 사유를 입력하세요',
		beforeEdit: '수정 전',
		afterEdit: '수정 후',
		dateLocale: 'ko-KR',
		weekdaySunday: '일',
		weekdayMonday: '월',
		weekdayTuesday: '화',
		weekdayWednesday: '수',
		weekdayThursday: '목',
		weekdayFriday: '금',
		weekdaySaturday: '토'
	},
	en: {
		pageTitle: 'Attendance · intern kim',
		title: 'Attendance',
		subtitle: 'Team attendance records and personal work time',
		allLocations: 'All locations',
		refresh: 'Refresh attendance',
		currentStatus: 'Current status',
		working: 'Working',
		finished: 'Clocked out',
		absent: 'Not clocked in',
		absence: 'Absence',
		absenceKindLeave: 'Leave',
		absenceKindOther: 'Other',
		absenceFormTitle: 'Register absence',
		absenceKind: 'Absence type',
		absenceStartDate: 'Start date',
		absenceEndDate: 'End date',
		absenceReason: 'Reason',
		absenceReasonPlaceholder: 'Add a reason if needed',
		createAbsence: 'Register absence',
		absenceCreated: 'Absence registered.',
		absenceNoWeekdays: 'No weekdays to register.',
		absenceDetails: 'Absence details',
		absenceCreatedByTemplate: 'Created by {user}',
		upcoming: 'Upcoming',
		inProgress: 'In progress',
		clockIn: 'Clock in',
		clockOut: 'Clock out',
		clockInShort: 'In',
		clockOutShort: 'Out',
		today: 'Today',
		thisWeek: 'This week',
		thisMonth: 'This month',
		todayAttendance: 'Today attendance',
		thisWeekAverage: 'This week average',
		thisMonthAverage: 'This month average',
		workedDayUnit: 'work days',
		workedDayTemplate: '{count} work days',
		myWorkTime: 'My work time',
		day: 'Daily',
		week: 'Weekly',
		month: 'Monthly',
		weekSuffix: '',
		weekLabelTemplate: 'W{index}',
		monthLabelTemplate: 'M{index}',
		total: 'Total',
		trend: 'Work time trend',
		monthlyCalendar: 'Monthly calendar',
		attendanceRate: 'Attendance rate',
		locationDistribution: 'Location distribution',
		noData: 'No data',
		teamLog: 'Team log',
		loading: 'Loading...',
		empty: 'No records.',
		date: 'Date',
		event: 'Event',
		location: 'Location',
		status: 'Status',
		canceled: 'Canceled',
		recorded: 'Recorded',
		loadFailed: 'Could not load attendance information.',
		defaultLocation: 'Office',
		hourUnit: 'h',
		minuteUnit: 'm',
		processingFailed: 'Processing failed',
		teamBlocked: 'The administrator has hidden team attendance.',
		peopleWorkingTemplate: '{count} working',
		todayClockInTemplate: '{worked}/{total} clocked in today',
		peopleCountTemplate: '{count} people',
		dayBasisTemplate: 'Based on {count} days',
		subscriptionDayTemplate: '{count} days',
		calendarTitleTemplate: '{month} calendar',
		attendanceRateTitleTemplate: '{month} attendance rate',
		teamAttendanceCalendarTitleTemplate: '{month} attendance calendar',
		presentCountTemplate: '{present}/{total}',
		moreAbsencesTemplate: '+{count} records',
		teamMonthlyStatus: 'Monthly work status table',
		teamMonthlyStatusTable: 'Monthly work status table',
		mobileStatusView: 'Team status',
		mobileToolsView: 'My records',
		previousMonth: 'Previous month',
		nextMonth: 'Next month',
		previousYear: 'Previous year',
		nextYear: 'Next year',
		previousYearWindow: 'Previous 12 years',
		nextYearWindow: 'Next 12 years',
		teamMember: 'Employee',
		teamMemberSearchPlaceholder: 'Search employees',
		noMembers: 'No members to display.',
		eventNone: 'No events.',
		workRecords: 'Work records',
		workSegments: 'Work segments',
		calendarEvents: 'Calendar events',
		completedWork: 'Completed work',
		noCalendarEvents: 'No matching events.',
		noCompletedWork: 'No completed work.',
		calendarEventsLoadFailed: 'Could not load calendar events.',
		completedWorkLoadFailed: 'Could not load completed work.',
		calendarAllDay: 'All day',
		locationSegmentCountTemplate: '{count} segments',
		originalMessage: 'Original message',
		manualEntry: 'Manually added record without a message',
		agentConfidenceTemplate: 'Agent confidence: {percent}%',
		agentInitialClassification: 'Agent initial classification',
		current: 'Current',
		editedAtTemplate: '{user} edited at {time}',
		cancelReasonTemplate: 'Cancel reason: {reason}',
		cancelReasonRepeatedClick: 'Canceled by repeated click',
		cancelReasonAccidentalShortSegment: 'Canceled as an accidental short segment',
		cancelReasonSameLocationResume: 'Merged into the same-location session',
		classification: 'Classification',
		confirmClockOut: 'Confirm clock-out',
		skip: 'Skip',
		edit: 'Edit',
		save: 'Save',
		cancel: 'Cancel',
		close: 'Close',
		eventTime: 'Time',
		editReason: 'Edit reason',
		editReasonPlaceholder: 'Enter a reason for the edit',
		beforeEdit: 'Before edit',
		afterEdit: 'After edit',
		dateLocale: 'en-US',
		weekdaySunday: 'Sun',
		weekdayMonday: 'Mon',
		weekdayTuesday: 'Tue',
		weekdayWednesday: 'Wed',
		weekdayThursday: 'Thu',
		weekdayFriday: 'Fri',
		weekdaySaturday: 'Sat'
	}
} as const;

export type AttendanceText = typeof attendanceText.ko;
