export const attendanceText = {
	ko: {
		pageTitle: '출결 · intern kim',
		title: '출결',
		subtitle: '팀 전체 근무 기록과 개인 근무 시간',
		allUsers: '전체 사용자',
		allLocations: '전체 장소',
		refresh: '출결 새로고침',
		currentStatus: '현재 상태',
		working: '근무 중',
		clockIn: '출근',
		clockOut: '퇴근',
		today: '오늘',
		thisWeek: '이번 주',
		thisMonth: '이번 달',
		workedDayUnit: '일 근무',
		myWorkTime: '내 근무 시간',
		day: '일별',
		week: '주별',
		month: '월별',
		weekSuffix: '주',
		trend: '근무 시간 추세',
		monthlyCalendar: '월간 캘린더',
		teamLog: '팀 로그',
		loading: '불러오는 중...',
		empty: '기록이 없습니다.',
		date: '날짜',
		user: '사용자',
		event: '이벤트',
		location: '장소',
		status: '상태',
		canceled: '취소됨',
		recorded: '기록',
		loadFailed: '출결 정보를 불러오지 못했습니다.',
		defaultLocation: '사무실',
		hourUnit: '시간',
		minuteUnit: '분'
	},
	en: {
		pageTitle: 'Attendance · intern kim',
		title: 'Attendance',
		subtitle: 'Team attendance records and personal work time',
		allUsers: 'All users',
		allLocations: 'All locations',
		refresh: 'Refresh attendance',
		currentStatus: 'Current status',
		working: 'Working',
		clockIn: 'Clock in',
		clockOut: 'Clock out',
		today: 'Today',
		thisWeek: 'This week',
		thisMonth: 'This month',
		workedDayUnit: 'work days',
		myWorkTime: 'My work time',
		day: 'Daily',
		week: 'Weekly',
		month: 'Monthly',
		weekSuffix: '',
		trend: 'Work time trend',
		monthlyCalendar: 'Monthly calendar',
		teamLog: 'Team log',
		loading: 'Loading...',
		empty: 'No records.',
		date: 'Date',
		user: 'User',
		event: 'Event',
		location: 'Location',
		status: 'Status',
		canceled: 'Canceled',
		recorded: 'Recorded',
		loadFailed: 'Could not load attendance information.',
		defaultLocation: 'Office',
		hourUnit: 'h',
		minuteUnit: 'm'
	}
} as const;
