export const calendarText = {
	ko: {
		pageTitle: '일정 · 김인턴',
		title: '일정',
		subtitle: '팀 일정과 외부 일정 연동을 한 화면에서 다룹니다.',
		shared: '공유',
		refresh: '새로고침',
		syncTitle: '연동',
		syncDescription: 'Google은 구독 URL로 읽고, Apple 일정은 CalDAV로 연결합니다.',
		caldav: 'CalDAV',
		username: '사용자 이름',
		password: '비밀번호',
		ics: 'Google iCal',
		rotate: '구독 URL 재발급',
		copy: '복사',
		loading: '일정을 불러오는 중...',
		empty: '일정을 드래그하거나 더블클릭해서 새 일정을 만드세요.',
		error: '일정을 불러오지 못했습니다.',
		saveError: '일정을 저장하지 못했습니다.',
		deleteError: '일정을 삭제하지 못했습니다.',
		today: '오늘',
		newEvent: '새 일정'
	},
	en: {
		pageTitle: 'Calendar · intern kim',
		title: 'Calendar',
		subtitle: 'Team schedule and external calendar sync in one place.',
		shared: 'Shared',
		refresh: 'Refresh',
		syncTitle: 'Sync',
		syncDescription: 'Google reads the subscription URL. Apple Calendar connects through CalDAV.',
		caldav: 'CalDAV',
		username: 'Username',
		password: 'Password',
		ics: 'Google iCal',
		rotate: 'Rotate subscription URL',
		copy: 'Copy',
		loading: 'Loading calendar...',
		empty: 'Drag or double-click the calendar to create an event.',
		error: 'Could not load the calendar.',
		saveError: 'Could not save the event.',
		deleteError: 'Could not delete the event.',
		today: 'Today',
		newEvent: 'New Event'
	}
} as const;
