export const companyPageText = {
	ko: {
		protected: '비밀번호로 보호됨',
		unlockTitle: '회사 페이지를 열어보세요.',
		unlockDescription: '공유받은 비밀번호를 입력하면 게시된 회사 정보를 볼 수 있어요.',
		password: '비밀번호',
		passwordPlaceholder: '공유받은 비밀번호',
		unlock: '페이지 열기',
		wrongPassword: '비밀번호를 확인해 주세요.',
		unavailableTitle: '현재 공유 중인 페이지가 없어요.',
		unavailableDescription: '관리자가 페이지를 게시하면 이 주소에서 확인할 수 있어요.',
		loadError: '페이지를 불러오지 못했어요. 잠시 후 다시 시도해 주세요.',
		metrics: '핵심 지표',
		displayCurrency: '표시 통화',
		trends: '지표 추이',
		milestones: '주요 이력',
		facts: '회사 정보',
		founded: '설립',
		teamSize: '인원',
		people: '명',
		jurisdiction: '소재 국가·지역',
		representative: '대표자',
		capital: '자본금',
		fiscalYearEnd: '회계연도 말',
		website: '웹사이트',
		contact: '문의하기',
		published: '게시일',
		lock: '다시 잠그기',
		noMetrics: '공개된 지표가 없습니다.',
		noRecords: '공개된 주요 이력이 없습니다.',
		changeLanguage: 'Change language to English',
		story: {
			highlights: '핵심 하이라이트', traction: '축적된 성과 지표', latestPeriod: '최근 기간',
			increase: '직전 기간 대비', businessModel: '비즈니스 모델', customerEvidence: '고객 근거',
			marketOpportunity: '시장 기회', competitiveAdvantage: '경쟁력', milestones: '달성한 성과',
			roadmap: '향후 12개월', funding: '다음 단계', fundingTarget: '모집 목표', useOfFunds: '자금 사용 계획',
			contact: '자세한 이야기 나누기', noNarrative: '게시된 사업 정보가 없습니다.'
		},
		teamActivity: {
			title: '팀의 움직임이 쌓이고 있습니다.',
			description: '최근 출근과 업무 활동에서 만든 공개용 신호입니다. 선과 셀의 높이·농도, 업무 목록은 실제 데이터를 반영합니다.',
			activeTeam: '최근 활동한 팀', people: '활동 인원', activityRhythm: '최근 30일 활동 리듬', activityGrid: '날짜별 활동',
			attendanceSignals: '출근 신호', workSignals: '업무 신호', workDistribution: '업무 상태 분포', recentWork: '최근 업무 흐름',
			teamMember: '팀원', defaultJobTitle: '사원', otherBusiness: '기타',
			statusLabels: { planned: '준비', inProgress: '진행 중', completed: '완료', paused: '잠시 멈춤', closed: '종료' }
		}
	},
	en: {
		protected: 'Password protected',
		unlockTitle: 'Open the company page.',
		unlockDescription: 'Enter the shared password to view the published company information.',
		password: 'Password',
		passwordPlaceholder: 'Shared password',
		unlock: 'Open page',
		wrongPassword: 'Check the password and try again.',
		unavailableTitle: 'No page is currently shared.',
		unavailableDescription: 'Once an administrator publishes the page, it will be available here.',
		loadError: 'Could not load the page. Try again shortly.',
		metrics: 'Key metrics',
		displayCurrency: 'Display currency',
		trends: 'Metric trends',
		milestones: 'Milestones',
		facts: 'Company facts',
		founded: 'Founded',
		teamSize: 'Team size',
		people: 'people',
		jurisdiction: 'Jurisdiction',
		representative: 'Representative',
		capital: 'Capital',
		fiscalYearEnd: 'Fiscal year end',
		website: 'Website',
		contact: 'Contact',
		published: 'Published',
		lock: 'Lock again',
		noMetrics: 'No metrics are shared.',
		noRecords: 'No milestones are shared.',
		changeLanguage: '언어를 한국어로 변경',
		story: {
			highlights: 'Highlights', traction: 'Evidence over time', latestPeriod: 'Latest period',
			increase: 'from the previous period', businessModel: 'Business model', customerEvidence: 'Customer evidence',
			marketOpportunity: 'Market opportunity', competitiveAdvantage: 'Competitive advantage', milestones: 'What we have achieved',
			roadmap: 'The next 12 months', funding: 'The next stage', fundingTarget: 'Target raise', useOfFunds: 'Use of funds',
			contact: 'Continue the conversation', noNarrative: 'No business narrative is shared.'
		},
		teamActivity: {
			title: 'The team keeps moving.',
			description: 'A public signal built from recent attendance and work. Line height, cell intensity, and the work list come directly from real activity.',
			activeTeam: 'Recently active team', people: 'active people', activityRhythm: '30-day activity rhythm', activityGrid: 'Daily activity',
			attendanceSignals: 'attendance signals', workSignals: 'work signals', workDistribution: 'Work status distribution', recentWork: 'Recent work flow',
			teamMember: 'Member', defaultJobTitle: 'Staff', otherBusiness: 'Other',
			statusLabels: { planned: 'Planned', inProgress: 'In progress', completed: 'Completed', paused: 'Paused', closed: 'Closed' }
		}
	}
} as const;
