export const companyPageText = {
	ko: {
		protected: '비밀번호로 보호됨',
		unlockTitle: '회사 페이지를 열어보세요.',
		unlockDescription: '공유받은 비밀번호를 입력하면 게시된 회사 정보를 볼 수 있어요.',
		password: '비밀번호',
		passwordPlaceholder: '공유받은 비밀번호',
		unlock: '페이지 열기',
		wrongPassword: '비밀번호를 확인해 주세요.',
		unavailableTitle: '현재 공유 중인 페이지가 없어요.',
		unavailableDescription: '관리자가 페이지를 게시하면 이 주소에서 확인할 수 있어요.',
		loadError: '페이지를 불러오지 못했어요. 잠시 후 다시 시도해 주세요.',
		metrics: '핵심 지표',
		displayCurrency: '표시 통화',
		trends: '지표 추이',
		milestones: '주요 이력',
		facts: '회사 정보',
		founded: '설립',
		teamSize: '인원',
		people: '명',
		jurisdiction: '소재 국가·지역',
		representative: '대표자',
		capital: '자본금',
		fiscalYearEnd: '회계연도 말',
		website: '웹사이트',
		contact: '문의하기',
		published: '게시일',
		lock: '다시 잠그기',
		noMetrics: '공개된 지표가 없습니다.',
		noRecords: '공개된 주요 이력이 없습니다.',
		changeLanguage: 'Change language to English',
		story: {
			highlights: '핵심 하이라이트', traction: '축적된 성과 지표', latestPeriod: '최근 기간',
			increase: '직전 기간 대비', businessModel: '비즈니스 모델', customerEvidence: '고객 근거',
			marketOpportunity: '시장 기회', competitiveAdvantage: '경쟁력', milestones: '달성한 성과',
			source: '출처', documents: '검증 가능한 근거', documentDescription: '관리자가 회사 기록에서 선별한 문서 요약입니다.',
			documentTypes: { 'funding-summary': '투자 요약', 'grant-certificate': '선정 확인', 'award-certificate': '수상 확인', 'validation-report': '검증 보고서', 'security-assessment': '보안 평가' },
			evidenceRoles: { growth: '성장', efficiency: '효율', scale: '규모', quality: '품질', reach: '도달 범위', capital: '재무' },
			recordCategories: { funding: '투자', award: '수상', product: '제품', partnership: '파트너십', certification: '인증', ip: '지식재산', reference: '고객 근거', grant: '지원 사업', milestone: '주요 성과', growth: '성장' },
			roadmap: '향후 12개월', funding: '다음 단계', fundingTarget: '모집 목표', useOfFunds: '자금 사용 계획',
			contact: '자세한 이야기 나누기', noNarrative: '게시된 사업 정보가 없습니다.'
		},
		teamActivity: {
			title: '최근 30일, 팀은 꾸준히 실행했습니다.',
			description: '출근과 업무 업데이트를 날짜별로 집계한 익명 운영 신호입니다. 개인별 출퇴근 시각과 이메일은 공개하지 않습니다.',
			activeTeam: '최근 활동한 팀', people: '활동 인원', activeDays: '활동한 날', checkIns: '출근 인원', workUpdates: '업무 업데이트', activityRhythm: '최근 30일 활동 리듬', activityGrid: '날짜별 활동',
			attendanceSignals: '출근 인원', workSignals: '업무 업데이트', workDistribution: '업무 상태 분포', recentWork: '최근 업무 흐름',
			teamMember: '팀원', defaultJobTitle: '사원', otherBusiness: '기타',
			statusLabels: { planned: '준비', inProgress: '진행 중', completed: '완료', paused: '잠시 멈춤', closed: '종료' }
		}
	},
	en: {
		protected: 'Password protected',
		unlockTitle: 'Open the company page.',
		unlockDescription: 'Enter the shared password to view the published company information.',
		password: 'Password',
		passwordPlaceholder: 'Shared password',
		unlock: 'Open page',
		wrongPassword: 'Check the password and try again.',
		unavailableTitle: 'No page is currently shared.',
		unavailableDescription: 'Once an administrator publishes the page, it will be available here.',
		loadError: 'Could not load the page. Try again shortly.',
		metrics: 'Key metrics',
		displayCurrency: 'Display currency',
		trends: 'Metric trends',
		milestones: 'Milestones',
		facts: 'Company facts',
		founded: 'Founded',
		teamSize: 'Team size',
		people: 'people',
		jurisdiction: 'Jurisdiction',
		representative: 'Representative',
		capital: 'Capital',
		fiscalYearEnd: 'Fiscal year end',
		website: 'Website',
		contact: 'Contact',
		published: 'Published',
		lock: 'Lock again',
		noMetrics: 'No metrics are shared.',
		noRecords: 'No milestones are shared.',
		changeLanguage: '언어를 한국어로 변경',
		story: {
			highlights: 'Highlights', traction: 'Evidence over time', latestPeriod: 'Latest period',
			increase: 'from the previous period', businessModel: 'Business model', customerEvidence: 'Customer evidence',
			marketOpportunity: 'Market opportunity', competitiveAdvantage: 'Competitive advantage', milestones: 'What we have achieved',
			source: 'Source', documents: 'Verifiable evidence', documentDescription: 'Document summaries selected from the company record by an administrator.',
			documentTypes: { 'funding-summary': 'Funding summary', 'grant-certificate': 'Grant certificate', 'award-certificate': 'Award certificate', 'validation-report': 'Validation report', 'security-assessment': 'Security assessment' },
			evidenceRoles: { growth: 'Growth', efficiency: 'Efficiency', scale: 'Scale', quality: 'Quality', reach: 'Reach', capital: 'Financial' },
			recordCategories: { funding: 'Funding', award: 'Award', product: 'Product', partnership: 'Partnership', certification: 'Certification', ip: 'Intellectual property', reference: 'Customer evidence', grant: 'Grant', milestone: 'Milestone', growth: 'Growth' },
			roadmap: 'The next 12 months', funding: 'The next stage', fundingTarget: 'Target raise', useOfFunds: 'Use of funds',
			contact: 'Continue the conversation', noNarrative: 'No business narrative is shared.'
		},
		teamActivity: {
			title: 'Thirty days of steady execution.',
			description: 'An anonymized operating signal aggregated from daily attendance and work updates. Individual times and email addresses remain private.',
			activeTeam: 'Recently active team', people: 'active people', activeDays: 'active days', checkIns: 'check-ins', workUpdates: 'work updates', activityRhythm: '30-day activity rhythm', activityGrid: 'Daily activity',
			attendanceSignals: 'people checked in', workSignals: 'work updates', workDistribution: 'Work status distribution', recentWork: 'Recent work flow',
			teamMember: 'Member', defaultJobTitle: 'Staff', otherBusiness: 'Other',
			statusLabels: { planned: 'Planned', inProgress: 'In progress', completed: 'Completed', paused: 'Paused', closed: 'Closed' }
		}
	}
} as const;
