export const crmText = {
	ko: {
		pageTitle: 'CRM · 김인턴',
		title: 'CRM',
		description: '고객, 거래처, 투자사, 후원사, 파트너의 관계와 진행 상황을 한 화면에서 정리합니다.',
		prototypeBadge: 'UI 시제품',
		demoStateNote: '이 화면에서 변경한 내용은 새로고침하면 초기화됩니다.',
		searchPlaceholder: '관계처, 담당자, 태그 검색',
		allStatuses: '전체 관계 상태',
		allTypes: '전체 유형',
		quickCreate: '빠른 추가',
		newRelationship: '관계처',
		newContact: '담당자',
		newOpportunity: '진행 건',
		logActivity: '활동 기록',
		newNextAction: '다음 액션',
		importFile: '파일 가져오기',
		createTitle: 'CRM 기록 추가',
		createDescription: '기록 종류에 맞는 상세 내용을 한 번에 입력합니다.',
		recordKind: '기록 종류',
		name: '이름 또는 제목',
		selectRelationship: '관계처 선택',
		business: '사업',
		relatedProgress: '관련 진행상황',
		noRelatedProgress: '진행상황과 연결하지 않음',
		inheritedBusinessDescription: '관련 진행상황의 사업을 자동으로 적용합니다.',
		businessRequired: '사업을 선택해 주세요.',
		details: '비고',
		email: '이메일',
		ownerEmail: '담당자 이메일',
		phone: '전화번호',
		contactTitle: '직급·역할',
		contactName: '연락처 이름',
		activityTitle: '활동 제목',
		address: '회사 주소',
		addressPlaceholder: '예: 서울특별시 성동구 왕십리로 222',
		tags: '태그',
		tagsPlaceholder: '태그 입력 후 Enter',
		nextContactDate: '다음 진행일',
		activityKind: '활동 종류',
		occurredAt: '활동 일시',
		activityStatus: '활동 상태',
		taskOwner: '업무 담당자',
		registerCalendar: '캘린더에 등록',
		registerCalendarDescription: '체크하면 이 기록과 연결된 일정을 함께 만듭니다.',
		allDay: '종일 일정',
		startTime: '시작 시간',
		endTime: '종료 시간',
		endTimeAfterStart: '종료 시간은 시작 시간보다 늦어야 합니다.',
		location: '장소',
		amount: '금액',
		currency: '통화',
		currencyCount: '{count}개 통화',
		cancel: '취소',
		save: '저장',
		archive: '보관',
		archiveConfirm: '이 CRM 기록을 보관할까요?',
		loading: 'CRM 데이터를 불러오는 중입니다.',
		retry: '다시 시도',
		savedToService: 'CRM 서비스에 저장했습니다.',
		archivedFromService: 'CRM 기록을 보관했습니다.',
		create: '추가',
		requiredField: '이름 또는 제목을 입력해 주세요.',
		contactMethodRequired: '이메일 또는 전화번호를 입력해 주세요.',
		relationshipContactCreateFailed: '관계처는 저장했지만 외부 담당자를 저장하지 못했습니다. 관계처를 다시 만들지 않고 외부 담당자만 다시 저장합니다.',
		contactRelationshipConflict: '연결된 진행 건의 관계처와 달라서 변경할 수 없습니다: {names}',
		opportunityCustomerRequired: '관계처 또는 연결 담당자를 선택해 주세요.',
		organizationLoadFailed: '조직도 정보를 불러오지 못했습니다.',
		refreshAfterSaveFailed: '저장했지만 목록을 새로 불러오지 못했습니다. 다시 시도해 주세요.',
		fixtureModeReadOnly: 'Fixture 모드에서는 서버 저장을 확인할 수 없습니다.',
		permissionDenied: 'CRM을 보거나 수정할 권한이 없습니다.',
		processingFailed: 'CRM 데이터를 처리하지 못했습니다.',
		invalidRequest: '입력한 CRM 정보를 확인해 주세요.',
		recordNotFound: 'CRM 기록을 찾을 수 없습니다.',
		conflict: '다른 변경과 충돌했습니다. 새로고침 후 다시 시도해 주세요.',
		ownerNotFound: '담당자를 조직도에서 찾을 수 없습니다.',
		ownerAmbiguous: '담당자가 여러 명입니다. 이메일을 입력해 주세요.',
		lostReasonRequired: '손실 단계를 선택할 때는 손실 사유가 필요합니다.',
		baseCurrencyConversionRequired: '외화 진행 건은 기준 통화 환산액이 있어야 종결할 수 있습니다.',
		definitionInUse: '등록된 CRM 기록에서 사용 중인 항목입니다. 연결된 기록의 값을 변경한 후 삭제해 주세요.',
		lostReason: '손실 사유',
		selectLostReason: '손실 사유 선택',
		linkedContacts: '외부 담당자',
		noOrganizationContacts: '선택한 관계처에 등록된 담당자가 없습니다.',
		realizedAmountReadonly: '종결된 진행 건의 금액과 통화는 변경할 수 없습니다.',
		home: '홈',
		relationships: '관계처',
		contactDirectory: '연락처',
		pipeline: '진행상황',
		activities: '활동',
		nextActions: '다음 액션',
		reports: '리포트',
		definitions: '정의',
		paginationSummary: '{from}-{to} / 전체 {total}개',
		paginationPrevious: '이전',
		paginationNext: '다음',
		todayFocus: '오늘 처리할 일',
		todayFocusDescription: '지연된 액션과 정체된 진행 건을 우선순위대로 확인합니다.',
		workInbox: '오늘의 업무함',
		workInboxDescription: '다음 액션과 자동 수집된 초안을 한 흐름에서 검토합니다.',
		attentionRelationships: '주의가 필요한 관계',
		attentionRelationshipsDescription: '관심 낮음 또는 일시 중지 상태인 관계를 우선 표시합니다.',
		overdueActionCount: '기한 초과 {count}개',
		viewRecentActivity: '최근 활동 보기',
		allActions: '전체 액션',
		viewAll: '전체 보기',
		allOwners: '전체 담당자',
		allUrgencies: '전체 마감',
		noActions: '조건에 맞는 다음 액션이 없습니다.',
		completeAction: '완료',
		reopenAction: '다시 열기',
		keyOrganizations: '주요 관계처',
		stalePipeline: '정체된 진행 건',
		recentActivity: '최근 활동',
		intakeDrafts: '가져오기 초안',
		intakeDraftDescription: '메일, 파일, 일정에서 자동 입력될 내용을 미리 검토하는 영역입니다.',
		approve: '반영',
		edit: '수정',
		reject: '제외',
		noDrafts: '검토할 가져오기 초안이 없습니다.',
		confidence: '신뢰도',
		suggestedAction: '추천 처리',
		activityTimeline: '활동 타임라인',
		organizationName: '관계처',
		type: '유형',
		status: '관계 상태',
		owner: '담당자',
		progressOwner: '내부 담당자',
		internalOwner: '내부 담당자',
		selectInternalOwner: '내부 담당자 선택',
		searchInternalOwner: '이름 또는 이메일 검색',
		selectExternalContact: '외부 담당자 선택',
		searchExternalContact: '이름 또는 이메일 검색',
		team: '팀',
		lastContact: '마지막 접촉',
		nextAction: '다음 액션',
		opportunity: '진행 건',
		stage: '단계',
		targetDate: '목표일',
		staleDays: '경과 기간',
		stageElapsedDescription: '현재 단계에 진입한 후 지난 기간',
		expectedValue: '예상 금액',
		dueDate: '마감일',
		importance: '중요도',
		externalContact: '외부 담당자',
		newExternalContact: '외부 담당자 추가',
		addExternalContact: '외부 담당자 함께 등록',
		addExternalContactDescription: '관계처를 만든 뒤 이 담당자를 바로 연결합니다.',
		relationshipAlreadyCreated: '관계처는 이미 저장되었습니다. 외부 담당자 정보를 확인하고 다시 저장해 주세요.',
		openOpportunities: '진행 건',
		contacts: '외부 담당자',
		relationshipDetail: '관계처 상세',
		editRelationship: '관계처 수정',
		editRelationshipDescription: '관계 정보, 담당자, 접촉 일정과 비고를 수정합니다.',
		editOpportunity: '진행 건 수정',
		editOpportunityDescription: '연결 관계처, 사업, 진행 유형, 단계, 금액과 비고를 수정합니다.',
		editContact: '연락처 수정',
		editContactDescription: '연결 관계처, 연락처 정보와 비고를 수정합니다.',
		editActivity: '활동 수정',
		editActivityDescription: '관련 진행상황, 사업, 활동 정보와 연결된 업무 상태를 수정합니다.',
		openDetail: '상세 보기',
		linkedTask: '연결 업무',
		linkedCalendar: '연결 일정',
		openTask: '업무에서 수정',
		openCalendar: '캘린더에서 수정',
		sourceEditNotice: '연결 업무와 일정은 각 원본 페이지에서도 수정할 수 있습니다.',
		updateLinkedCalendar: '활동 일시 변경을 연결 일정에도 반영',
		updateLinkedCalendarDescription: '체크하면 연결된 일정의 시작 시각을 함께 변경합니다.',
		none: '없음',
		missingTask: '연결 업무를 찾을 수 없음',
		calendarRegistered: '캘린더 등록됨',
		calendarRegistrationFailed: '기록은 저장했지만 캘린더 등록에 실패했습니다. 활동 또는 진행 건 상세에서 다시 등록할 수 있습니다.',
		retryCalendar: '캘린더 다시 등록',
		linkedSourceLoadError: '업무 정보를 불러오지 못했습니다.',
		taskCreateError: '활동과 연결할 업무를 만들지 못했습니다.',
		taskUpdateError: '연결된 업무를 수정하지 못했습니다.',
		calendarCreateError: '연결할 캘린더 일정을 만들지 못했습니다.',
		calendarUpdateError: '연결된 캘린더 일정을 수정하지 못했습니다.',
		activityCalendarUpdatePartialFailure: '활동과 업무는 저장했지만 연결 일정 변경에 실패했습니다.',
		creating: '등록 중',
		overview: '개요',
		activity: '활동',
		progress: '진행 건',
		allRelationships: '전체 관계처',
		allContacts: '전체 연락처',
		allActivityKinds: '전체 활동',
		myRelationships: '내 담당',
		needsAttention: '확인 필요',
		recentlyContacted: '최근 접촉',
		tableView: '목록',
		boardView: '보드',
		noProgress: '이 단계의 진행 건이 없습니다.',
		progressKind: '진행 유형',
		allProgressKinds: '전체',
		progressKinds: {
			sales: '판매',
			fundraising: '투자 유치',
			investment: '투자',
			sponsorship: '후원',
			partnership: '파트너십',
			procurement: '구매·협력'
		},
		importTitle: 'CRM 파일 가져오기',
		importDescription: '파일을 확인하고 열 매핑과 중복 처리 기준을 정한 뒤 반영합니다.',
		uploadStep: '파일 선택',
		mappingStep: '열 매핑',
		duplicateStep: '중복 확인',
		reviewStep: '반영 검토',
		completeStep: '완료',
		chooseSampleFile: '샘플 CSV 불러오기',
		continue: '계속',
		back: '이전',
		importRows: '20개 행을 찾았습니다.',
		duplicateDetected: '기존 관계처와 이름이 같은 2개 행을 찾았습니다.',
		skipDuplicates: '중복 행은 건너뛰기',
		importReady: '18개 관계처와 담당자 정보를 반영할 준비가 되었습니다.',
		importComplete: '샘플 데이터 18개를 가져왔습니다.',
		prototypeChanged: 'UI 시제품에 변경 내용을 반영했습니다.',
		stageReport: '단계별 현황',
		ownerReport: '담당자별 현황',
		ownerReportDescription: '담당자별 관계처와 열린 진행 건, 후속 액션 누락을 비교합니다.',
		quietOrganizations: '장기 미접촉 관계처',
		quietOrganizationsDescription: '마지막 접촉일이 오래된 관계처부터 확인합니다.',
		reportPeriod: '분석 기간',
		reportPeriodDescription: '진행 건의 목표일을 기준으로 리포트 범위를 조정합니다.',
		reportPeriodQuarter: '2026년 3분기',
		reportPeriodNext90Days: '향후 90일',
		reportPeriodAll: '전체 기간',
		reportSummary: '핵심 리포트 지표',
		exportCSV: 'CSV 내보내기',
		openValue: '예상 금액',
		wonValue: '성사 금액',
		currencyValueComparison: '통화별 금액 비교',
		currencyValueComparisonDescription: '통화별 예상 금액과 성사 금액을 비교합니다. 막대 길이는 각 통화 안에서만 비교됩니다.',
		won: '성사',
		monthlyClosingForecast: '월별 예상 마감 금액',
		monthlyClosingForecastDescription: '목표일 기준 열린 금액과 성사 금액을 비교합니다.',
		stageReportDescription: '단계별 진행 건 수와 예상 금액입니다.',
		progressKindReport: '진행 유형별 구성',
		progressKindReportDescription: '판매, 투자, 후원, 파트너십, 구매·협력 목적별 구성을 봅니다.',
		openProgress: '열린 진행 건',
		missingActions: '후속 액션 누락',
		noReportData: '선택한 기간에 해당하는 진행 건이 없습니다.',
		noOrganizations: '조건에 맞는 관계처가 없습니다.',
		noContacts: '조건에 맞는 연락처가 없습니다.',
		noActivities: '조건에 맞는 활동이 없습니다.',
		noValue: '금액 없음',
		daysAgo: '{days}일',
		organizationCount: '{count}개 계정',
		opportunityCount: '{count}개 진행 건',
		missingActionCount: '액션 누락 {count}개',
		totalExpectedValue: '열린 예상 금액',
		overdueActions: '기한 지난 연계 업무',
		highImportanceOrganizations: '중요 계정',
		pendingDrafts: '검토 대기 초안',
		activePipeline: '열린 파이프라인',
		kpiPipelineHealth: '진행 현황',
		kpiPipelineHealthDescription: '열린 예상 금액의 진행 속도와 정체 상태입니다.',
		kpiRelationshipHealth: '관계 관리',
		kpiRelationshipHealthDescription: '활성 관계처의 최근 접촉과 확인 필요 상태입니다.',
		kpiFollowUpHealth: '후속 조치',
		kpiFollowUpHealthDescription: 'CRM 관계처와 연결된 업무의 마감 상태입니다.',
		kpiPipelineComposition: '진행 유형 구성',
		kpiPipelineCompositionDescription: '열린 진행 건이 어떤 관계 목적으로 구성됐는지 보여줍니다.',
		kpiOpenValue: '열린 예상 금액',
		kpiActiveRelationships: '활성 관계처',
		kpiOpenActions: '열린 업무',
		kpiOpenProgress: '열린 진행 건',
		kpiMoving: '정상 진행',
		kpiStalled: '정체',
		kpiOnHold: '보류',
		kpiRecentlyContacted: '최근 접촉',
		kpiStable: '안정',
		kpiNeedsAttention: '확인 필요',
		kpiScheduled: '예정',
		kpiDueSoon: '오늘·임박',
		kpiOverdue: '기한 초과',
		kpiSales: '판매',
		kpiInvestment: '투자',
		kpiCollaboration: '후원·협력',
		kpiCountSuffix: '건',
		activityKinds: {
			note: '메모',
			email: '메일',
			meeting: '미팅',
			call: '통화',
			task: '업무',
			file: '파일',
			event: '이벤트',
			stage_change: '단계 변경'
		},
		organizationTypes: {
			customer: '고객사',
			partner: '파트너',
			sponsor: '스폰서',
			vendor: '협력사',
			investor: '투자자',
			portfolio: '투자 대상',
			other: '기타'
		},
		organizationStatuses: {
			prospect: '잠재 관계',
			active: '활성',
			paused: '보류'
		},
		opportunityStages: {
			lead: '리드',
			qualified: '검토',
			proposal: '제안',
			negotiation: '협의',
			won: '성사',
			lost: '실패',
			on_hold: '보류'
		},
		nextActionStatuses: {
			todo: '해야 할 일',
			in_progress: '진행 중',
			waiting: '회신 대기',
			done: '완료',
			paused: '일시정지',
			cancelled: '중단'
		},
		actionUrgencies: {
			overdue: '지연',
			today: '오늘',
			due_soon: '임박',
			scheduled: '예정',
			done: '완료'
		},
		importanceLabels: {
			high: '높음',
			medium: '보통',
			low: '낮음'
		},
		intakeSources: {
			file: '파일',
			mail: '메일',
			calendar: '일정'
		}
	},
	en: {
		pageTitle: 'CRM · InternKim',
		title: 'CRM',
		description: 'Track customers, vendors, investors, sponsors, and partners in one internal workspace.',
		prototypeBadge: 'UI prototype',
		demoStateNote: 'Changes made here reset when the page refreshes.',
		searchPlaceholder: 'Search relationships, owners, or tags',
		allStatuses: 'All relationship statuses',
		allTypes: 'All types',
		quickCreate: 'Quick add',
		newRelationship: 'Relationship',
		newContact: 'Contact',
		newOpportunity: 'Opportunity',
		logActivity: 'Log activity',
		newNextAction: 'Next action',
		importFile: 'Import file',
		createTitle: 'Add CRM record',
		createDescription: 'Enter the complete details for the selected record type.',
		recordKind: 'Record type',
		name: 'Name or title',
		selectRelationship: 'Select relationship',
		business: 'Business',
		relatedProgress: 'Related progress',
		noRelatedProgress: 'Not linked to progress',
		inheritedBusinessDescription: 'Uses the business from the related progress automatically.',
		businessRequired: 'Select a business.',
		details: 'Details',
		email: 'Email',
		ownerEmail: 'Owner email',
		phone: 'Phone',
		contactTitle: 'Title or role',
		contactName: 'Contact name',
		activityTitle: 'Activity title',
		address: 'Company address',
		addressPlaceholder: 'e.g. 222 Wangsimni-ro, Seongdong-gu, Seoul',
		tags: 'Tags',
		tagsPlaceholder: 'Type a tag and press Enter',
		nextContactDate: 'Next progress date',
		activityKind: 'Activity type',
		occurredAt: 'Activity date and time',
		activityStatus: 'Activity status',
		taskOwner: 'Task owner',
		registerCalendar: 'Add to calendar',
		registerCalendarDescription: 'Creates a calendar event linked to this record.',
		allDay: 'All-day event',
		startTime: 'Start time',
		endTime: 'End time',
		endTimeAfterStart: 'End time must be later than start time.',
		location: 'Location',
		amount: 'Amount',
		currency: 'Currency',
		currencyCount: '{count} currencies',
		cancel: 'Cancel',
		save: 'Save',
		archive: 'Archive',
		archiveConfirm: 'Archive this CRM record?',
		loading: 'Loading CRM data.',
		retry: 'Retry',
		savedToService: 'Saved to the CRM service.',
		archivedFromService: 'Archived the CRM record.',
		create: 'Add',
		requiredField: 'Enter a name or title.',
		contactMethodRequired: 'Enter an email address or phone number.',
		relationshipContactCreateFailed: 'The relationship was saved, but the external contact was not. Retry saves only the contact without creating another relationship.',
		contactRelationshipConflict: 'This contact cannot move because these linked opportunities belong to another relationship: {names}',
		opportunityCustomerRequired: 'Select a relationship or linked contact.',
		organizationLoadFailed: 'Could not load the organization directory.',
		refreshAfterSaveFailed: 'Saved, but the list could not be refreshed. Try again.',
		fixtureModeReadOnly: 'Server persistence is unavailable in fixture mode.',
		permissionDenied: 'You do not have permission to view or edit CRM records.',
		processingFailed: 'Could not process the CRM data.',
		invalidRequest: 'Check the CRM information and try again.',
		recordNotFound: 'The CRM record could not be found.',
		conflict: 'This record conflicts with another change. Reload and try again.',
		ownerNotFound: 'The owner could not be found in the organization directory.',
		ownerAmbiguous: 'Multiple owners match. Enter an email address.',
		lostReasonRequired: 'Select a lost reason before moving to a lost stage.',
		baseCurrencyConversionRequired: 'Foreign-currency progress requires a converted base amount before it can be closed.',
		definitionInUse: 'This item is used by an existing CRM record. Change the linked record before deleting it.',
		lostReason: 'Lost reason',
		selectLostReason: 'Select lost reason',
		linkedContacts: 'External contacts',
		noOrganizationContacts: 'The selected relationship has no contacts.',
		realizedAmountReadonly: 'Amount and currency cannot be changed after progress is closed.',
		home: 'Home',
		relationships: 'Relationships',
		contactDirectory: 'Contacts',
		pipeline: 'Progress',
		activities: 'Activities',
		nextActions: 'Next actions',
		reports: 'Reports',
		definitions: 'Definitions',
		paginationSummary: '{from}-{to} of {total}',
		paginationPrevious: 'Previous',
		paginationNext: 'Next',
		todayFocus: 'Today\'s focus',
		todayFocusDescription: 'Review overdue actions and stalled progress in priority order.',
		workInbox: 'Today\'s inbox',
		workInboxDescription: 'Review next actions and automatically collected drafts in one flow.',
		attentionRelationships: 'Relationships needing attention',
		attentionRelationshipsDescription: 'Prioritized by cold or paused relationship status.',
		overdueActionCount: '{count} overdue',
		viewRecentActivity: 'View recent activity',
		allActions: 'All actions',
		viewAll: 'View all',
		allOwners: 'All owners',
		allUrgencies: 'All due dates',
		noActions: 'No next actions match this view.',
		completeAction: 'Complete',
		reopenAction: 'Reopen',
		keyOrganizations: 'Key relationships',
		stalePipeline: 'Stale progress',
		recentActivity: 'Recent activity',
		intakeDrafts: 'Import drafts',
		intakeDraftDescription: 'Review information suggested from mail, files, and calendar before saving.',
		approve: 'Apply',
		edit: 'Edit',
		reject: 'Exclude',
		noDrafts: 'There are no import drafts to review.',
		confidence: 'Confidence',
		suggestedAction: 'Suggested action',
		activityTimeline: 'Activity timeline',
		organizationName: 'Relationship',
		type: 'Type',
		status: 'Relationship status',
		owner: 'Owner',
		progressOwner: 'Internal owner',
		internalOwner: 'Internal owner',
		selectInternalOwner: 'Select internal owner',
		searchInternalOwner: 'Search by name or email',
		selectExternalContact: 'Select external contact',
		searchExternalContact: 'Search by name or email',
		team: 'Team',
		lastContact: 'Last contact',
		nextAction: 'Next action',
		opportunity: 'Opportunity',
		stage: 'Stage',
		targetDate: 'Target date',
		staleDays: 'Time in stage',
		stageElapsedDescription: 'Time elapsed since this opportunity entered its current stage.',
		expectedValue: 'Expected value',
		dueDate: 'Due date',
		importance: 'Importance',
		externalContact: 'External contact',
		newExternalContact: 'Add external contact',
		addExternalContact: 'Add an external contact',
		addExternalContactDescription: 'Creates and links this contact immediately after the relationship is created.',
		relationshipAlreadyCreated: 'The relationship is already saved. Check the external contact and retry.',
		openOpportunities: 'Open opportunities',
		contacts: 'Contacts',
		relationshipDetail: 'Relationship detail',
		editRelationship: 'Edit relationship',
		editRelationshipDescription: 'Update relationship details, ownership, contact dates, and notes.',
		editOpportunity: 'Edit opportunity',
		editOpportunityDescription: 'Update the linked relationship, business, progress type, stage, amount, and details.',
		editContact: 'Edit contact',
		editContactDescription: 'Update the linked relationship, contact information, and details.',
		editActivity: 'Edit activity',
		editActivityDescription: 'Update the related progress, business, activity, and linked task status.',
		openDetail: 'Open detail',
		linkedTask: 'Linked task',
		linkedCalendar: 'Linked calendar event',
		openTask: 'Edit in Tasks',
		openCalendar: 'Edit in Calendar',
		sourceEditNotice: 'Linked tasks and events can also be edited from their source pages.',
		updateLinkedCalendar: 'Apply activity time changes to linked event',
		updateLinkedCalendarDescription: 'When checked, the linked event start time changes with the activity.',
		none: 'None',
		missingTask: 'Linked task not found',
		calendarRegistered: 'Added to calendar',
		calendarRegistrationFailed: 'The record was saved, but the calendar event could not be created. Retry from the activity or progress detail.',
		retryCalendar: 'Retry calendar registration',
		linkedSourceLoadError: 'Could not load task information.',
		taskCreateError: 'Could not create the task linked to this activity.',
		taskUpdateError: 'Could not update the task linked to this activity.',
		calendarCreateError: 'Could not create the linked calendar event.',
		calendarUpdateError: 'Could not update the linked calendar event.',
		activityCalendarUpdatePartialFailure: 'The activity and task were saved, but the linked event could not be updated.',
		creating: 'Creating',
		overview: 'Overview',
		activity: 'Activity',
		progress: 'Progress',
		allRelationships: 'All relationships',
		allContacts: 'All contacts',
		allActivityKinds: 'All activities',
		myRelationships: 'Owned by me',
		needsAttention: 'Needs attention',
		recentlyContacted: 'Recently contacted',
		tableView: 'List',
		boardView: 'Board',
		noProgress: 'No progress records in this stage.',
		progressKind: 'Progress type',
		allProgressKinds: 'All',
		progressKinds: {
			sales: 'Sales',
			fundraising: 'Fundraising',
			investment: 'Investment',
			sponsorship: 'Sponsorship',
			partnership: 'Partnership',
			procurement: 'Procurement'
		},
		importTitle: 'Import CRM file',
		importDescription: 'Review the file, map columns, and choose duplicate rules before applying it.',
		uploadStep: 'Choose file',
		mappingStep: 'Map columns',
		duplicateStep: 'Check duplicates',
		reviewStep: 'Review import',
		completeStep: 'Complete',
		chooseSampleFile: 'Load sample CSV',
		continue: 'Continue',
		back: 'Back',
		importRows: '20 rows found.',
		duplicateDetected: '2 rows share a name with an existing relationship.',
		skipDuplicates: 'Skip duplicate rows',
		importReady: '18 relationships and contacts are ready to import.',
		importComplete: 'Imported 18 sample records.',
		prototypeChanged: 'The UI prototype has been updated.',
		stageReport: 'Pipeline by stage',
		ownerReport: 'Owner summary',
		ownerReportDescription: 'Compare relationships, open progress, and missing follow-up actions by owner.',
		quietOrganizations: 'Quiet relationships',
		quietOrganizationsDescription: 'Review relationships with the oldest contact dates first.',
		reportPeriod: 'Report period',
		reportPeriodDescription: 'Adjust the report range using opportunity target dates.',
		reportPeriodQuarter: 'Q3 2026',
		reportPeriodNext90Days: 'Next 90 days',
		reportPeriodAll: 'All time',
		reportSummary: 'Report summary',
		exportCSV: 'Export CSV',
		openValue: 'Expected value',
		wonValue: 'Won value',
		currencyValueComparison: 'Value comparison by currency',
		currencyValueComparisonDescription: 'Compare expected and won values within each currency. Bar lengths are scaled separately for each currency.',
		won: 'Won',
		monthlyClosingForecast: 'Monthly closing forecast',
		monthlyClosingForecastDescription: 'Compare open and won value by target month.',
		stageReportDescription: 'Opportunity count and expected value by stage.',
		progressKindReport: 'Progress type mix',
		progressKindReportDescription: 'Compare sales, investment, sponsorship, partnership, and procurement work.',
		openProgress: 'Open progress',
		missingActions: 'Missing follow-up',
		noReportData: 'No opportunities match the selected period.',
		noOrganizations: 'No relationships match these filters.',
		noContacts: 'No contacts match these filters.',
		noActivities: 'No activities match these filters.',
		noValue: 'No amount',
		daysAgo: '{days} days',
		organizationCount: '{count} organizations',
		opportunityCount: '{count} opportunities',
		missingActionCount: '{count} missing actions',
		totalExpectedValue: 'Open expected value',
		overdueActions: 'Overdue linked tasks',
		highImportanceOrganizations: 'Important organizations',
		pendingDrafts: 'Drafts to review',
		activePipeline: 'Open pipeline',
		kpiPipelineHealth: 'Progress health',
		kpiPipelineHealthDescription: 'Open expected value split by movement and stalled status.',
		kpiRelationshipHealth: 'Relationship health',
		kpiRelationshipHealthDescription: 'Recent contact and attention status across active relationships.',
		kpiFollowUpHealth: 'Follow-up health',
		kpiFollowUpHealthDescription: 'Due status of work linked to CRM relationships.',
		kpiPipelineComposition: 'Progress mix',
		kpiPipelineCompositionDescription: 'How open progress is distributed across relationship goals.',
		kpiOpenValue: 'Open expected value',
		kpiActiveRelationships: 'Active relationships',
		kpiOpenActions: 'Open tasks',
		kpiOpenProgress: 'Open progress',
		kpiMoving: 'Moving',
		kpiStalled: 'Stalled',
		kpiOnHold: 'On hold',
		kpiRecentlyContacted: 'Recently contacted',
		kpiStable: 'Stable',
		kpiNeedsAttention: 'Needs attention',
		kpiScheduled: 'Scheduled',
		kpiDueSoon: 'Today or due soon',
		kpiOverdue: 'Overdue',
		kpiSales: 'Sales',
		kpiInvestment: 'Investment',
		kpiCollaboration: 'Sponsor or partner',
		kpiCountSuffix: '',
		activityKinds: {
			note: 'Note',
			email: 'Email',
			meeting: 'Meeting',
			call: 'Call',
			task: 'Task',
			file: 'File',
			event: 'Event',
			stage_change: 'Stage change'
		},
		organizationTypes: {
			customer: 'Customer',
			partner: 'Partner',
			sponsor: 'Sponsor',
			vendor: 'Vendor',
			investor: 'Investor',
			portfolio: 'Portfolio',
			other: 'Other'
		},
		organizationStatuses: {
			prospect: 'Prospect',
			active: 'Active',
			paused: 'Paused'
		},
		opportunityStages: {
			lead: 'Lead',
			qualified: 'Qualified',
			proposal: 'Proposal',
			negotiation: 'Negotiation',
			won: 'Won',
			lost: 'Lost',
			on_hold: 'On hold'
		},
		nextActionStatuses: {
			todo: 'To do',
			in_progress: 'In progress',
			waiting: 'Waiting',
			done: 'Done',
			paused: 'Paused',
			cancelled: 'Cancelled'
		},
		actionUrgencies: {
			overdue: 'Overdue',
			today: 'Today',
			due_soon: 'Due soon',
			scheduled: 'Scheduled',
			done: 'Done'
		},
		importanceLabels: {
			high: 'High',
			medium: 'Medium',
			low: 'Low'
		},
		intakeSources: {
			file: 'File',
			mail: 'Mail',
			calendar: 'Calendar'
		}
	}
} as const;

export type CRMText = typeof crmText.ko;
