import type { PageText } from '$lib/i18n/page-text.svelte';
import { taskText } from '../task/text';

export const crmText = {
	ko: {
		pageTitle: 'CRM · 김인턴',
		searchPlaceholder: '관계처, 연락처, 태그 검색',
		newRelationship: '관계처',
		newContact: '연락처',
		newOpportunity: '거래',
		logActivity: '활동 기록',
		createTitle: 'CRM 기록 추가',
		createDescription: '기록 종류에 맞는 상세 내용을 한 번에 입력합니다.',
		recordKind: '기록 종류',
		name: '이름 또는 제목',
		selectRelationship: '관계처 선택',
		business: '사업',
		relatedProgress: '관련 거래',
		noRelatedProgress: '거래와 연결하지 않음',
		details: '비고',
		email: '이메일',
		ownerEmail: '담당자 이메일',
		phone: '전화번호',
		contactTitle: '직급·역할',
		contactName: '연락처 이름',
		activityTitle: '활동 제목',
		address: '주소',
		addressPlaceholder: '예: 서울특별시 예시구 예시로 1',
		tags: '태그',
		tagsPlaceholder: '태그 입력 후 Enter',
		nextContactDate: '다음 연락일',
		activityKind: '활동 종류',
		assignee: '담당자',
		columnKind: '종류',
		columnSize: '크기',
		columnStartDate: '시작일',
		columnEndDate: '종료일',
		occurredAt: '활동 일시',
		activityStatus: '활동 상태',
		registerCalendar: '캘린더에 등록',
		registerCalendarDescription: '체크하면 이 기록과 연결된 일정을 함께 만듭니다.',
		allDay: '종일 일정',
		startTime: '시작 시간',
		endTime: '종료 시간',
		endTimeAfterStart: '종료 시간은 시작 시간보다 늦어야 합니다.',
		location: '장소',
		amount: '금액',
		resetFilters: '초기화',
		filters: '필터',
		sort: '정렬',
		metricsOverview: 'CRM 현황',
		sortAscending: '오름차순 정렬 중',
		sortDescending: '내림차순 정렬 중',
		currency: '통화',
		viewCurrency: '보기 통화',
		viewCurrencyFailed: '환율을 불러오지 못해 보기 통화를 바꾸지 못했습니다.',
		cancel: '취소',
		save: '저장',
		archive: '보관',
		archiveConfirm: '이 CRM 기록을 보관할까요?',
		loading: 'CRM 데이터를 불러오는 중입니다.',
		directoryLoading: '담당자 정보를 불러오는 중입니다. 기록은 볼 수 있으며 담당자 선택은 준비 후 사용할 수 있습니다.',
		currencyUnavailable: '거래 금액을 표시하는 데 필요한 통화 정보를 불러오지 못했습니다. 다시 시도해 주세요.',
		retry: '다시 시도',
		savedToService: 'CRM 서비스에 저장했습니다.',
		archivedFromService: 'CRM 기록을 보관했습니다.',
		create: '추가',
		requiredField: '이름 또는 제목을 입력해 주세요.',
		contactMethodRequired: '이메일 또는 전화번호를 입력해 주세요.',
		relationshipContactCreateFailed: '관계처는 저장했지만 연락처를 저장하지 못했습니다. 관계처를 다시 만들지 않고 연락처만 다시 저장합니다.',
		contactRelationshipConflict: '연결된 거래의 관계처와 달라서 변경할 수 없습니다: {names}',
		opportunityCustomerRequired: '관계처 또는 연결 연락처를 선택해 주세요.',
		organizationLoadFailed: '조직도 정보를 불러오지 못했습니다.',
		refreshAfterSaveFailed: '저장했지만 목록을 새로 불러오지 못했습니다. 다시 시도해 주세요.',
		fixtureModeReadOnly: 'Fixture 모드에서는 서버 저장을 확인할 수 없습니다.',
		permissionDenied: 'CRM을 보거나 수정할 권한이 없습니다.',
		processingFailed: 'CRM 데이터를 처리하지 못했습니다.',
		invalidRequest: '입력한 CRM 정보를 확인해 주세요.',
		recordNotFound: 'CRM 기록을 찾을 수 없습니다.',
		conflict: '다른 변경과 충돌했습니다. 새로고침 후 다시 시도해 주세요.',
		ownerNotFound: '담당자를 조직도에서 찾을 수 없습니다.',
		ownerAmbiguous: '담당자가 여러 명입니다. 이메일을 입력해 주세요.',
		lostReasonRequired: '실패 단계를 선택할 때는 실패 사유가 필요합니다.',
		definitionInUse: '등록된 CRM 기록에서 사용 중인 항목입니다. 연결된 기록의 값을 변경한 후 삭제해 주세요.',
		lostReasonPrompt: '실패 사유',
		noOrganizationContacts: '선택한 관계처에 등록된 연락처가 없습니다.',
		realizedAmountReadonly: '종결된 거래의 금액과 통화는 변경할 수 없습니다.',
		conversionSettled: '확정',
		conversionEstimate: '{date} 환율 기준 예상',
		relationships: '관계처',
		contactDirectory: '연락처',
		pipeline: '거래',
		activities: '활동',
		reports: '보고',
		definitions: {
			title: '정의',
			organizationTypes: '관계처 유형',
			pipelines: '파이프라인',
			add: '추가',
			remove: '삭제',
			removeTitle: '항목 삭제',
			removeDescription: '"{name}" 항목을 삭제할까요?',
			cancel: '취소',
			color: '색상',
			done: '완료',
			nameRequired: '이름을 입력하세요.',
			emptyList: '아직 없습니다.',
			saving: '저장 중입니다.'
		},
		paginationSummary: '{from}-{to} / 전체 {total}개',
		paginationPrevious: '이전',
		paginationNext: '다음',
		edit: '수정',
		organizationName: '관계처',
		type: '유형',
		status: '상태',
		owner: '담당자',
		progressOwner: '담당자',
		internalOwner: '담당자',
		selectInternalOwner: '담당자 선택',
		searchInternalOwner: '이름 또는 이메일 검색',
		selectExternalContact: '연락처 선택',
		searchExternalContact: '이름 또는 이메일 검색',
		lastContact: '마지막 연락',
		nextAction: '다음 활동',
		opportunity: '거래',
		stage: '단계',
		targetDate: '마감 예정일',
		staleDays: '경과 기간',
		stageElapsedDescription: '현재 단계에 진입한 후 지난 기간',
		expectedValue: '금액',
		importance: '우선순위',
		externalContact: '연락처',
		newExternalContact: '연락처 추가',
		addExternalContact: '연락처 함께 등록',
		addExternalContactDescription: '관계처를 만든 뒤 이 연락처를 바로 연결합니다.',
		relationshipAlreadyCreated: '관계처는 이미 저장되었습니다. 연락처 정보를 확인하고 다시 저장해 주세요.',
		openOpportunities: '열린 거래',
		contacts: '연락처',
		editRelationship: '관계처 수정',
		editRelationshipDescription: '관계처 정보, 담당자, 연락 일정과 비고를 수정합니다.',
		editOpportunity: '거래 수정',
		editOpportunityDescription: '연결 관계처, 사업, 파이프라인, 단계, 금액과 비고를 수정합니다.',
		editContact: '연락처 수정',
		editContactDescription: '연결 관계처, 연락처 정보와 비고를 수정합니다.',
		editActivity: '활동 수정',
		editActivityDescription: '관련 거래, 사업, 활동 정보와 연결된 업무 상태를 수정합니다.',
		linkedCalendar: '연결 일정',
		none: '없음',
		calendarRegistered: '캘린더 등록됨',
		calendarCreateError: '연결할 캘린더 일정을 만들지 못했습니다.',
		creating: '등록 중',
		overview: '개요',
		activity: '활동',
		progress: '거래',
		allRelationships: '전체',
		myRelationships: '내 담당',
		needsAttention: '확인 필요',
		tableView: '목록',
		boardView: '보드',
		noProgress: '이 단계에 거래가 없습니다.',
		progressKind: '파이프라인',
		progressKinds: {
			sales: '영업',
			fundraising: '투자 유치',
			investment: '투자',
			sponsorship: '후원',
			partnership: '파트너십',
			procurement: '구매'
		},
		stageReport: '단계별 파이프라인',
		openDealAmount: '열린 거래 금액',
		winRate: '성사율',
		daysSinceContact: '{days}일 전',
		elapsedSinceContact: '경과',
		ownerReport: '담당자별 현황',
		quietOrganizations: '장기 미연락 관계처',
		reportPeriod: '분석 기간',
		reportPeriodQuarter: '{year}년 {quarter}분기',
		reportPeriodNext90Days: '향후 90일',
		reportPeriodAll: '전체 기간',
		openValue: '금액',
		wonValue: '성사 금액',
		won: '성사',
		monthlyClosingForecast: '월별 예상 마감 금액',
		progressKindReport: '파이프라인별 구성',
		openProgress: '열린 거래',
		missingActions: '활동 없는 거래',
		noReportData: '선택한 기간에 해당하는 거래가 없습니다.',
		noOrganizations: '조건에 맞는 관계처가 없습니다.',
		noContacts: '조건에 맞는 연락처가 없습니다.',
		noActivities: '조건에 맞는 활동이 없습니다.',
		noValue: '금액 없음',
		daysAgo: '{days}일',
		daysAgoOne: '1일',
		kpiOpenValue: '열린 거래 금액',
		kpiRelationships: '관계처',
		kpiOpenActions: '열린 활동',
		kpiOpenProgress: '열린 거래',
		kpiMoving: '정상 진행',
		kpiStalled: '정체',
		kpiOnHold: '보류',
		kpiRecentlyContacted: '최근 연락',
		kpiStable: '안정',
		kpiNeedsAttention: '확인 필요',
		kpiScheduled: '예정',
		kpiDueSoon: '오늘·임박',
		kpiOverdue: '기한 초과',
		kpiOtherProgressKinds: '기타',
		kpiCountSuffix: '건',
		activityKinds: {
			note: '메모',
			email: '이메일',
			meeting: '미팅',
			call: '통화',
			task: '업무',
			file: '파일',
			event: '일정',
			stage_change: '단계 변경'
		},
		organizationTypes: {
			customer: '고객사',
			partner: '파트너사',
			sponsor: '후원사',
			vendor: '공급사',
			investor: '투자사',
			portfolio: '포트폴리오',
			other: '기타'
		},
		organizationStatuses: {
			prospect: '리드',
			active: '활성',
			paused: '비활성'
		},
		opportunityStages: {
			waiting: '신규',
			in_progress: '진행 중',
			review: '검토 중',
			done: '성사',
			on_hold: '보류',
			lost: '실패'
		},
		taskStatuses: taskText.ko.status,
		actionUrgencies: {
			overdue: '지연',
			today: '오늘',
			due_soon: '임박',
			scheduled: '예정',
			done: '완료'
		},
		lastContactWindows: {
			within_7: '7일 이내',
			within_30: '30일 이내',
			within_90: '90일 이내',
			over_90: '90일 넘음'
		},
		importanceLabels: {
			high: '높음',
			medium: '보통',
			low: '낮음'
		},
		intakeSources: {
			file: '파일',
			mail: '메일',
			calendar: '일정'
		}
	},
	en: {
		pageTitle: 'CRM · InternKim',
		searchPlaceholder: 'Search accounts, contacts, or tags',
		newRelationship: 'Account',
		newContact: 'Contact',
		newOpportunity: 'Deal',
		logActivity: 'Log activity',
		createTitle: 'Add CRM record',
		createDescription: 'Enter the complete details for the selected record type.',
		recordKind: 'Record type',
		name: 'Name or title',
		selectRelationship: 'Select account',
		business: 'Business',
		relatedProgress: 'Related deal',
		noRelatedProgress: 'Not linked to a deal',
		details: 'Details',
		email: 'Email',
		ownerEmail: 'Owner email',
		phone: 'Phone',
		contactTitle: 'Title or role',
		contactName: 'Contact name',
		activityTitle: 'Activity title',
		address: 'Address',
		addressPlaceholder: 'e.g. 222 Wangsimni-ro, Seongdong-gu, Seoul',
		tags: 'Tags',
		tagsPlaceholder: 'Type a tag and press Enter',
		nextContactDate: 'Next contact date',
		activityKind: 'Activity type',
		assignee: 'Assignee',
		columnKind: 'Type',
		columnSize: 'Size',
		columnStartDate: 'Start date',
		columnEndDate: 'End date',
		occurredAt: 'Activity date and time',
		activityStatus: 'Activity status',
		registerCalendar: 'Add to calendar',
		registerCalendarDescription: 'Creates a calendar event linked to this record.',
		allDay: 'All-day event',
		startTime: 'Start time',
		endTime: 'End time',
		endTimeAfterStart: 'End time must be later than start time.',
		location: 'Location',
		amount: 'Amount',
		resetFilters: 'Reset',
		filters: 'Filters',
		sort: 'Sort',
		metricsOverview: 'CRM overview',
		sortAscending: 'Sorted ascending',
		sortDescending: 'Sorted descending',
		currency: 'Currency',
		viewCurrency: 'View currency',
		viewCurrencyFailed: 'Rates were unavailable, so the view currency did not change.',
		cancel: 'Cancel',
		save: 'Save',
		archive: 'Archive',
		archiveConfirm: 'Archive this CRM record?',
		loading: 'Loading CRM data.',
		directoryLoading: 'Loading owners. Records are available; owner selection will be enabled when ready.',
		currencyUnavailable: 'Could not load the currency information needed to display deal amounts. Please retry.',
		retry: 'Retry',
		savedToService: 'Saved to the CRM service.',
		archivedFromService: 'Archived the CRM record.',
		create: 'Add',
		requiredField: 'Enter a name or title.',
		contactMethodRequired: 'Enter an email address or phone number.',
		relationshipContactCreateFailed: 'The account was saved, but the contact was not. Retry saves only the contact without creating another account.',
		contactRelationshipConflict: 'This contact cannot move because these linked deals belong to another account: {names}',
		opportunityCustomerRequired: 'Select an account or linked contact.',
		organizationLoadFailed: 'Could not load the organization directory.',
		refreshAfterSaveFailed: 'Saved, but the list could not be refreshed. Try again.',
		fixtureModeReadOnly: 'Server persistence is unavailable in fixture mode.',
		permissionDenied: 'You do not have permission to view or edit CRM records.',
		processingFailed: 'Could not process the CRM data.',
		invalidRequest: 'Check the CRM information and try again.',
		recordNotFound: 'The CRM record could not be found.',
		conflict: 'This record conflicts with another change. Reload and try again.',
		ownerNotFound: 'The owner could not be found in the organization directory.',
		ownerAmbiguous: 'Multiple owners match. Enter an email address.',
		lostReasonRequired: 'Select a lost reason before moving to a lost stage.',
		definitionInUse: 'This item is used by an existing CRM record. Change the linked record before deleting it.',
		lostReasonPrompt: 'Reason lost',
		noOrganizationContacts: 'The selected account has no contacts.',
		realizedAmountReadonly: 'Amount and currency cannot be changed after a deal is closed.',
		conversionSettled: 'settled',
		conversionEstimate: 'estimated at the {date} rate',
		relationships: 'Accounts',
		contactDirectory: 'Contacts',
		pipeline: 'Deals',
		activities: 'Activities',
		reports: 'Reports',
		definitions: {
			title: 'Definitions',
			organizationTypes: 'Account types',
			pipelines: 'Pipelines',
			add: 'Add',
			remove: 'Remove',
			removeTitle: 'Remove item',
			removeDescription: 'Delete "{name}"?',
			cancel: 'Cancel',
			color: 'Color',
			done: 'Done',
			nameRequired: 'Enter a name.',
			emptyList: 'None yet.',
			saving: 'Saving.'
		},
		paginationSummary: '{from}-{to} of {total}',
		paginationPrevious: 'Previous',
		paginationNext: 'Next',
		edit: 'Edit',
		organizationName: 'Account',
		type: 'Type',
		status: 'Status',
		owner: 'Owner',
		progressOwner: 'Owner',
		internalOwner: 'Owner',
		selectInternalOwner: 'Select owner',
		searchInternalOwner: 'Search by name or email',
		selectExternalContact: 'Select contact',
		searchExternalContact: 'Search by name or email',
		lastContact: 'Last contacted',
		nextAction: 'Next activity',
		opportunity: 'Deal',
		stage: 'Stage',
		targetDate: 'Close date',
		staleDays: 'Time in stage',
		stageElapsedDescription: 'Time elapsed since this deal entered its current stage.',
		expectedValue: 'Amount',
		importance: 'Priority',
		externalContact: 'Contact',
		newExternalContact: 'Add contact',
		addExternalContact: 'Add a contact',
		addExternalContactDescription: 'Creates and links this contact immediately after the account is created.',
		relationshipAlreadyCreated: 'The account is already saved. Check the contact and retry.',
		openOpportunities: 'Open deals',
		contacts: 'Contacts',
		editRelationship: 'Edit account',
		editRelationshipDescription: 'Update account details, ownership, contact dates, and notes.',
		editOpportunity: 'Edit deal',
		editOpportunityDescription: 'Update the linked account, business, pipeline, stage, amount, and details.',
		editContact: 'Edit contact',
		editContactDescription: 'Update the linked account, contact information, and details.',
		editActivity: 'Edit activity',
		editActivityDescription: 'Update the related deal, business, activity, and linked task status.',
		linkedCalendar: 'Linked calendar event',
		none: 'None',
		calendarRegistered: 'Added to calendar',
		calendarCreateError: 'Could not create the linked calendar event.',
		creating: 'Creating',
		overview: 'Overview',
		activity: 'Activity',
		progress: 'Deals',
		allRelationships: 'All',
		myRelationships: 'Mine',
		needsAttention: 'Needs attention',
		tableView: 'List',
		boardView: 'Board',
		noProgress: 'No deals in this stage.',
		progressKind: 'Pipeline',
		progressKinds: {
			sales: 'Sales',
			fundraising: 'Fundraising',
			investment: 'Investment',
			sponsorship: 'Sponsorship',
			partnership: 'Partnership',
			procurement: 'Procurement'
		},
		stageReport: 'Pipeline by stage',
		openDealAmount: 'Open deal amount',
		winRate: 'Win rate',
		daysSinceContact: '{days} days ago',
		elapsedSinceContact: 'Elapsed',
		ownerReport: 'Owner summary',
		quietOrganizations: 'Not contacted recently',
		reportPeriod: 'Report period',
		reportPeriodQuarter: 'Q{quarter} {year}',
		reportPeriodNext90Days: 'Next 90 days',
		reportPeriodAll: 'All time',
		openValue: 'Amount',
		wonValue: 'Won amount',
		won: 'Won',
		monthlyClosingForecast: 'Monthly closing forecast',
		progressKindReport: 'By pipeline',
		openProgress: 'Open deals',
		missingActions: 'Deals without activity',
		noReportData: 'No deals match the selected period.',
		noOrganizations: 'No accounts match.',
		noContacts: 'No contacts match these filters.',
		noActivities: 'No activities match these filters.',
		noValue: 'No amount',
		daysAgo: '{days} days',
		daysAgoOne: '1 day',
		kpiOpenValue: 'Open deal amount',
		kpiRelationships: 'Accounts',
		kpiOpenActions: 'Open activities',
		kpiOpenProgress: 'Open deals',
		kpiMoving: 'Moving',
		kpiStalled: 'Stalled',
		kpiOnHold: 'On hold',
		kpiRecentlyContacted: 'Recently contacted',
		kpiStable: 'Stable',
		kpiNeedsAttention: 'Needs attention',
		kpiScheduled: 'Scheduled',
		kpiDueSoon: 'Today or due soon',
		kpiOverdue: 'Overdue',
		kpiOtherProgressKinds: 'Other',
		kpiCountSuffix: '',
		activityKinds: {
			note: 'Note',
			email: 'Email',
			meeting: 'Meeting',
			call: 'Call',
			task: 'Task',
			file: 'File',
			event: 'Event',
			stage_change: 'Stage change'
		},
		organizationTypes: {
			customer: 'Customer',
			partner: 'Partner',
			sponsor: 'Sponsor',
			vendor: 'Vendor',
			investor: 'Investor',
			portfolio: 'Portfolio',
			other: 'Other'
		},
		organizationStatuses: {
			prospect: 'Lead',
			active: 'Active',
			paused: 'Inactive'
		},
		opportunityStages: {
			waiting: 'New',
			in_progress: 'In progress',
			review: 'In review',
			done: 'Closed won',
			on_hold: 'On hold',
			lost: 'Closed lost'
		},
		taskStatuses: taskText.en.status,
		actionUrgencies: {
			overdue: 'Overdue',
			today: 'Today',
			due_soon: 'Due soon',
			scheduled: 'Scheduled',
			done: 'Done'
		},
		lastContactWindows: {
			within_7: 'Within 7 days',
			within_30: 'Within 30 days',
			within_90: 'Within 90 days',
			over_90: 'Over 90 days'
		},
		importanceLabels: {
			high: 'High',
			medium: 'Medium',
			low: 'Low'
		},
		intakeSources: {
			file: 'File',
			mail: 'Mail',
			calendar: 'Calendar'
		}
	}
} as const;

export type CRMText = PageText<typeof crmText>;
