export const hostSetupText = {
	ko: {
		title: '김인턴 시작하기',
		description: '회사 컴퓨터를 연결하고 함께 사용할 직원을 초대하세요.',
		loading: '회사 정보를 확인하고 있습니다.',
		accountReady: '관리자 계정과 회사가 준비됐습니다.',
		computer: '1. 회사 컴퓨터 연결',
		computerDescription: '김인턴 박스를 전원과 인터넷에 연결하세요. 이 화면을 연 컴퓨터가 박스와 같은 사무실 인터넷에 있어야 박스가 여기에 보입니다.',
		searching: '같은 인터넷에서 켜진 박스를 찾고 있습니다…',
		searchingHint: '박스를 켜고 1분쯤 지나면 여기에 나타납니다. 보이지 않으면 박스와 이 컴퓨터가 같은 공유기에 연결됐는지 확인하세요.',
		foundBox: '김인턴 박스',
		connect: '이 박스 연결',
		connecting: '연결 중…',
		modelKey: 'OpenRouter API 키',
		modelKeyDescription: '김인턴이 AI 모델을 쓸 때 사용료가 청구되는 키입니다. 이 브라우저에서 박스만 열 수 있게 잠근 다음 보냅니다.',
		modelKeyLink: 'OpenRouter에서 키 만들기',
		sendModelKey: '키 보내기',
		sendingModelKey: '보내는 중…',
		modelKeyMissing: 'OpenRouter API 키를 붙여 넣으세요.',
		boxClaimed: '이 박스를 회사에 연결했습니다. 김인턴이 쓸 모델 키를 보내면 설치를 시작합니다.',
		boxConnected: '박스가 회사에 연결됐습니다. 박스가 설치를 마치기까지 몇 분 걸립니다.',
		changeModelKey: '모델 키 바꾸기',
		otherComputer: '다른 컴퓨터에 직접 설치하기',
		otherComputerDescription: 'Debian 13(arm64/amd64) 또는 Homebrew가 설치된 Mac을 사용하세요. 인터넷 연결, 관리자 권한, 계속 켜 둘 환경이 필요합니다.',
		download: '연결 파일 받기',
		downloadAgain: '연결 파일 다시 받기',
		downloading: '연결 파일 만드는 중…',
		fileHint: '파일에는 컴퓨터를 이 회사에 연결하는 키가 들어 있습니다. Debian에서는 설치할 때 한 번 쓰이고 나면 더는 아무것도 연결하지 않습니다.',
		install: '회사 호스트 설치',
		installDescription: '아래 명령은 Debian에서 apt 패키지를, macOS에서 Homebrew 패키지를 설치한 다음 회사 서비스를 등록합니다.',
		installCommand: 'curl -fsSL https://intern.kim/install.sh | sh -s -- host',
		configureCommand: 'sudo internkim install ~/Downloads/internkim-host.json',
		installHint: '설치 중 OpenRouter API 키를 입력합니다. 터미널은 입력한 문자를 표시하지 않습니다. 직원들은 별도 설치 없이 웹 앱을 사용합니다.',
		guide: '설치 안내 보기',
		check: '연결 확인',
		checking: '확인 중…',
		connected: '회사 컴퓨터가 연결됐습니다.',
		offline: '아직 김인턴이 응답하지 않습니다. 박스가 켜져 있는지 확인하고, 설치가 끝날 때까지 몇 분 기다린 뒤 다시 확인하세요.',
		unavailable: '연결 상태를 확인하지 못했습니다. 잠시 뒤 다시 확인하세요.',
		invite: '2. 직원 초대',
		inviteDescription: '초대한 직원에게 로그인 주소와 화면에 표시되는 임시 비밀번호를 전달하세요.',
		tryIt: '3. 김인턴에게 말 걸기',
		tryItDescription: '메신저에서 김인턴과의 대화를 열고 첫 부탁을 남겨보세요.',
		firstMessage: '내일 오전 10시에 회의 준비할 일을 등록해줘.',
		openMessenger: '메신저 열기',
		replaceTitle: '기존 연결 키를 바꿀까요?',
		replaceDescription: '이전에 받은 연결 파일은 더 이상 사용할 수 없습니다. 기존 컴퓨터에도 새 파일로 설정을 다시 적용해야 합니다. 회사 데이터와 직원 계정은 유지됩니다.',
		replace: '새 연결 파일 받기',
		cancel: '취소',
		failed: '연결 파일을 만들지 못했습니다.',
		boxFailed: '박스와 연결하지 못했습니다. 잠시 뒤 다시 시도하세요.'
	},
	en: {
		title: 'Get started with InternKim',
		description: 'Connect the company computer and invite your coworkers.',
		loading: 'Loading your company.',
		accountReady: 'Your administrator account and company are ready.',
		computer: '1. Connect the company computer',
		computerDescription: 'Plug your InternKim box into power and the internet. It appears here when this computer is on the same office internet as the box.',
		searching: 'Looking for a box on this internet connection…',
		searchingHint: 'A box shows up about a minute after it is switched on. If it does not, check that the box and this computer use the same router.',
		foundBox: 'InternKim box',
		connect: 'Connect this box',
		connecting: 'Connecting…',
		modelKey: 'OpenRouter API key',
		modelKeyDescription: 'InternKim is billed for AI models on this key. This browser locks it so only your box can open it, then sends it.',
		modelKeyLink: 'Create a key on OpenRouter',
		sendModelKey: 'Send key',
		sendingModelKey: 'Sending…',
		modelKeyMissing: 'Paste your OpenRouter API key.',
		boxClaimed: 'This box now belongs to your company. Send the model key InternKim will use and it starts installing.',
		boxConnected: 'The box is connected to your company. It takes a few minutes to finish installing.',
		changeModelKey: 'Change the model key',
		otherComputer: 'Install on another computer instead',
		otherComputerDescription: 'Use Debian 13 (arm64 or amd64) or a Mac with Homebrew. The computer needs internet access, administrator access, and must stay awake.',
		download: 'Download connection file',
		downloadAgain: 'Download the file again',
		downloading: 'Preparing connection file…',
		fileHint: 'This file carries a key that connects a computer to your company. On Debian the install spends it, and after that it connects nothing.',
		install: 'Install the company host',
		installDescription: 'These commands install the apt package on Debian or the Homebrew package on macOS, then register the company services.',
		installCommand: 'curl -fsSL https://intern.kim/install.sh | sh -s -- host',
		configureCommand: 'sudo internkim install ~/Downloads/internkim-host.json',
		installHint: 'Enter your OpenRouter API key during installation. The terminal hides it while you type. Coworkers use the web app without installing anything.',
		guide: 'Read the installation guide',
		check: 'Check connection',
		checking: 'Checking…',
		connected: 'The company computer is connected.',
		offline: 'InternKim is not answering yet. Check that the box is on, give it a few minutes to finish installing, then check again.',
		unavailable: 'Could not check the connection. Try again shortly.',
		invite: '2. Invite coworkers',
		inviteDescription: 'Share the sign-in address and the temporary password shown after each invitation.',
		tryIt: '3. Talk to InternKim',
		tryItDescription: 'Open a conversation with InternKim in the messenger and send your first request.',
		firstMessage: 'Create a task to prepare for a meeting tomorrow at 10 AM.',
		openMessenger: 'Open messenger',
		replaceTitle: 'Replace the existing connection key?',
		replaceDescription: 'Previously downloaded connection files will stop working. Apply the new file to any existing company computer. Company data and employee accounts are kept.',
		replace: 'Download a new file',
		cancel: 'Cancel',
		failed: 'Could not create the connection file.',
		boxFailed: 'Could not reach the box setup. Try again shortly.'
	}
};
