export const hostSetupText = {
	ko: {
		title: '김인턴 시작하기',
		description: '회사 컴퓨터를 연결하고 함께 사용할 직원을 초대하세요.',
		loading: '회사 정보를 확인하고 있습니다.',
		accountReady: '관리자 계정과 회사가 준비됐습니다.',
		computer: '1. 회사 컴퓨터 연결',
		computerDescription: 'Debian 13(arm64/amd64) 또는 Homebrew가 설치된 Mac을 사용하세요. 인터넷 연결, 관리자 권한, 계속 켜 둘 환경이 필요합니다.',
		download: '연결 파일 받기',
		downloadAgain: '연결 파일 다시 받기',
		downloading: '연결 파일 만드는 중…',
		fileHint: '파일에는 이 회사의 연결 키가 들어 있습니다. 회사 컴퓨터에만 보관하세요.',
		install: '회사 호스트 설치',
		installDescription: '아래 명령은 Debian에서 apt 패키지를, macOS에서 Homebrew 패키지를 설치한 다음 회사 서비스를 등록합니다.',
		installCommand: 'curl -fsSL https://intern.kim/install.sh | sh -s -- host',
		configureCommand: 'sudo internkim install ~/Downloads/internkim-host.json',
		installHint: '설치 중 OpenRouter API 키를 입력합니다. 터미널은 입력한 문자를 표시하지 않습니다. 직원들은 별도 설치 없이 웹 앱을 사용합니다.',
		guide: '설치 안내 보기',
		check: '연결 확인',
		checking: '확인 중…',
		connected: '회사 컴퓨터가 연결됐습니다.',
		offline: '아직 연결되지 않았습니다. 회사 컴퓨터가 켜져 있고 호스트 설치가 끝났는지 확인하세요.',
		unavailable: '연결 상태를 확인하지 못했습니다. 잠시 뒤 다시 확인하세요.',
		invite: '2. 직원 초대',
		inviteDescription: '초대한 직원에게 로그인 주소와 화면에 표시되는 임시 비밀번호를 전달하세요.',
		tryIt: '3. 김인턴에게 말 걸기',
		tryItDescription: '메신저에서 김인턴과의 대화를 열고 첫 부탁을 남겨보세요.',
		firstMessage: '내일 오전 10시에 회의 준비할 일을 등록해줘.',
		openMessenger: '메신저 열기',
		replaceTitle: '기존 연결 키를 바꿀까요?',
		replaceDescription: '이전에 받은 연결 파일은 더 이상 사용할 수 없습니다. 기존 컴퓨터에도 새 파일로 설정을 다시 적용해야 합니다. 회사 데이터와 직원 계정은 유지됩니다.',
		replace: '새 연결 파일 받기',
		cancel: '취소',
		failed: '연결 파일을 만들지 못했습니다.'
	},
	en: {
		title: 'Get started with InternKim',
		description: 'Connect the company computer and invite your coworkers.',
		loading: 'Loading your company.',
		accountReady: 'Your administrator account and company are ready.',
		computer: '1. Connect the company computer',
		computerDescription: 'Use Debian 13 (arm64 or amd64) or a Mac with Homebrew. The computer needs internet access, administrator access, and must stay awake.',
		download: 'Download connection file',
		downloadAgain: 'Download the file again',
		downloading: 'Preparing connection file…',
		fileHint: 'This file contains your company connection key. Keep it on the company computer.',
		install: 'Install the company host',
		installDescription: 'These commands install the apt package on Debian or the Homebrew package on macOS, then register the company services.',
		installCommand: 'curl -fsSL https://intern.kim/install.sh | sh -s -- host',
		configureCommand: 'sudo internkim install ~/Downloads/internkim-host.json',
		installHint: 'Enter your OpenRouter API key during installation. The terminal hides it while you type. Coworkers use the web app without installing anything.',
		guide: 'Read the installation guide',
		check: 'Check connection',
		checking: 'Checking…',
		connected: 'The company computer is connected.',
		offline: 'The computer is not connected yet. Check that it is powered on and the host installation finished.',
		unavailable: 'Could not check the connection. Try again shortly.',
		invite: '2. Invite coworkers',
		inviteDescription: 'Share the sign-in address and the temporary password shown after each invitation.',
		tryIt: '3. Talk to InternKim',
		tryItDescription: 'Open a conversation with InternKim in the messenger and send your first request.',
		firstMessage: 'Create a task to prepare for a meeting tomorrow at 10 AM.',
		openMessenger: 'Open messenger',
		replaceTitle: 'Replace the existing connection key?',
		replaceDescription: 'Previously downloaded connection files will stop working. Apply the new file to any existing company computer. Company data and employee accounts are kept.',
		replace: 'Download a new file',
		cancel: 'Cancel',
		failed: 'Could not create the connection file.'
	}
};
