export const mailTextKo = {
	title: '메일 · 김인턴',
	pageName: '메일',
	transportLabel: 'IMAP / SMTP',
	settings: '메일 설정',
	compose: '작성',
	checkingMail: '메일을 확인하는 중...',
	checkingMailDescription: '계정 상태와 메일함을 확인하고 있습니다.',
	mailboxes: '메일함',
	loadingMailboxes: '메일함을 불러오는 중...',
	connectedAccount: '연결된 계정',
	noAccountConnected: '메일 로그인 필요',
	connectedAccountDescription: 'IMAP 및 SMTP 설정은 서버에 저장됩니다.',
	noAccountConnectedDescription: '메일을 받고 보내려면 IMAP / SMTP 로그인 정보를 등록하세요.',
	mailboxCountSummary: '전체 {total}개 · 읽지 않음 {unread}개',
	mailboxUnreadCount: '읽지 않음 {count}개',
	refresh: '메일 새로고침',
	search: '메일 검색',
	connectAccount: '메일 로그인',
	unread: '읽지 않음',
	needsAttention: '메일 확인 필요',
	unknownSender: '알 수 없는 발신자',
	noSubject: '(제목 없음)',
	noMessages: '표시할 메시지가 없습니다',
	connectMail: '메일 로그인',
	emptyMailbox: '다른 메일함이나 검색어를 시도하세요.',
	emptyUnconfigured: '설정에서 IMAP / SMTP 로그인 정보를 등록하세요.',
	loadingMessages: '메시지를 불러오는 중...',
	messagePagination: '메일 페이지 이동',
	messagePage: '{page}페이지',
	previousPage: '이전',
	nextPage: '다음',
	allInboxes: '전체 받은편지함',
	selectMessage: '메시지를 선택하세요',
	archive: '보관',
	trash: '삭제',
	markRead: '읽음 표시',
	reply: '답장',
	to: '받는 사람',
	loadingMessage: '메시지를 불러오는 중...',
	messageBody: '메시지 본문',
	ready: '메일 준비 완료',
	notConnected: '메일 로그인이 필요합니다',
	chooseMessage: '목록에서 메시지를 선택하세요.',
	connectDescription: '메일을 받고 보내려면 IMAP / SMTP 로그인 정보를 등록하세요.',
	replyAction: '답장...',
	composeAction: '작성...',
	fields: {
		emailAddress: '이메일 주소',
		emailLocalPart: '메일 아이디',
		emailDomain: '메일 도메인',
		customDomain: '도메인',
		displayName: '표시 이름',
		defaultMailbox: '기본 메일함',
		host: '호스트',
		port: '포트',
		security: '보안',
		username: '사용자 이름',
		loginAccount: '로그인 계정',
		password: '비밀번호',
		appPassword: '앱 비밀번호',
		sentMailbox: '보낸 메일함',
		cc: '참조',
		bcc: '숨은 참조',
		subject: '제목',
		body: '본문'
	},
	providers: {
		gmail: 'gmail.com',
		naver: 'naver.com',
		daum: 'daum.net',
		hanmail: 'hanmail.net',
		custom: '직접 입력'
	},
	fieldDescriptions: {
		emailAddress: '도메인을 선택하면 서버 설정은 자동으로 채워집니다.',
		displayName: '메일을 받는 사람에게 보이는 이름입니다.',
		defaultMailbox: '처음 열어볼 받은편지함입니다. 보통 INBOX를 사용합니다.',
		loginAccount: '메일 서비스에서 안내하는 로그인 계정을 사용합니다.',
		appPassword: '일반 로그인 비밀번호가 아니라 메일 서비스에서 만든 앱 비밀번호입니다.',
		sentMailbox: '발송한 메일 사본을 저장할 메일함입니다. Gmail은 비워두면 중복 저장을 피할 수 있습니다.',
		providerPreset: '필요할 때만 서버 주소와 포트를 직접 바꿉니다.'
	},
	settingsSheet: {
		title: '메일 로그인 정보',
		description: '메일 주소와 앱 비밀번호를 입력하면 서버 설정은 자동으로 채워집니다.',
		displayNamePlaceholder: '이름',
		savedPassword: '저장된 비밀번호',
		appPassword: '앱 비밀번호',
		googleAppPasswordLink: 'Google 앱 비밀번호 만들기',
		googleAccountNote: '먼저 올바른 Google 계정으로 로그인했는지 확인하세요. 다른 계정에서 만든 앱 비밀번호는 연결되지 않습니다.',
		googleSetupNote: '생성된 앱 비밀번호는 이 화면을 닫으면 다시 볼 수 없습니다. 안전한 곳에 저장한 뒤, 앱 비밀번호 칸에 붙여넣으세요.',
		naverSetupLink: '네이버 설정 링크 보기',
		naverSetupSteps: ['IMAP/SMTP 사용 설정하기', '애플리케이션 비밀번호 생성하기'],
		naverAccountNote: '먼저 올바른 네이버 계정으로 로그인했는지 확인하세요. 다른 계정에서 만든 애플리케이션 비밀번호는 연결되지 않습니다.',
		naverSetupNotes: ['IMAP/SMTP 사용을 사용함으로 바꾸고 저장하세요. IMAP 동기화 메일 제한은 한 번에 가져올 최대 메일 수입니다.', '생성된 애플리케이션 비밀번호는 이 화면을 닫으면 다시 볼 수 없습니다. 안전한 곳에 저장한 뒤, 앱 비밀번호 칸에 붙여넣으세요.'],
		daumSetupLink: 'Daum/Hanmail 설정 링크 보기',
		daumSetupSteps: ['IMAP/SMTP 사용 설정하기', 'Daum 앱 비밀번호 생성하기'],
		daumSetupNotes: ['IMAP/SMTP 사용을 사용함으로 바꾸고 저장하세요. 설정 화면의 아이디를 IMAP/SMTP 로그인 계정으로 사용합니다.', '생성된 앱 비밀번호는 앱 비밀번호 칸에 붙여넣으세요. 앱 비밀번호는 다시 확인하기 어려우니 안전한 곳에 저장하세요.'],
		setupImageAlts: {
			googleAppPasswordCreated: 'Google 앱 비밀번호 생성 완료 예시',
			naverIMAPSMTP: '네이버 IMAP/SMTP 설정 예시',
			naverAppPassword: '네이버 애플리케이션 비밀번호 생성 예시',
			daumIMAPSMTP: 'Daum IMAP/SMTP 설정 예시',
			daumAppPassword: 'Daum 앱 비밀번호 생성 예시'
		},
		advancedSettings: '고급 설정',
		autoConfigured: '선택한 도메인에 맞춰 받는 메일과 보내는 메일 서버가 자동으로 설정됩니다.',
		testing: '테스트 중...',
		testConnection: '연결 테스트',
		saving: '저장 중...',
		save: '설정 저장',
		saved: '설정이 저장되었습니다.',
		saveFailed: '저장에 실패했습니다.',
		testFailed: '연결 테스트에 실패했습니다.',
		testSucceeded: 'IMAP 및 SMTP 연결에 성공했습니다.',
		securityNone: '없음'
	},
	composeSheet: {
		title: '작성',
		sending: '보내는 중...',
		send: '보내기'
	},
	defaultMailboxes: {
		inbox: '받은편지함',
		sent: '보낸메일',
		drafts: '임시보관함',
		archive: '보관함',
		trash: '휴지통'
	},
	errors: {
		loadMail: '메일을 불러오지 못했습니다.',
		connectAccount: '메일 로그인 정보를 등록하세요.',
		loadMailboxes: '메일함을 불러오지 못했습니다.',
		loadMessages: '메시지를 불러오지 못했습니다.',
		loadMessage: '메시지를 불러오지 못했습니다.',
		saveAccount: '계정을 저장하지 못했습니다.',
		sendMessage: '메시지를 보내지 못했습니다.',
		moveMessage: '메시지를 이동하지 못했습니다.',
		updateMessage: '메시지를 업데이트하지 못했습니다.',
		serviceUnavailable: '메일 서비스를 일시적으로 사용할 수 없습니다.',
		mailboxNotFound: '메일함을 찾을 수 없습니다.'
	}
} as const;
