export const mailText = {
	ko: {
		title: '메일 · 김인턴',
		pageName: '메일',
		transportLabel: 'IMAP / SMTP',
		settings: '메일 설정',
		compose: '작성',
		mailboxes: '메일함',
		connectedAccount: '연결된 계정',
		noAccountConnected: '메일 로그인 필요',
		connectedAccountDescription: 'IMAP 및 SMTP 설정은 서버에 저장됩니다.',
		noAccountConnectedDescription: '메일을 받고 보내려면 IMAP / SMTP 로그인 정보를 등록하세요.',
		messageCountSuffix: '개 메시지',
		refresh: '메일 새로고침',
		search: '메일 검색',
		connectAccount: '메일 로그인',
		unread: '읽지 않음',
		needsAttention: '메일 확인 필요',
		unknownSender: '알 수 없는 발신자',
		noSubject: '(제목 없음)',
		noMessages: '표시할 메시지가 없습니다',
		connectMail: '메일 로그인',
		emptyMailbox: '다른 메일함이나 검색어를 시도하세요.',
		emptyUnconfigured: '설정에서 IMAP / SMTP 로그인 정보를 등록하세요.',
		loadingMore: '메시지를 더 불러오는 중...',
		scrollForMore: '스크롤해서 더 보기',
		allInboxes: '전체 받은편지함',
		selectMessage: '메시지를 선택하세요',
		archive: '보관',
		trash: '삭제',
		markRead: '읽음 표시',
		reply: '답장',
		to: '받는 사람',
		loadingMessage: '메시지를 불러오는 중...',
		messageBody: '메시지 본문',
		ready: '메일 준비 완료',
		notConnected: '메일 로그인이 필요합니다',
		chooseMessage: '목록에서 메시지를 선택하세요.',
		connectDescription: '메일을 받고 보내려면 IMAP / SMTP 로그인 정보를 등록하세요.',
		replyAction: '답장...',
		composeAction: '작성...',
		fields: {
			emailAddress: '이메일 주소',
			emailLocalPart: '메일 아이디',
			emailDomain: '메일 도메인',
			customDomain: '도메인',
			displayName: '표시 이름',
			defaultMailbox: '기본 메일함',
			host: '호스트',
			port: '포트',
			security: '보안',
			username: '사용자 이름',
			loginAccount: '로그인 계정',
			password: '비밀번호',
			appPassword: '앱 비밀번호',
			sentMailbox: '보낸 메일함',
			cc: '참조',
			bcc: '숨은 참조',
			subject: '제목',
			body: '본문'
		},
		providers: {
			gmail: 'gmail.com',
			naver: 'naver.com',
			custom: '직접 입력'
		},
		fieldDescriptions: {
			emailAddress: '도메인을 선택하면 서버 설정은 자동으로 채워집니다.',
			displayName: '메일을 받는 사람에게 보이는 이름입니다.',
			defaultMailbox: '처음 열어볼 받은편지함입니다. 보통 INBOX를 사용합니다.',
			loginAccount: '보통 전체 이메일 주소를 그대로 사용합니다.',
			appPassword: '일반 로그인 비밀번호가 아니라 메일 서비스에서 만든 앱 비밀번호입니다.',
			sentMailbox: '발송한 메일 사본을 저장할 메일함입니다. Gmail은 비워두면 중복 저장을 피할 수 있습니다.',
			providerPreset: '필요할 때만 서버 주소와 포트를 직접 바꿉니다.'
		},
		settingsSheet: {
			title: '메일 로그인 정보',
			description: '메일 주소와 앱 비밀번호를 입력하면 서버 설정은 자동으로 채워집니다.',
			displayNamePlaceholder: '이름',
			savedPassword: '저장된 비밀번호',
			appPassword: '앱 비밀번호',
			advancedSettings: '고급 설정',
			autoConfigured: '선택한 도메인에 맞춰 받는 메일과 보내는 메일 서버가 자동으로 설정됩니다.',
			testing: '테스트 중...',
			testConnection: '연결 테스트',
			saving: '저장 중...',
			save: '설정 저장',
			saved: '설정이 저장되었습니다.',
			saveFailed: '저장에 실패했습니다.',
			testFailed: '연결 테스트에 실패했습니다.',
			testSucceeded: 'IMAP 및 SMTP 연결에 성공했습니다.',
			securityNone: '없음'
		},
		composeSheet: {
			title: '작성',
			sending: '보내는 중...',
			send: '보내기'
		},
		defaultMailboxes: {
			inbox: '받은편지함',
			sent: '보낸메일',
			drafts: '임시보관함',
			archive: '보관함',
			trash: '휴지통'
		},
		errors: {
			loadMail: '메일을 불러오지 못했습니다.',
			connectAccount: '메일 로그인 정보를 등록하세요.',
			loadMailboxes: '메일함을 불러오지 못했습니다.',
			loadMessages: '메시지를 불러오지 못했습니다.',
			loadMessage: '메시지를 불러오지 못했습니다.',
			saveAccount: '계정을 저장하지 못했습니다.',
			sendMessage: '메시지를 보내지 못했습니다.',
			moveMessage: '메시지를 이샘플지 못했습니다.',
			updateMessage: '메시지를 업데이트하지 못했습니다.',
			serviceUnavailable: '메일 서비스를 일시적으로 사용할 수 없습니다.',
			mailboxNotFound: '메일함을 찾을 수 없습니다.'
		}
	},
	en: {
		title: 'Mail · Intern Kim',
		pageName: 'Mail',
		transportLabel: 'IMAP / SMTP',
		settings: 'Mail settings',
		compose: 'Compose',
		mailboxes: 'Mailboxes',
		connectedAccount: 'Connected account',
		noAccountConnected: 'Mail sign-in required',
		connectedAccountDescription: 'IMAP and SMTP settings are stored server-side.',
		noAccountConnectedDescription: 'Add IMAP / SMTP sign-in settings to receive and send mail.',
		messageCountSuffix: ' messages',
		refresh: 'Refresh mail',
		search: 'Search mail',
		connectAccount: 'Mail sign-in',
		unread: 'Unread',
		needsAttention: 'Mail needs attention',
		unknownSender: 'Unknown sender',
		noSubject: '(No subject)',
		noMessages: 'No messages here',
		connectMail: 'Sign in to mail',
		emptyMailbox: 'Try another mailbox or search.',
		emptyUnconfigured: 'Open settings and add IMAP / SMTP sign-in settings.',
		loadingMore: 'Loading more messages...',
		scrollForMore: 'Scroll for more',
		allInboxes: 'All Inboxes',
		selectMessage: 'Select a message',
		archive: 'Archive',
		trash: 'Trash',
		markRead: 'Mark read',
		reply: 'Reply',
		to: 'To',
		loadingMessage: 'Loading message...',
		messageBody: 'Message body',
		ready: 'Ready for mail',
		notConnected: 'Mail sign-in is required',
		chooseMessage: 'Choose a message from the list.',
		connectDescription: 'Add IMAP / SMTP sign-in settings to receive and send mail.',
		replyAction: 'Reply...',
		composeAction: 'Compose...',
		fields: {
			emailAddress: 'Email address',
			emailLocalPart: 'Email ID',
			emailDomain: 'Mail domain',
			customDomain: 'Domain',
			displayName: 'Display name',
			defaultMailbox: 'Default mailbox',
			host: 'Host',
			port: 'Port',
			security: 'Security',
			username: 'Username',
			loginAccount: 'Login account',
			password: 'Password',
			appPassword: 'App password',
			sentMailbox: 'Sent mailbox',
			cc: 'CC',
			bcc: 'BCC',
			subject: 'Subject',
			body: 'Body'
		},
		providers: {
			gmail: 'gmail.com',
			naver: 'naver.com',
			custom: 'Custom'
		},
		fieldDescriptions: {
			emailAddress: 'Choose a domain to fill server settings automatically.',
			displayName: 'The sender name recipients will see.',
			defaultMailbox: 'The inbox opened first. INBOX is typical.',
			loginAccount: 'Usually the full email address.',
			appPassword: 'Use an app password from your mail service, not your normal login password.',
			sentMailbox: 'The mailbox for saving sent-message copies. Leave blank for Gmail to avoid duplicates.',
			providerPreset: 'Change server addresses and ports only when needed.'
		},
		settingsSheet: {
			title: 'Mail sign-in settings',
			description: 'Enter your email address and app password. Server settings are filled automatically.',
			displayNamePlaceholder: 'Your name',
			savedPassword: 'Saved password',
			appPassword: 'App password',
			advancedSettings: 'Advanced settings',
			autoConfigured: 'Incoming and outgoing mail servers are configured automatically for the selected domain.',
			testing: 'Testing...',
			testConnection: 'Test connection',
			saving: 'Saving...',
			save: 'Save settings',
			saved: 'Settings saved.',
			saveFailed: 'Save failed.',
			testFailed: 'Connection test failed.',
			testSucceeded: 'IMAP and SMTP connection succeeded.',
			securityNone: 'None'
		},
		composeSheet: {
			title: 'Compose',
			sending: 'Sending...',
			send: 'Send'
		},
		defaultMailboxes: {
			inbox: 'Inbox',
			sent: 'Sent',
			drafts: 'Drafts',
			archive: 'Archive',
			trash: 'Trash'
		},
		errors: {
			loadMail: 'Could not load mail.',
			connectAccount: 'Add mail sign-in settings to start.',
			loadMailboxes: 'Could not load mailboxes.',
			loadMessages: 'Could not load messages.',
			loadMessage: 'Could not load message.',
			saveAccount: 'Could not save account.',
			sendMessage: 'Could not send message.',
			moveMessage: 'Could not move message.',
			updateMessage: 'Could not update message.',
			serviceUnavailable: 'Mail service is temporarily unavailable.',
			mailboxNotFound: 'mailbox was not found.'
		}
	}
} as const;
