export const mailText = {
	ko: {
		title: 'Mail · Intern Kim',
		pageName: 'Mail',
		transportLabel: 'IMAP / SMTP',
		settings: '메일 설정',
		compose: '작성',
		mailboxes: '메일함',
		connectedAccount: '연결된 계정',
		noAccountConnected: '연결된 계정 없음',
		connectedAccountDescription: 'IMAP 및 SMTP 설정은 서버에 저장됩니다.',
		noAccountConnectedDescription: '메일을 받고 보내려면 IMAP 및 SMTP 설정을 추가하세요.',
		messageCountSuffix: '개 메시지',
		refresh: '메일 새로고침',
		search: '메일 검색',
		connectAccount: '계정 연결',
		unread: '읽지 않음',
		needsAttention: '메일 확인 필요',
		unknownSender: '알 수 없는 발신자',
		noSubject: '(제목 없음)',
		noMessages: '표시할 메시지가 없습니다',
		connectMail: '메일 연결',
		emptyMailbox: '다른 메일함이나 검색어를 시도하세요.',
		emptyUnconfigured: '설정에서 IMAP / SMTP 정보를 추가하세요.',
		loadingMore: '메시지를 더 불러오는 중...',
		scrollForMore: '스크롤해서 더 보기',
		allInboxes: '전체 받은편지함',
		selectMessage: '메시지를 선택하세요',
		archive: '보관',
		trash: '삭제',
		markRead: '읽음 표시',
		reply: '답장',
		to: '받는 사람',
		loadingMessage: '메시지를 불러오는 중...',
		messageBody: '메시지 본문',
		ready: '메일 준비 완료',
		notConnected: '메일이 연결되지 않았습니다',
		chooseMessage: '목록에서 메시지를 선택하세요.',
		connectDescription: '메일을 받고 보내려면 IMAP 및 SMTP 계정을 연결하세요.',
		replyAction: '답장...',
		composeAction: '작성...',
		fields: {
			emailAddress: '이메일 주소',
			displayName: '표시 이름',
			defaultMailbox: '기본 메일함',
			host: '호스트',
			port: '포트',
			security: '보안',
			username: '사용자 이름',
			password: '비밀번호',
			sentMailbox: '보낸 메일함',
			cc: '참조',
			bcc: '숨은 참조',
			subject: '제목',
			body: '본문'
		},
		settingsSheet: {
			title: '메일 설정',
			description: '메일 수신과 발신에 사용할 이메일 계정 하나를 연결합니다.',
			displayNamePlaceholder: '이름',
			savedPassword: '저장된 비밀번호',
			appPassword: '앱 비밀번호',
			testing: '테스트 중...',
			testConnection: '연결 테스트',
			saving: '저장 중...',
			save: '설정 저장',
			saved: '설정이 저장되었습니다.',
			saveFailed: '저장에 실패했습니다.',
			testFailed: '연결 테스트에 실패했습니다.',
			testSucceeded: 'IMAP 및 SMTP 연결에 성공했습니다.',
			securityNone: '없음'
		},
		composeSheet: {
			title: '작성',
			sending: '보내는 중...',
			send: '보내기'
		},
		defaultMailboxes: {
			inbox: '받은편지함',
			sent: '보낸메일',
			drafts: '임시보관함',
			archive: '보관함',
			trash: '휴지통'
		},
		errors: {
			loadMail: '메일을 불러오지 못했습니다.',
			connectAccount: '메일 계정을 연결하세요.',
			loadMailboxes: '메일함을 불러오지 못했습니다.',
			loadMessages: '메시지를 불러오지 못했습니다.',
			loadMessage: '메시지를 불러오지 못했습니다.',
			saveAccount: '계정을 저장하지 못했습니다.',
			sendMessage: '메시지를 보내지 못했습니다.',
			moveMessage: '메시지를 이동하지 못했습니다.',
			updateMessage: '메시지를 업데이트하지 못했습니다.',
			serviceUnavailable: '메일 서비스를 일시적으로 사용할 수 없습니다.',
			mailboxNotFound: '메일함을 찾을 수 없습니다.'
		}
	},
	en: {
		title: 'Mail · Intern Kim',
		pageName: 'Mail',
		transportLabel: 'IMAP / SMTP',
		settings: 'Mail settings',
		compose: 'Compose',
		mailboxes: 'Mailboxes',
		connectedAccount: 'Connected account',
		noAccountConnected: 'No account connected',
		connectedAccountDescription: 'IMAP and SMTP settings are stored server-side.',
		noAccountConnectedDescription: 'Add IMAP and SMTP settings to receive and send mail.',
		messageCountSuffix: ' messages',
		refresh: 'Refresh mail',
		search: 'Search mail',
		connectAccount: 'Connect account',
		unread: 'Unread',
		needsAttention: 'Mail needs attention',
		unknownSender: 'Unknown sender',
		noSubject: '(No subject)',
		noMessages: 'No messages here',
		connectMail: 'Connect mail',
		emptyMailbox: 'Try another mailbox or search.',
		emptyUnconfigured: 'Open settings and add IMAP / SMTP credentials.',
		loadingMore: 'Loading more messages...',
		scrollForMore: 'Scroll for more',
		allInboxes: 'All Inboxes',
		selectMessage: 'Select a message',
		archive: 'Archive',
		trash: 'Trash',
		markRead: 'Mark read',
		reply: 'Reply',
		to: 'To',
		loadingMessage: 'Loading message...',
		messageBody: 'Message body',
		ready: 'Ready for mail',
		notConnected: 'Mail is not connected',
		chooseMessage: 'Choose a message from the list.',
		connectDescription: 'Connect an IMAP and SMTP account to receive and send mail.',
		replyAction: 'Reply...',
		composeAction: 'Compose...',
		fields: {
			emailAddress: 'Email address',
			displayName: 'Display name',
			defaultMailbox: 'Default mailbox',
			host: 'Host',
			port: 'Port',
			security: 'Security',
			username: 'Username',
			password: 'Password',
			sentMailbox: 'Sent mailbox',
			cc: 'CC',
			bcc: 'BCC',
			subject: 'Subject',
			body: 'Body'
		},
		settingsSheet: {
			title: 'Mail settings',
			description: 'Connect one email account for receiving and sending mail.',
			displayNamePlaceholder: 'Your name',
			savedPassword: 'Saved password',
			appPassword: 'App password',
			testing: 'Testing...',
			testConnection: 'Test connection',
			saving: 'Saving...',
			save: 'Save settings',
			saved: 'Settings saved.',
			saveFailed: 'Save failed.',
			testFailed: 'Connection test failed.',
			testSucceeded: 'IMAP and SMTP connection succeeded.',
			securityNone: 'None'
		},
		composeSheet: {
			title: 'Compose',
			sending: 'Sending...',
			send: 'Send'
		},
		defaultMailboxes: {
			inbox: 'Inbox',
			sent: 'Sent',
			drafts: 'Drafts',
			archive: 'Archive',
			trash: 'Trash'
		},
		errors: {
			loadMail: 'Could not load mail.',
			connectAccount: 'Connect a mail account to start.',
			loadMailboxes: 'Could not load mailboxes.',
			loadMessages: 'Could not load messages.',
			loadMessage: 'Could not load message.',
			saveAccount: 'Could not save account.',
			sendMessage: 'Could not send message.',
			moveMessage: 'Could not move message.',
			updateMessage: 'Could not update message.',
			serviceUnavailable: 'Mail service is temporarily unavailable.',
			mailboxNotFound: 'mailbox was not found.'
		}
	}
} as const;
