export const mailTextEn = {
	title: 'Mail · Intern Kim',
	pageName: 'Mail',
	transportLabel: 'IMAP / SMTP',
	settings: 'Mail settings',
	compose: 'Compose',
	checkingMail: 'Checking mail...',
	checkingMailDescription: 'Checking account status and mailboxes.',
	mailboxes: 'Mailboxes',
	loadingMailboxes: 'Loading mailboxes...',
	connectedAccount: 'Connected account',
	noAccountConnected: 'Mail sign-in required',
	connectedAccountDescription: 'IMAP and SMTP settings are stored server-side.',
	noAccountConnectedDescription: 'Add IMAP / SMTP sign-in settings to receive and send mail.',
	messageCountSuffix: ' messages',
	refresh: 'Refresh mail',
	search: 'Search mail',
	connectAccount: 'Mail sign-in',
	unread: 'Unread',
	needsAttention: 'Mail needs attention',
	unknownSender: 'Unknown sender',
	noSubject: '(No subject)',
	noMessages: 'No messages here',
	connectMail: 'Sign in to mail',
	emptyMailbox: 'Try another mailbox or search.',
	emptyUnconfigured: 'Open settings and add IMAP / SMTP sign-in settings.',
	loadingMessages: 'Loading messages...',
	messagePagination: 'Mail pages',
	messagePage: 'Page {page}',
	previousPage: 'Previous',
	nextPage: 'Next',
	allInboxes: 'All Inboxes',
	selectMessage: 'Select a message',
	archive: 'Archive',
	trash: 'Trash',
	markRead: 'Mark read',
	reply: 'Reply',
	to: 'To',
	loadingMessage: 'Loading message...',
	messageBody: 'Message body',
	ready: 'Ready for mail',
	notConnected: 'Mail sign-in is required',
	chooseMessage: 'Choose a message from the list.',
	connectDescription: 'Add IMAP / SMTP sign-in settings to receive and send mail.',
	replyAction: 'Reply...',
	composeAction: 'Compose...',
	fields: {
		emailAddress: 'Email address',
		emailLocalPart: 'Email ID',
		emailDomain: 'Mail domain',
		customDomain: 'Domain',
		displayName: 'Display name',
		defaultMailbox: 'Default mailbox',
		host: 'Host',
		port: 'Port',
		security: 'Security',
		username: 'Username',
		loginAccount: 'Login account',
		password: 'Password',
		appPassword: 'App password',
		sentMailbox: 'Sent mailbox',
		cc: 'CC',
		bcc: 'BCC',
		subject: 'Subject',
		body: 'Body'
	},
	providers: {
		gmail: 'gmail.com',
		naver: 'naver.com',
		custom: 'Custom'
	},
	fieldDescriptions: {
		emailAddress: 'Choose a domain to fill server settings automatically.',
		displayName: 'The sender name recipients will see.',
		defaultMailbox: 'The inbox opened first. INBOX is typical.',
		loginAccount: 'Usually the full email address.',
		appPassword: 'Use an app password from your mail service, not your normal login password.',
		sentMailbox: 'The mailbox for saving sent-message copies. Leave blank for Gmail to avoid duplicates.',
		providerPreset: 'Change server addresses and ports only when needed.'
	},
	settingsSheet: {
		title: 'Mail sign-in settings',
		description: 'Enter your email address and app password. Server settings are filled automatically.',
		displayNamePlaceholder: 'Your name',
		savedPassword: 'Saved password',
		appPassword: 'App password',
		googleAppPasswordLink: 'Create Google app password',
		advancedSettings: 'Advanced settings',
		autoConfigured: 'Incoming and outgoing mail servers are configured automatically for the selected domain.',
		testing: 'Testing...',
		testConnection: 'Test connection',
		saving: 'Saving...',
		save: 'Save settings',
		saved: 'Settings saved.',
		saveFailed: 'Save failed.',
		testFailed: 'Connection test failed.',
		testSucceeded: 'IMAP and SMTP connection succeeded.',
		securityNone: 'None'
	},
	composeSheet: {
		title: 'Compose',
		sending: 'Sending...',
		send: 'Send'
	},
	defaultMailboxes: {
		inbox: 'Inbox',
		sent: 'Sent',
		drafts: 'Drafts',
		archive: 'Archive',
		trash: 'Trash'
	},
	errors: {
		loadMail: 'Could not load mail.',
		connectAccount: 'Add mail sign-in settings to start.',
		loadMailboxes: 'Could not load mailboxes.',
		loadMessages: 'Could not load messages.',
		loadMessage: 'Could not load message.',
		saveAccount: 'Could not save account.',
		sendMessage: 'Could not send message.',
		moveMessage: 'Could not move message.',
		updateMessage: 'Could not update message.',
		serviceUnavailable: 'Mail service is temporarily unavailable.',
		mailboxNotFound: 'mailbox was not found.'
	}
} as const;
