import { mkdir, mkdtemp, readFile, readdir, rename, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { z } from 'zod';

import { protocolVersion } from '../src/lib/server/public-api/catalog/protocol';
import {
	buildProtocolManifest,
	buildSchemaArtifacts,
	calculateArtifactHash,
	serializeArtifact,
	type SchemaArtifact
} from '../src/lib/server/public-api/catalog/protocol-artifacts';

import {
	messengerIdentityCredentialKindSchema,
	messengerIdentityCredentialKinds
} from '../src/lib/server/public-api/catalog/credential';
import { buildCapabilityToolCatalog } from '../src/lib/server/public-api/catalog/tools';

const generatedDirectory = fileURLToPath(new URL('../../pkg/capabilityprotocol/generated/', import.meta.url));
const catalogFileName = 'capability-tools.json';
const messengerIdentityCredentialKindSchemaName = 'messenger-identity-credential-kind';

const recordVocabularyPath = fileURLToPath(
	new URL(
		'../../supabase/tests/the_record_names_the_messenger_identity_credential_kinds.test.sql',
		import.meta.url
	)
);

export function buildGeneratedDocuments(): Map<string, string> {
	const schemas = [
		...buildSchemaArtifacts(),
		buildEnumSchemaArtifact(messengerIdentityCredentialKindSchemaName, messengerIdentityCredentialKindSchema)
	].sort((left, right) => (left.name < right.name ? -1 : left.name > right.name ? 1 : 0));
	const catalogDocument = serializeArtifact(buildCapabilityToolCatalog(protocolVersion));
	const manifest = buildProtocolManifest(schemas, {
		fileName: catalogFileName,
		hash: calculateArtifactHash(catalogDocument)
	});
	return new Map([
		[catalogFileName, catalogDocument],
		...schemas.map(({ fileName, schema }) => [join('json-schema', fileName), serializeArtifact(schema)] as const),
		['manifest.json', serializeArtifact(manifest)]
	]);
}

function buildEnumSchemaArtifact(name: string, schema: z.ZodType): SchemaArtifact {
	const document = {
		...(z.toJSONSchema(schema) as Record<string, unknown>),
		$id: `https://schemas.blueclaw.dev/${protocolVersion}/${name}.schema.json`
	};
	return {
		fileName: `${name}.schema.json`,
		hash: calculateArtifactHash(serializeArtifact(document)),
		name,
		schema: document
	};
}

function buildRecordVocabularyDocument(): string {
	const declared = messengerIdentityCredentialKinds
		.map((kind) => `('${kind.replaceAll("'", "''")}'::text)`)
		.join(', ');
	return `-- Generated by web/scripts/generate-capability-protocol.ts from
-- web/src/lib/server/public-api/catalog/credential.ts.
begin;
create extension if not exists pgtap with schema extensions;
select plan(1);

select set_eq(
  $$select kind from internal.messenger_identity_credential_kind$$,
  $$values ${declared}$$,
  'the record names the messenger identity credential kinds the catalog declares'
);

select * from finish();
rollback;
`;
}

export async function writeGeneratedProtocol(targetDirectory = generatedDirectory): Promise<void> {
	const documents = buildGeneratedDocuments();
	const parentDirectory = dirname(targetDirectory.replace(/\/$/, ''));
	await mkdir(parentDirectory, { recursive: true });
	const stagingDirectory = await mkdtemp(join(parentDirectory, '.generated-staging-'));
	try {
		await writeDocuments(stagingDirectory, documents);
		await rm(targetDirectory, { force: true, recursive: true });
		await rename(stagingDirectory, targetDirectory.replace(/\/$/, ''));
	} finally {
		await rm(stagingDirectory, { force: true, recursive: true });
	}
}

export async function checkGeneratedProtocol(targetDirectory = generatedDirectory): Promise<void> {
	const documents = buildGeneratedDocuments();
	const expectedPaths = [...documents.keys()].sort();
	const actualPaths = await listRelativeFilePaths(targetDirectory);
	if (JSON.stringify(actualPaths) !== JSON.stringify(expectedPaths)) {
		throw new Error(`generated protocol paths differ: expected ${expectedPaths.join(', ')}, got ${actualPaths.join(', ')}`);
	}
	for (const [relativePath, expectedDocument] of documents) {
		const actualDocument = await readFile(join(targetDirectory, relativePath), 'utf8');
		if (actualDocument !== expectedDocument) {
			throw new Error(`generated protocol artifact is stale: ${relativePath}`);
		}
	}
}

async function writeDocuments(targetDirectory: string, documents: Map<string, string>): Promise<void> {
	await Promise.all(
		[...documents].map(async ([relativePath, document]) => {
			const artifactPath = join(targetDirectory, relativePath);
			await mkdir(dirname(artifactPath), { recursive: true });
			await writeFile(artifactPath, document);
		})
	);
}

async function listRelativeFilePaths(targetDirectory: string, relativeDirectory = ''): Promise<string[]> {
	const entries = await readdir(join(targetDirectory, relativeDirectory), { withFileTypes: true });
	const paths = await Promise.all(
		entries.map(async (entry) => {
			const relativePath = join(relativeDirectory, entry.name);
			if (!entry.isDirectory()) return [relativePath];
			return listRelativeFilePaths(targetDirectory, relativePath);
		})
	);
	return paths.flat().sort();
}

async function writeRecordVocabulary(targetPath = recordVocabularyPath): Promise<void> {
	await writeFile(targetPath, buildRecordVocabularyDocument());
}

async function checkRecordVocabulary(targetPath = recordVocabularyPath): Promise<void> {
	const actualDocument = await readFile(targetPath, 'utf8');
	if (actualDocument !== buildRecordVocabularyDocument()) {
		throw new Error(`generated record vocabulary is stale: ${targetPath}`);
	}
}

if (import.meta.main) {
	if (Bun.argv.includes('--check')) {
		await checkGeneratedProtocol();
		await checkRecordVocabulary();
	} else {
		await writeGeneratedProtocol();
		await writeRecordVocabulary();
	}
}
