export const orgchartDirectoryText = {
	ko: {
		title: '직원',
		orgchartTab: '조직도',
		listTab: '직원 목록',
		search: '검색',
		searchPlaceholder: '이름, 직책, 이메일 검색',
		filter: '필터',
		organization: '조직',
		allOrganizations: '전체 조직',
		manageInAdmin: '인사 정보 수정',
		loading: '조직도를 불러오고 있습니다.',
		empty: '표시할 조직도 구성원이 없습니다.',
		loadError: '조직도를 불러오지 못했습니다.',
		primaryOrganization: '소속 팀',
		noTitle: '직책 미입력',
		unassignedTeam: '팀 미지정',
		position: '직책',
		hireDate: '입사일',
		notProvided: '미입력',
		personDetail: '직원 상세',
		closeDetail: '상세 닫기',
		basicInformation: '기본 정보',
		email: '이메일',
		zoomOut: '축소',
		zoomIn: '확대',
		zoomFit: '화면 맞춤'
	},
	en: {
		title: 'People',
		orgchartTab: 'Org chart',
		listTab: 'People list',
		search: 'Search',
		searchPlaceholder: 'Search name, title, email',
		filter: 'Filter',
		organization: 'Organization',
		allOrganizations: 'All organizations',
		manageInAdmin: 'Edit people info',
		loading: 'Loading the org chart.',
		empty: 'No org chart members to show.',
		loadError: 'Could not load the org chart.',
		primaryOrganization: 'Team',
		noTitle: 'No title',
		unassignedTeam: 'Unassigned',
		position: 'Position',
		hireDate: 'Hire date',
		notProvided: 'Not provided',
		personDetail: 'Person detail',
		closeDetail: 'Close detail',
		basicInformation: 'Basic information',
		email: 'Email',
		zoomOut: 'Zoom out',
		zoomIn: 'Zoom in',
		zoomFit: 'Fit'
	}
} as const;
