export const orgchartDirectoryText = {
	ko: {
		title: '직원',
		search: '검색',
		searchPlaceholder: '이름, 직책, 이메일 검색',
		filter: '필터',
		organization: '조직',
		allOrganizations: '전체 조직',
		editPerson: '수정하기',
		loading: '조직도를 불러오고 있습니다.',
		empty: '표시할 조직도 구성원이 없습니다.',
		loadError: '조직도를 불러오지 못했습니다.',
		teamLead: '팀장',
		memberCountUnit: '명',
		moreMembersPrefix: '+',
		moreMembersSuffix: '명 더 보기',
		primaryOrganization: '소속 팀',
		directSupervisor: '직속 상관',
		noSupervisor: '없음',
		noTitle: '직책 미입력',
		unassignedTeam: '팀 미지정',
		position: '직책',
		hireDate: '입사일',
		notProvided: '미입력',
		personDetail: '직원 상세',
		closeDetail: '상세 닫기',
		basicInformation: '기본 정보',
		email: '이메일'
	},
	en: {
		title: 'People',
		search: 'Search',
		searchPlaceholder: 'Search name, title, email',
		filter: 'Filter',
		organization: 'Organization',
		allOrganizations: 'All organizations',
		editPerson: 'Edit',
		loading: 'Loading the org chart.',
		empty: 'No org chart members to show.',
		loadError: 'Could not load the org chart.',
		teamLead: 'Lead',
		memberCountUnit: ' people',
		moreMembersPrefix: '+',
		moreMembersSuffix: ' more',
		primaryOrganization: 'Team',
		directSupervisor: 'Direct manager',
		noSupervisor: 'None',
		noTitle: 'No title',
		unassignedTeam: 'Unassigned',
		position: 'Position',
		hireDate: 'Hire date',
		notProvided: 'Not provided',
		personDetail: 'Person detail',
		closeDetail: 'Close detail',
		basicInformation: 'Basic information',
		email: 'Email'
	}
} as const;
