export const handoffText = {
	ko: {
		pageTitle: '브라우저 넘겨받기 · 김인턴',
		title: '브라우저를 넘겨받았어요',
		description: '김인턴이 쓰던 브라우저를 직접 조작할 수 있어요. 끝나면 완료를 누르면 김인턴이 이어서 진행해요.',
		connecting: '브라우저에 연결하는 중…',
		waitingForScreen: '화면을 받아오는 중…',
		missingTitle: '이 넘겨받기는 끝났어요',
		missingDescription: '이미 완료됐거나 시간이 지나 닫혔어요. 대화에서 김인턴에게 다시 요청해 주세요.',
		refusedTitle: '요청한 사람만 열 수 있어요',
		refusedDescription: '이 브라우저는 김인턴에게 요청한 사람에게만 넘겨졌어요.',
		unreachableTitle: '회사 서버에 연결하지 못했어요',
		unreachableDescription: '기기가 켜져 있는지 확인한 뒤 다시 시도해 주세요.',
		failedTitle: '기기가 브라우저를 열지 못했어요',
		failedDescription: '잠시 뒤 다시 시도해 보고, 계속되면 아래 이유를 관리자에게 알려 주세요.',
		retry: '다시 연결',
		leave: '돌아가기',
		endedCompletedTitle: '완료했어요',
		endedCompletedDescription: '김인턴이 대화에서 이어서 진행해요.',
		endedAbandonedTitle: '넘겨받기를 그만뒀어요',
		endedAbandonedDescription: '김인턴이 대화에서 어떻게 할지 물어볼 거예요.',
		endedExpiredTitle: '시간이 지나 닫혔어요',
		endedExpiredDescription: '필요하면 대화에서 김인턴에게 다시 요청해 주세요.',
		back: '뒤로',
		reload: '새로고침',
		keyboard: '키보드',
		complete: '완료',
		abandon: '그만두기',
		expiresAt: '{time}까지',
		inputFailed: '입력을 전달하지 못했어요.',
		finishFailed: '넘겨받기를 끝내지 못했어요. 다시 시도해 주세요.'
	},
	en: {
		pageTitle: 'Browser handoff · internkim',
		title: 'The browser is yours',
		description: 'Control the browser the intern was using. Press Done when you finish and the intern picks up from there.',
		connecting: 'Connecting to the browser…',
		waitingForScreen: 'Waiting for the screen…',
		missingTitle: 'This handoff has ended',
		missingDescription: 'It was already finished or closed after its time ran out. Ask the intern again in the conversation.',
		refusedTitle: 'Only the person who asked can open this',
		refusedDescription: 'This browser was handed to the person who asked the intern.',
		unreachableTitle: 'Could not reach the company server',
		unreachableDescription: 'Check that the device is on, then try again.',
		failedTitle: 'The device could not open the browser',
		failedDescription: 'Try again in a moment. If it keeps happening, share the reason below with your admin.',
		retry: 'Reconnect',
		leave: 'Go back',
		endedCompletedTitle: 'Done',
		endedCompletedDescription: 'The intern continues in the conversation.',
		endedAbandonedTitle: 'You stopped the handoff',
		endedAbandonedDescription: 'The intern will ask in the conversation how to proceed.',
		endedExpiredTitle: 'Closed after its time ran out',
		endedExpiredDescription: 'Ask the intern again in the conversation if you still need it.',
		back: 'Back',
		reload: 'Reload',
		keyboard: 'Keyboard',
		complete: 'Done',
		abandon: 'Stop',
		expiresAt: 'until {time}',
		inputFailed: 'Could not send your input.',
		finishFailed: 'Could not end the handoff. Try again.'
	}
};
