export const companySettingsText = {
	ko: {
		title: '설정',
		generalTab: '일반',
		adminTab: '관리자',
		signIn: '로그인',
		persona: {
			userTitle: '김인턴이 나를 대하는 방식',
			userDescription: '김인턴이 나에게 답할 때 읽는 문서입니다. 나만 바꿀 수 있고, 다음 요청부터 반영됩니다.',
			callMeLabel: '나를 부르는 말',
			callMePlaceholder: '샘플 님',
			aboutLabel: '알아두면 좋은 것',
			aboutPlaceholder: '맡은 일, 자주 쓰는 도구, 피하고 싶은 것',
			preferencesLabel: '나와 일하는 방식',
			userLanguageLabel: '답할 언어',
			morningBriefingTitle: '아침 브리핑',
			morningBriefingDescription: '김인턴이 오늘 일정과 지금 하는 일, 앞으로 할 일을 회사 시간대에 맞춰 개인 DM으로 보냅니다.',
			morningBriefingEnabled: '브리핑 받기',
			morningBriefingTime: '받는 시간',
			morningBriefingTimeZone: '회사 시간대 기준',
			soulTitle: '김인턴의 성격',
			soulDescription: '김인턴이 무엇을 지키고, 무엇을 하지 않고, 어떻게 일하는지를 정합니다. 회사 전체에 적용되며 관리자만 바꿉니다.',
			valuesLabel: '지키는 것',
			boundariesLabel: '하지 않는 것',
			workingStyleLabel: '일하는 방식',
			linesPlaceholder: '한 줄에 한 문장',
			toneRegisterLabel: '말투',
			toneRegisters: { formal: '격식체', polite: '공손한 말투', casual: '편한 말투' },
			traitsLabel: '어조',
			toneTraits: {
				calm: '차분한',
				warm: '따뜻한',
				clear: '또렷한',
				concise: '간결한',
				direct: '단도직입적인',
				playful: '유쾌한',
				meticulous: '꼼꼼한',
				energetic: '활기찬'
			},
			languageLabel: '기본 언어',
			matchRequesterLabel: '요청한 사람의 언어로 답하기',
			save: '저장',
			saved: '저장했습니다.',
			userLoadError: '내 설정을 불러오지 못했습니다.',
			loading: '내 설정을 불러오는 중…',
			retryLoad: '다시 불러오기',
			userSaveError: '내 설정을 저장하지 못했습니다.',
			soulLoadError: '성격을 불러오지 못했습니다.',
			soulSaveError: '성격을 저장하지 못했습니다.'
		},
		notifications: '알림',
		notificationsDescription: '이 기기에서 알림을 받습니다. 메시지 알림을 끄면 쓰는 메신저 앱이 알려줍니다.',
		notifyStart: '이 기기에서 알림 받기',
		notifyStop: '이 기기에서 알림 끄기',
		notifyMessage: '메시지',
		notifyTask: '업무',
		notifyApproval: '승인',
		notifyAttendance: '근태',
		notifyLeave: '휴가 신청',
		notifyCalendar: '일정 알림',
		notifyMail: '메일',
		notifyBlocked: '브라우저가 이 사이트의 알림을 막고 있습니다. 주소창 옆 설정에서 허용해 주세요.',
		notifyUnsupported: '이 브라우저는 알림을 지원하지 않습니다.',
		notifyUnconfigured: '이 배포에는 알림 키(VAPID)가 아직 없습니다. 관리자가 등록해야 알림을 받을 수 있습니다.',
		notifyLoadFailed: '알림 설정을 불러오지 못했습니다.',
		notifyFailed: '알림 설정을 저장하지 못했습니다.',
		notifyTest: '테스트 알림 보내기',
		notifyTestTitle: '알림이 켜졌습니다',
		notifyTestBody: '이 기기로 알림이 도착합니다.',
		notifyTestSent: '보냈습니다. 곧 알림이 뜹니다.',
		notifyTestNoDevice: '알림을 켠 기기가 없습니다. 먼저 이 기기에서 알림을 켜 주세요.',
		notifyTestFailed: '테스트 알림을 보내지 못했습니다.',
		signInDescription: '패스키를 등록해 두면 비밀번호 없이 지문이나 얼굴로 들어옵니다.',
		password: '비밀번호',
		passwordDescription: '로그인에 쓰는 비밀번호를 바꿉니다. 메시지와 신원은 그대로 둡니다.',
		currentPassword: '현재 비밀번호',
		newPassword: '새 비밀번호',
		confirmNewPassword: '새 비밀번호 확인',
		changePassword: '비밀번호 바꾸기',
		passwordChanged: '비밀번호를 바꿨습니다.',
		passwordMismatch: '새 비밀번호가 서로 다릅니다.',
		currentPasswordWrong: '현재 비밀번호가 맞지 않습니다.',
		passwordChangeFailed: '비밀번호를 바꾸지 못했습니다.',
		personalAccessTokens: '개인 액세스 토큰',
		personalAccessTokensDescription: '내 신원으로 API를 부르는 토큰입니다. 이 토큰으로 부르면 내가 부른 것과 같습니다.',
		noPersonalAccessTokens: '아직 만든 토큰이 없습니다.',
		personalAccessTokenName: '이 토큰을 무엇이라 부를까요',
		personalAccessTokenNamePlaceholder: '노트북',
		personalAccessTokenNeedsName: '토큰에는 이름이 필요합니다.',
		personalAccessTokenPermission: '이 토큰이 할 수 있는 일',
		personalAccessTokenReads: '읽기',
		personalAccessTokenWrites: '읽기와 쓰기',
		personalAccessTokenDeletes: '읽기, 쓰기, 삭제',
		issuePersonalAccessToken: '토큰 만들기',
		revokePersonalAccessToken: '폐기',
		personalAccessTokenIssued: '토큰을 만들었습니다. 지금만 보입니다.',
		personalAccessTokenShownOnce: '이 토큰은 지금만 보입니다. 옮겨 적어 두세요.',
		personalAccessTokenHowToUse: '이렇게 부릅니다:',
		personalAccessTokenRevoked: '토큰을 폐기했습니다.',
		personalAccessTokenFailed: '토큰을 만들지 못했습니다.',
		personalAccessTokensLoadFailed: '토큰 목록을 불러오지 못했습니다.',
		passkeys: '패스키',
		noPasskeys: '아직 등록한 패스키가 없습니다.',
		unnamedPasskey: '이름 없는 패스키',
		addedOn: '{date}에 등록',
		lastUsedOn: '마지막 사용 {date}',
		neverUsed: '아직 쓴 적 없음',
		addPasskey: '패스키 등록',
		removePasskey: '삭제',
		passkeyAdded: '패스키를 등록했습니다.',
		passkeyRemoved: '패스키를 삭제했습니다.',
		passkeyAlreadyRegistered: '이 기기의 패스키는 이미 등록되어 있습니다.',
		passkeyFailed: '패스키를 등록하지 못했습니다.',
		passkeysUnsupported: '이 브라우저는 패스키를 지원하지 않습니다.',
		passkeysLoadFailed: '패스키 목록을 불러오지 못했습니다.',
		myMessenger: '내 메신저 계정',
		myMessengerManage: '메신저 계정 연결 관리',
		myMessengerDescription: '이 앱이 메신저에서 하는 일은 전부 내 계정으로 합니다. 여기서 연결해 두면 다른 사람의 자격으로 도는 일이 없습니다.',
		messengerLoading: '메신저에 무엇이 필요한지 확인하는 중입니다.',
		messengerUnavailable: '회사 앱이 꺼져 있어 메신저에 물어보지 못했습니다.',
		messengerConnectedAs: '{name}(으)로 연결되어 있습니다.',
		messengerAlreadyConnected: '이미 연결되어 있습니다.',
		messengerConnect: '연결',
		messengerReconnect: '다시 연결',
		messengerConnected: '메신저 계정을 연결했습니다.',
		messengerConnectFailed: '연결하지 못했습니다.',
		company: '회사',
		members: '구성원',
		membersDescription: '이 회사에서 함께 일할 사람을 초대합니다. 초대하면 메신저 신원도 함께 준비됩니다.',
		inviteMember: '구성원 초대',
		removeMember: '내보내기',
		removeMemberTitle: '이 사람을 내보낼까요?',
		removeMemberDescription: '{name} 님은 이 회사의 구성원이 아니게 되고, 버즈 커뮤니티와 모든 채널에서도 나갑니다.',
		purgeMember: '완전 삭제',
		purgeMemberDescription: '켜면 기록에서 행까지 지웁니다. 근태·휴가처럼 이 사람을 가리키는 기록이 있으면 지워지지 않고 퇴사 처리만 됩니다.',
		removeFailed: '내보내지 못했습니다.',
		memberActions: '구성원 작업',
		resetPassword: '비밀번호 리셋',
		resetPasswordTitle: '비밀번호를 리셋할까요?',
		resetPasswordDescription: '{name} 님의 로그인 비밀번호를 새 임시 비밀번호로 바꿉니다. 쓰던 비밀번호는 바로 막힙니다.',
		resetPasswordConfirm: '리셋',
		resetPasswordFailed: '비밀번호를 리셋하지 못했습니다.',
		temporaryPasswordTitle: '임시 비밀번호',
		temporaryPasswordDescription: '이 화면에서만 볼 수 있습니다.',
		temporaryPasswordHandOver: '본인에게 전달하세요. 로그인 후 패스키를 등록하면 비밀번호는 더 필요 없습니다.',
		wipeMessages: 'DM 전부 삭제',
		wipeMessagesTitle: '보낸 메시지를 전부 지울까요?',
		wipeMessagesDescription: '{name} 님이 보낸 메시지를 모든 대화에서 지웁니다. 되돌릴 수 없습니다.',
		wipeMessagesConfirm: '전부 삭제',
		wipeMessagesDone: '{count}건을 지웠습니다.',
		wipeMessagesFailed: '메시지를 지우지 못했습니다.',
		done: '완료',
		membersUnavailable: '구성원을 읽지 못했습니다.',
		name: '이름',
		email: '이메일',
		hireDate: '입사일',
		role: '권한',
		membersEmpty: '구성원이 아직 없습니다.',
		cancel: '취소',
		companyDescription: '이 회사 전체에 적용되는 설정입니다. 관리자만 바꿀 수 있습니다.',
		companyPicture: '회사 사진',
		companyPictureChoose: '사진 바꾸기',
		companyPictureRemove: '사진 지우기',
		companyPictureHintTemplate: '눌러서 바꿉니다. 정사각형으로 잘립니다. PNG, JPG, GIF, WebP, HEIC · {megabytes}MB까지.',
		companyPictureTooBigTemplate: '{megabytes}MB까지 올릴 수 있습니다. 이 파일은 {size}입니다.',
		companyPictureSaved: '회사 사진을 바꿨습니다.',
		companyPictureRemoved: '회사 사진을 지웠습니다.',
		companyPictureFailed: '회사 사진을 바꾸지 못했습니다.',
		companyPictureLoadFailed: '회사 사진을 불러오지 못했습니다.',
		baseCurrency: '기준 통화',
		baseCurrencyDescription: '거래를 성사로 옮길 때 금액이 이 통화로 환산되어 확정됩니다. 다른 통화로 기록한 거래는 그 시점 환율로 한 번만 환산합니다.',
		baseCurrencySettledNote: '이미 확정된 거래는 그대로 둡니다. 확정 금액은 성사 시점의 기록이라 통화를 바꿔도 다시 계산하지 않습니다.',
		baseCurrencyLoadFailed: '기준 통화를 불러오지 못했습니다.',
		agent: '에이전트',
		agentDescription: '에이전트가 이 회사의 컴퓨터에서 무엇을 갖추고 일하는지 봅니다.',
		connections: '연결',
		connectionsDescription: '메일과 캘린더는 회사 서버에 그대로 둡니다. 여기에는 접속 정보만 두고, 비밀번호는 암호화해 보관합니다.',
		buzz: '메신저 (Buzz)',
		buzzDescription: '회사 메신저가 어디에 있는지입니다. 계정은 각자 위에서 연결합니다.',
		host: '주소',
		port: '포트',
		save: '저장',
		forget: '삭제',
		saved: '저장했습니다.',
		saveFailed: '저장하지 못했습니다.',
		loadFailed: '연결 정보를 불러오지 못했습니다.'
	},
	en: {
		title: 'Settings',
		generalTab: 'General',
		adminTab: 'Administrator',
		persona: {
			userTitle: 'How Intern Kim works with me',
			userDescription: 'What Intern Kim reads when it answers you. Only you can change it, and it applies from your next request.',
			callMeLabel: 'What to call me',
			callMePlaceholder: 'Sam',
			aboutLabel: 'Worth knowing about me',
			aboutPlaceholder: 'what you work on, the tools you use, what you would rather avoid',
			preferencesLabel: 'How to work with me',
			userLanguageLabel: 'Answer me in',
			morningBriefingTitle: 'Morning briefing',
			morningBriefingDescription: "Intern Kim sends today's schedule, current work, and planned work in a personal DM using the company's timezone.",
			morningBriefingEnabled: 'Receive the briefing',
			morningBriefingTime: 'Time to receive it',
			morningBriefingTimeZone: 'Company timezone',
			soulTitle: "Intern Kim's soul",
			soulDescription: 'What Intern Kim holds to, never does, and how it works. It applies to the whole company and only an administrator changes it.',
			valuesLabel: 'What it holds to',
			boundariesLabel: 'What it never does',
			workingStyleLabel: 'How it works',
			linesPlaceholder: 'one sentence per line',
			toneRegisterLabel: 'Register',
			toneRegisters: { formal: 'formal', polite: 'polite', casual: 'casual' },
			traitsLabel: 'Traits',
			toneTraits: {
				calm: 'calm',
				warm: 'warm',
				clear: 'clear',
				concise: 'concise',
				direct: 'direct',
				playful: 'playful',
				meticulous: 'meticulous',
				energetic: 'energetic'
			},
			languageLabel: 'Default language',
			matchRequesterLabel: 'Answer in the requester\'s language',
			save: 'Save',
			saved: 'Saved.',
			userLoadError: 'Could not load your settings.',
			loading: 'Loading your settings…',
			retryLoad: 'Try again',
			userSaveError: 'Could not save your settings.',
			soulLoadError: 'Could not load the soul.',
			soulSaveError: 'Could not save the soul.'
		},
		signIn: 'Signing in',
		notifications: 'Notifications',
		notificationsDescription: 'Be told on this device. Turn messages off and your messenger app is the one that tells you.',
		notifyStart: 'Notify me on this device',
		notifyStop: 'Stop notifying this device',
		notifyMessage: 'Messages',
		notifyTask: 'Work',
		notifyApproval: 'Approvals',
		notifyAttendance: 'Clocking in and out',
		notifyLeave: 'Leave requests',
		notifyCalendar: 'Event reminders',
		notifyMail: 'Mail',
		notifyBlocked: 'The browser is blocking notifications for this site. Allow them beside the address bar.',
		notifyUnsupported: 'This browser does not support notifications.',
		notifyUnconfigured: 'This deployment has no notification keys (VAPID) yet. An administrator has to add them first.',
		notifyLoadFailed: 'The notification settings did not load.',
		notifyFailed: 'That did not save.',
		notifyTest: 'Send a test notification',
		notifyTestTitle: 'Notifications are on',
		notifyTestBody: 'They will arrive on this device.',
		notifyTestSent: 'Sent. It should arrive shortly.',
		notifyTestNoDevice: 'No device has notifications turned on. Turn them on here first.',
		notifyTestFailed: 'The test notification did not send.',
		signInDescription: 'Register a passkey and you come back in with a fingerprint or your face, no password.',
		password: 'Password',
		passwordDescription: 'Change the password you sign in with. Your messages and your identity stay as they are.',
		currentPassword: 'Current password',
		newPassword: 'New password',
		confirmNewPassword: 'New password again',
		changePassword: 'Change the password',
		passwordChanged: 'Your password is changed.',
		passwordMismatch: 'The two new passwords do not match.',
		currentPasswordWrong: 'That is not the current password.',
		passwordChangeFailed: 'The password did not change.',
		personalAccessTokens: 'Personal access tokens',
		personalAccessTokensDescription: 'A token that calls the API as you. What it reaches is what you reach.',
		noPersonalAccessTokens: 'You have no tokens yet.',
		personalAccessTokenName: 'What should this token be called',
		personalAccessTokenNamePlaceholder: 'Laptop',
		personalAccessTokenNeedsName: 'A token needs a name.',
		personalAccessTokenPermission: 'What this token may do',
		personalAccessTokenReads: 'Read',
		personalAccessTokenWrites: 'Read and write',
		personalAccessTokenDeletes: 'Read, write and delete',
		issuePersonalAccessToken: 'Make a token',
		revokePersonalAccessToken: 'Revoke',
		personalAccessTokenIssued: 'The token is made. This is the only time it is shown.',
		personalAccessTokenShownOnce: 'This is the only time this token is shown. Copy it somewhere safe.',
		personalAccessTokenHowToUse: 'Call with it like this:',
		personalAccessTokenRevoked: 'The token is revoked.',
		personalAccessTokenFailed: 'The token could not be made.',
		personalAccessTokensLoadFailed: 'The tokens could not be loaded.',
		passkeys: 'Passkeys',
		noPasskeys: 'No passkey registered yet.',
		unnamedPasskey: 'Unnamed passkey',
		addedOn: 'Added {date}',
		lastUsedOn: 'Last used {date}',
		neverUsed: 'Never used',
		addPasskey: 'Register a passkey',
		removePasskey: 'Remove',
		passkeyAdded: 'Passkey registered.',
		passkeyRemoved: 'Passkey removed.',
		passkeyAlreadyRegistered: 'This device already has a passkey here.',
		passkeyFailed: 'That passkey did not register.',
		passkeysUnsupported: 'This browser does not support passkeys.',
		passkeysLoadFailed: 'The passkeys did not load.',
		myMessenger: 'My messenger account',
		myMessengerManage: 'Manage messenger account connection',
		myMessengerDescription: 'Everything this app does in the messenger it does as you. Connect here and nothing runs under somebody else\u2019s name.',
		messengerLoading: 'Asking the messenger what it needs.',
		messengerUnavailable: 'The company app is not running, so nothing could be asked of the messenger.',
		messengerConnectedAs: 'Connected as {name}.',
		messengerAlreadyConnected: 'Already connected.',
		messengerConnect: 'Connect',
		messengerReconnect: 'Connect again',
		messengerConnected: 'Your messenger account is connected.',
		messengerConnectFailed: 'That did not connect.',
		company: 'Company',
		members: 'Members',
		membersDescription: 'Invite the people who work here. An invitation prepares their messenger identity too.',
		inviteMember: 'Invite a member',
		removeMember: 'Remove',
		removeMemberTitle: 'Remove this person?',
		removeMemberDescription: '{name} stops being a member of this company and leaves the Buzz community and every channel.',
		purgeMember: 'Erase completely',
		purgeMemberDescription: 'Erases the row from the record. If attendance, leave or anything else still names them, the row stays and they are only marked as having left.',
		removeFailed: 'The removal did not go through.',
		memberActions: 'Member actions',
		resetPassword: 'Reset password',
		resetPasswordTitle: 'Reset this password?',
		resetPasswordDescription: 'A new temporary password replaces the one {name} signs in with. The old one stops working immediately.',
		resetPasswordConfirm: 'Reset',
		resetPasswordFailed: 'The password was not reset.',
		temporaryPasswordTitle: 'Temporary password',
		temporaryPasswordDescription: 'This screen is the only place it is shown.',
		temporaryPasswordHandOver: 'Hand this over. Once they sign in and set up a passkey, no password is needed.',
		wipeMessages: 'Delete every message',
		wipeMessagesTitle: 'Delete every message they posted?',
		wipeMessagesDescription: 'Every message {name} posted is removed from every conversation. This cannot be undone.',
		wipeMessagesConfirm: 'Delete them',
		wipeMessagesDone: '{count} messages deleted.',
		wipeMessagesFailed: 'The messages were not deleted.',
		done: 'Done',
		membersUnavailable: 'The member list could not be read.',
		name: 'Name',
		email: 'Email',
		hireDate: 'Joined',
		role: 'Role',
		membersEmpty: 'Nobody here yet.',
		cancel: 'Cancel',
		companyDescription: 'Settings that hold for everyone here. Only an administrator can change them.',
		companyPicture: 'Company picture',
		companyPictureChoose: 'Change the picture',
		companyPictureRemove: 'Remove the picture',
		companyPictureHintTemplate: 'Click to change. Cropped to a square. PNG, JPG, GIF, WebP, HEIC · up to {megabytes}MB.',
		companyPictureTooBigTemplate: 'Up to {megabytes}MB; this file is {size}.',
		companyPictureSaved: 'The company picture changed.',
		companyPictureRemoved: 'The company picture is gone.',
		companyPictureFailed: 'The company picture did not change.',
		companyPictureLoadFailed: 'The company picture did not load.',
		baseCurrency: 'Base currency',
		baseCurrencyDescription: 'An amount is converted into this currency when a deal is moved to won. A deal recorded in another currency is converted once, at the rate of that moment.',
		baseCurrencySettledNote: 'Deals already settled are left alone. A settled amount is the record of what closed, so changing this does not recompute it.',
		baseCurrencyLoadFailed: 'The base currency did not load.',
		agent: 'Agent',
		agentDescription: 'What the agent has to work with on this company\u2019s computer.',
		connections: 'Connections',
		connectionsDescription: 'Mail and calendar stay on your own servers. Only how to reach them is kept here, with the password encrypted.',
		buzz: 'Messenger (Buzz)',
		buzzDescription: 'Where your messenger lives. Accounts are connected above, one person at a time.',
		host: 'Host',
		port: 'Port',
		save: 'Save',
		forget: 'Remove',
		saved: 'Saved.',
		saveFailed: 'That did not save.',
		loadFailed: 'The connections did not load.'
	}
};
