export const companySettingsText = {
	ko: {
		title: '설정',
		signIn: '로그인',
		notifications: '알림',
		notificationsDescription: '이 기기에서 알림을 받습니다. 메시지 알림을 끄면 쓰는 메신저 앱이 알려줍니다.',
		notifyStart: '이 기기에서 알림 받기',
		notifyStop: '이 기기에서 알림 끄기',
		notifyMessage: '메시지',
		notifyTask: '업무',
		notifyApproval: '승인',
		notifyAttendance: '근태',
		notifyBlocked: '브라우저가 이 사이트의 알림을 막고 있습니다. 주소창 옆 설정에서 허용해 주세요.',
		notifyUnsupported: '이 브라우저는 알림을 지원하지 않습니다.',
		notifyUnconfigured: '이 회사에는 알림이 아직 설정되지 않았습니다.',
		notifyLoadFailed: '알림 설정을 불러오지 못했습니다.',
		notifyFailed: '알림 설정을 저장하지 못했습니다.',
		signInDescription: '패스키를 등록해 두면 비밀번호 없이 지문이나 얼굴로 들어옵니다.',
		passkeys: '패스키',
		noPasskeys: '아직 등록한 패스키가 없습니다.',
		unnamedPasskey: '이름 없는 패스키',
		addedOn: '{date}에 등록',
		lastUsedOn: '마지막 사용 {date}',
		neverUsed: '아직 쓴 적 없음',
		addPasskey: '패스키 등록',
		removePasskey: '삭제',
		passkeyAdded: '패스키를 등록했습니다.',
		passkeyRemoved: '패스키를 삭제했습니다.',
		passkeyAlreadyRegistered: '이 기기의 패스키는 이미 등록되어 있습니다.',
		passkeyFailed: '패스키를 등록하지 못했습니다.',
		passkeysUnsupported: '이 브라우저는 패스키를 지원하지 않습니다.',
		passkeysLoadFailed: '패스키 목록을 불러오지 못했습니다.',
		connections: '연결',
		connectionsDescription: '메일과 캘린더는 회사 서버에 그대로 둡니다. 여기에는 접속 정보만 두고, 비밀번호는 암호화해 보관합니다.',
		mattermost: '메신저 (Mattermost)',
		mattermostDescription: '앱이 회사 메신저에 접속할 때 쓰는 계정입니다.',
		smtp: '메일 보내기 (SMTP)',
		smtpDescription: '보낸 메일이 나가는 서버입니다.',
		imap: '메일 받기 (IMAP)',
		imapDescription: '받은 메일을 읽어오는 서버입니다.',
		caldav: '캘린더 (CalDAV)',
		caldavDescription: '일정을 주고받는 서버입니다.',
		host: '주소',
		port: '포트',
		username: '아이디',
		password: '비밀번호',
		passwordKept: '저장되어 있습니다',
		save: '저장',
		forget: '삭제',
		saved: '저장했습니다.',
		saveFailed: '저장하지 못했습니다.',
		loadFailed: '연결 정보를 불러오지 못했습니다.'
	},
	en: {
		title: 'Settings',
		signIn: 'Signing in',
		notifications: 'Notifications',
		notificationsDescription: 'Be told on this device. Turn messages off and your messenger app is the one that tells you.',
		notifyStart: 'Notify me on this device',
		notifyStop: 'Stop notifying this device',
		notifyMessage: 'Messages',
		notifyTask: 'Work',
		notifyApproval: 'Approvals',
		notifyAttendance: 'Attendance',
		notifyBlocked: 'The browser is blocking notifications for this site. Allow them beside the address bar.',
		notifyUnsupported: 'This browser does not support notifications.',
		notifyUnconfigured: 'Notifications are not set up for this company yet.',
		notifyLoadFailed: 'The notification settings did not load.',
		notifyFailed: 'That did not save.',
		signInDescription: 'Register a passkey and you come back in with a fingerprint or your face, no password.',
		passkeys: 'Passkeys',
		noPasskeys: 'No passkey registered yet.',
		unnamedPasskey: 'Unnamed passkey',
		addedOn: 'Added {date}',
		lastUsedOn: 'Last used {date}',
		neverUsed: 'Never used',
		addPasskey: 'Register a passkey',
		removePasskey: 'Remove',
		passkeyAdded: 'Passkey registered.',
		passkeyRemoved: 'Passkey removed.',
		passkeyAlreadyRegistered: 'This device already has a passkey here.',
		passkeyFailed: 'That passkey did not register.',
		passkeysUnsupported: 'This browser does not support passkeys.',
		passkeysLoadFailed: 'The passkeys did not load.',
		connections: 'Connections',
		connectionsDescription: 'Mail and calendar stay on your own servers. Only how to reach them is kept here, with the password encrypted.',
		mattermost: 'Messenger (Mattermost)',
		mattermostDescription: 'The account the app uses to reach your messenger.',
		smtp: 'Sending mail (SMTP)',
		smtpDescription: 'The server outgoing mail goes through.',
		imap: 'Receiving mail (IMAP)',
		imapDescription: 'The server incoming mail is read from.',
		caldav: 'Calendar (CalDAV)',
		caldavDescription: 'The server events are exchanged with.',
		host: 'Host',
		port: 'Port',
		username: 'Username',
		password: 'Password',
		passwordKept: 'Already stored',
		save: 'Save',
		forget: 'Remove',
		saved: 'Saved.',
		saveFailed: 'That did not save.',
		loadFailed: 'The connections did not load.'
	}
};
