export const companySettingsText = {
	ko: {
		title: '설정',
		connections: '연결',
		connectionsDescription: '메일과 캘린더는 회사 서버에 그대로 둡니다. 여기에는 접속 정보만 두고, 비밀번호는 암호화해 보관합니다.',
		mattermost: '메신저 (Mattermost)',
		mattermostDescription: '앱이 회사 메신저에 접속할 때 쓰는 계정입니다.',
		smtp: '메일 보내기 (SMTP)',
		smtpDescription: '보낸 메일이 나가는 서버입니다.',
		imap: '메일 받기 (IMAP)',
		imapDescription: '받은 메일을 읽어오는 서버입니다.',
		caldav: '캘린더 (CalDAV)',
		caldavDescription: '일정을 주고받는 서버입니다.',
		host: '주소',
		port: '포트',
		username: '아이디',
		password: '비밀번호',
		passwordKept: '저장되어 있습니다',
		save: '저장',
		forget: '삭제',
		saved: '저장했습니다.',
		saveFailed: '저장하지 못했습니다.',
		loadFailed: '연결 정보를 불러오지 못했습니다.',
		adminOnly: '관리자만 볼 수 있습니다.'
	},
	en: {
		title: 'Settings',
		connections: 'Connections',
		connectionsDescription: 'Mail and calendar stay on your own servers. Only how to reach them is kept here, with the password encrypted.',
		mattermost: 'Messenger (Mattermost)',
		mattermostDescription: 'The account the app uses to reach your messenger.',
		smtp: 'Sending mail (SMTP)',
		smtpDescription: 'The server outgoing mail goes through.',
		imap: 'Receiving mail (IMAP)',
		imapDescription: 'The server incoming mail is read from.',
		caldav: 'Calendar (CalDAV)',
		caldavDescription: 'The server events are exchanged with.',
		host: 'Host',
		port: 'Port',
		username: 'Username',
		password: 'Password',
		passwordKept: 'Already stored',
		save: 'Save',
		forget: 'Remove',
		saved: 'Saved.',
		saveFailed: 'That did not save.',
		loadFailed: 'The connections did not load.',
		adminOnly: 'Only an admin can see this.'
	}
};
