package capabilityprotocol

func CompanionToolDescriptors() []Descriptor {
	return MustCanonicalizeBuiltInDescriptors([]Descriptor{
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "user.confirm",
				CanonicalName:   "user.confirm",
				Namespace:       "user",
				ModelName:       "user.confirm",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Ask the user to approve one pending action.",
				Version:              "1",
				PrivacyClass:         "user_input",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: true,
				WorksOffline:         true,
				InputSchema:          userConfirmInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:user.confirm",
				SideEffect:           SideEffectApproval,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "user.input",
				CanonicalName:   "user.input",
				Namespace:       "user",
				ModelName:       "user.input",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Ask the user for information needed to continue.",
				Version:              "1",
				PrivacyClass:         "user_input",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: true,
				WorksOffline:         true,
				InputSchema:          userInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:user.input",
				SideEffect:           SideEffectApproval,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "file.pick",
				CanonicalName:   "file.pick",
				Namespace:       "file",
				ModelName:       "file.pick",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Ask the user to choose local files and upload them through the companion.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: true,
				WorksOffline:         true,
				InputSchema:          filePickInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:file.pick",
				SideEffect:           SideEffectLocalFile,
				RequiresApproval:     true,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem.mount.create",
				CanonicalName:   "filesystem.mount.create",
				Namespace:       "filesystem",
				ModelName:       "filesystem.mount.create",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Connect a user-selected local directory as a filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: true,
				WorksOffline:         true,
				InputSchema:          mountCreateInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem.mount.create",
				SideEffect:           SideEffectLocalFile,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem.mount.list",
				CanonicalName:   "filesystem.mount.list",
				Namespace:       "filesystem",
				ModelName:       "filesystem.mount.list",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "List connected local filesystem mounts.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          emptyToolInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem.mount.list",
				SideEffect:           SideEffectRead,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem.mount.pause",
				CanonicalName:   "filesystem.mount.pause",
				Namespace:       "filesystem",
				ModelName:       "filesystem.mount.pause",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Pause access to a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountReferenceInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem.mount.pause",
				SideEffect:           SideEffectLocalFile,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem.mount.resume",
				CanonicalName:   "filesystem.mount.resume",
				Namespace:       "filesystem",
				ModelName:       "filesystem.mount.resume",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Resume access to a paused local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountReferenceInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem.mount.resume",
				SideEffect:           SideEffectLocalFile,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem.mount.revoke",
				CanonicalName:   "filesystem.mount.revoke",
				Namespace:       "filesystem",
				ModelName:       "filesystem.mount.revoke",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Permanently revoke a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountReferenceInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem.mount.revoke",
				SideEffect:           SideEffectDestructive,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem.mount.status",
				CanonicalName:   "filesystem.mount.status",
				Namespace:       "filesystem",
				ModelName:       "filesystem.mount.status",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Read the status of one or all connected local filesystem mounts.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountReferenceInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem.mount.status",
				SideEffect:           SideEffectRead,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem.mount.stat",
				CanonicalName:   "filesystem.mount.stat",
				Namespace:       "filesystem",
				ModelName:       "filesystem.mount.stat",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Read metadata for a path inside a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountPathInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem.mount.stat",
				SideEffect:           SideEffectRead,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem.mount.list_directory",
				CanonicalName:   "filesystem.mount.list_directory",
				Namespace:       "filesystem",
				ModelName:       "filesystem.mount.list_directory",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "List a directory inside a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountPathInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem.mount.list_directory",
				SideEffect:           SideEffectRead,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem.mount.read",
				CanonicalName:   "filesystem.mount.read",
				Namespace:       "filesystem",
				ModelName:       "filesystem.mount.read",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Read a file inside a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountPathInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem.mount.read",
				SideEffect:           SideEffectRead,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem.mount.write",
				CanonicalName:   "filesystem.mount.write",
				Namespace:       "filesystem",
				ModelName:       "filesystem.mount.write",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Write a file inside a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountWriteInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem.mount.write",
				SideEffect:           SideEffectLocalFile,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem.mount.mkdir",
				CanonicalName:   "filesystem.mount.mkdir",
				Namespace:       "filesystem",
				ModelName:       "filesystem.mount.mkdir",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Create a directory inside a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountPathInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem.mount.mkdir",
				SideEffect:           SideEffectLocalFile,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem.mount.rename",
				CanonicalName:   "filesystem.mount.rename",
				Namespace:       "filesystem",
				ModelName:       "filesystem.mount.rename",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Rename a path inside a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountRenameInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem.mount.rename",
				SideEffect:           SideEffectLocalFile,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem.mount.delete",
				CanonicalName:   "filesystem.mount.delete",
				Namespace:       "filesystem",
				ModelName:       "filesystem.mount.delete",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Delete a path inside a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountDeleteInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem.mount.delete",
				SideEffect:           SideEffectDestructive,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem.mount.truncate",
				CanonicalName:   "filesystem.mount.truncate",
				Namespace:       "filesystem",
				ModelName:       "filesystem.mount.truncate",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Resize a file inside a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountTruncateInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem.mount.truncate",
				SideEffect:           SideEffectLocalFile,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem.mount.chmod",
				CanonicalName:   "filesystem.mount.chmod",
				Namespace:       "filesystem",
				ModelName:       "filesystem.mount.chmod",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Change permissions on a path inside a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountChangeModeInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem.mount.chmod",
				SideEffect:           SideEffectLocalFile,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem.mount.watch",
				CanonicalName:   "filesystem.mount.watch",
				Namespace:       "filesystem",
				ModelName:       "filesystem.mount.watch",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "List paths changed since a given time in a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountWatchInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem.mount.watch",
				SideEffect:           SideEffectRead,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser.open",
				CanonicalName:   "browser.open",
				Namespace:       "browser",
				ModelName:       "browser.open",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Open a URL in the user's local browser.",
				Version:              "1",
				PrivacyClass:         "user_browser",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: true,
				WorksOffline:         false,
				InputSchema:          browserOpenInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:browser.open",
				SideEffect:           SideEffectConnect,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser.snapshot",
				CanonicalName:   "browser.snapshot",
				Namespace:       "browser",
				ModelName:       "browser.snapshot",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Read the current local browser page structure.",
				Version:              "1",
				PrivacyClass:         "user_browser",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: false,
				WorksOffline:         false,
				InputSchema:          browserSnapshotInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:browser.snapshot",
				SideEffect:           SideEffectRead,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser.screenshot",
				CanonicalName:   "browser.screenshot",
				Namespace:       "browser",
				ModelName:       "browser.screenshot",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Capture the visible local browser page.",
				Version:              "1",
				PrivacyClass:         "user_browser",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: false,
				WorksOffline:         false,
				InputSchema:          browserScreenshotInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:browser.screenshot",
				SideEffect:           SideEffectRead,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser.handoff",
				CanonicalName:   "browser.handoff",
				Namespace:       "browser",
				ModelName:       "browser.handoff",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Hand browser control to the user for an interactive step.",
				Version:              "1",
				PrivacyClass:         "user_browser",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: true,
				WorksOffline:         false,
				InputSchema:          browserHandoffInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:browser.handoff",
				SideEffect:           SideEffectConnect,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser.click",
				CanonicalName:   "browser.click",
				Namespace:       "browser",
				ModelName:       "browser.click",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Click a target in the user's local browser.",
				Version:              "1",
				PrivacyClass:         "user_browser",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: false,
				WorksOffline:         false,
				InputSchema:          browserTargetInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:browser.click",
				SideEffect:           SideEffectExternalWrite,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser.fill",
				CanonicalName:   "browser.fill",
				Namespace:       "browser",
				ModelName:       "browser.fill",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Fill text into a target in the user's local browser.",
				Version:              "1",
				PrivacyClass:         "user_browser",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: false,
				WorksOffline:         false,
				InputSchema:          browserFillInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:browser.fill",
				SideEffect:           SideEffectExternalWrite,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser.select",
				CanonicalName:   "browser.select",
				Namespace:       "browser",
				ModelName:       "browser.select",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Select a value in the user's local browser.",
				Version:              "1",
				PrivacyClass:         "user_browser",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: false,
				WorksOffline:         false,
				InputSchema:          browserSelectInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:browser.select",
				SideEffect:           SideEffectExternalWrite,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser.press",
				CanonicalName:   "browser.press",
				Namespace:       "browser",
				ModelName:       "browser.press",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Press a key in the user's local browser.",
				Version:              "1",
				PrivacyClass:         "user_browser",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: false,
				WorksOffline:         false,
				InputSchema:          browserPressInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:browser.press",
				SideEffect:           SideEffectExternalWrite,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser.wait",
				CanonicalName:   "browser.wait",
				Namespace:       "browser",
				ModelName:       "browser.wait",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Wait for a browser target or a bounded interval.",
				Version:              "1",
				PrivacyClass:         "user_browser",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: false,
				WorksOffline:         false,
				InputSchema:          browserWaitInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:browser.wait",
				SideEffect:           SideEffectRead,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
	})
}

func CompanionLLMDescriptors() []Descriptor {
	return MustCanonicalizeBuiltInDescriptors([]Descriptor{
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "llm.text",
				CanonicalName:   "llm.text",
				Namespace:       "llm",
				ModelName:       "llm.text",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Generate text with the companion's local language model.",
				Version:              "1",
				PrivacyClass:         "model_input",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          TextLLMInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:llm.text",
				SideEffect:           SideEffectComputation,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "llm.structured",
				CanonicalName:   "llm.structured",
				Namespace:       "llm",
				ModelName:       "llm.structured",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Generate schema-constrained output with the companion's local language model.",
				Version:              "1",
				PrivacyClass:         "model_input",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          StructuredLLMInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:llm.structured",
				SideEffect:           SideEffectComputation,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "embedding.create",
				CanonicalName:   "embedding.create",
				Namespace:       "embedding",
				ModelName:       "embedding.create",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Create embeddings with the companion's local embedding model.",
				Version:              "1",
				PrivacyClass:         "model_input",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          EmbeddingInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:embedding.create",
				SideEffect:           SideEffectComputation,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            AttentionTriageToolName,
				CanonicalName:   AttentionTriageToolName,
				Namespace:       "attention",
				ModelName:       AttentionTriageToolName,
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Classify whether a pending companion job needs remote attention.",
				Version:              "1",
				PrivacyClass:         "model_input",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          attentionTriageInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:attention.triage",
				SideEffect:           SideEffectComputation,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
	})
}

func DeviceBrowserDescriptors() []Descriptor {
	return MustCanonicalizeBuiltInDescriptors([]Descriptor{
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser.open",
				CanonicalName:   "browser.open",
				Namespace:       "browser",
				ModelName:       "browser.open",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Open a URL in the device browser.",
				Version:              "1",
				PrivacyClass:         "device_browser",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: false,
				WorksOffline:         false,
				InputSchema:          browserOpenInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:browser.open",
				SideEffect:           SideEffectConnect,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser.snapshot",
				CanonicalName:   "browser.snapshot",
				Namespace:       "browser",
				ModelName:       "browser.snapshot",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Read the current device browser page structure.",
				Version:              "1",
				PrivacyClass:         "device_browser",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: false,
				WorksOffline:         false,
				InputSchema:          browserSnapshotInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:browser.snapshot",
				SideEffect:           SideEffectRead,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser.click",
				CanonicalName:   "browser.click",
				Namespace:       "browser",
				ModelName:       "browser.click",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Click a target in the device browser.",
				Version:              "1",
				PrivacyClass:         "device_browser",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: false,
				WorksOffline:         false,
				InputSchema:          browserTargetInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:browser.click",
				SideEffect:           SideEffectExternalWrite,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser.fill",
				CanonicalName:   "browser.fill",
				Namespace:       "browser",
				ModelName:       "browser.fill",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Fill text into a target in the device browser.",
				Version:              "1",
				PrivacyClass:         "device_browser",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: false,
				WorksOffline:         false,
				InputSchema:          browserFillInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:browser.fill",
				SideEffect:           SideEffectExternalWrite,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser.select",
				CanonicalName:   "browser.select",
				Namespace:       "browser",
				ModelName:       "browser.select",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Select a value in the device browser.",
				Version:              "1",
				PrivacyClass:         "device_browser",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: false,
				WorksOffline:         false,
				InputSchema:          browserSelectInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:browser.select",
				SideEffect:           SideEffectExternalWrite,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser.press",
				CanonicalName:   "browser.press",
				Namespace:       "browser",
				ModelName:       "browser.press",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Press a key in the device browser.",
				Version:              "1",
				PrivacyClass:         "device_browser",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: false,
				WorksOffline:         false,
				InputSchema:          browserPressInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:browser.press",
				SideEffect:           SideEffectExternalWrite,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser.wait",
				CanonicalName:   "browser.wait",
				Namespace:       "browser",
				ModelName:       "browser.wait",
				ModelVisibility: ModelVisibilityVisible,
			},
			Metadata: DescriptorMetadata{
				Description:          "Wait for a browser target or a bounded interval.",
				Version:              "1",
				PrivacyClass:         "device_browser",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: false,
				WorksOffline:         false,
				InputSchema:          browserWaitInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:browser.wait",
				SideEffect:           SideEffectRead,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
	})
}
