package capabilityprotocol

// A grant covers a family of tools, and each tool names the family it belongs to.
const (
	BrowserApprovalScope   = "browser"
	FileApprovalScope      = "file"
	DesktopApprovalScope   = "desktop"
	UserInputApprovalScope = "user_input"
)

func mustGeneratedToolDescriptor(name string) Descriptor {
	return MustGeneratedToolDescriptors(name)[0]
}

// Every browser tool drives one browser session, and that session lives on the
// requester's own machine, so the whole family runs there - not just the steps
// that need the person watching.
func companionBrowserDescriptor(name string, options ...func(*Descriptor)) Descriptor {
	descriptor := mustGeneratedToolDescriptor(name)
	descriptor.RequiresRequesterDevice = true
	descriptor.ApprovalScope = BrowserApprovalScope
	for _, option := range options {
		option(&descriptor)
	}
	return descriptor
}

// Some browser steps cannot run headless at all - they need the person's own
// browser window - and the descriptor is where that is written down.
func withCompanionBrowser(descriptor *Descriptor) {
	descriptor.RequiresCompanionBrowser = true
}

func deviceBrowserDescriptor(name string, description string) Descriptor {
	descriptor := mustGeneratedToolDescriptor(name)
	descriptor.Description = description
	descriptor.PrivacyClass = "device_browser"
	descriptor.RequiresUserPresence = false
	return descriptor
}

func CompanionToolDescriptors() []Descriptor {
	return MustCanonicalizeBuiltInDescriptors([]Descriptor{
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "user_confirm",
				CanonicalName:   "user_confirm",
				Namespace:       "user",
				ModelName:       "user_confirm",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:             "Ask the user to approve one pending action.",
				Version:                 "1",
				PrivacyClass:            "user_input",
				EstimatedLatency:        "interactive",
				RequiresUserPresence:    true,
				RequiresRequesterDevice: true,
				ApprovalScope:           UserInputApprovalScope,
				WorksOffline:            true,
				InputSchema:             userConfirmInputSchema(),
				OutputSchema:            ToolInvokeOutputSchema(),
				PolicyResource:          "tool:user_confirm",
				SideEffect:              SideEffectApproval,
				Availability:            AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:             IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "user_input",
				CanonicalName:   "user_input",
				Namespace:       "user",
				ModelName:       "user_input",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:             "Ask the user for information needed to continue.",
				Version:                 "1",
				PrivacyClass:            "user_input",
				EstimatedLatency:        "interactive",
				RequiresUserPresence:    true,
				RequiresRequesterDevice: true,
				ApprovalScope:           UserInputApprovalScope,
				WorksOffline:            true,
				InputSchema:             userInputSchema(),
				OutputSchema:            ToolInvokeOutputSchema(),
				PolicyResource:          "tool:user_input",
				SideEffect:              SideEffectApproval,
				Availability:            AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:             IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "file_pick",
				CanonicalName:   "file_pick",
				Namespace:       "file",
				ModelName:       "file_pick",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:             "Ask the user to choose local files and upload them through the companion.",
				Version:                 "1",
				PrivacyClass:            "local_file",
				EstimatedLatency:        "interactive",
				RequiresUserPresence:    true,
				RequiresRequesterDevice: true,
				ApprovalScope:           FileApprovalScope,
				WorksOffline:            true,
				InputSchema:             filePickInputSchema(),
				OutputSchema:            ToolInvokeOutputSchema(),
				PolicyResource:          "tool:file_pick",
				SideEffect:              SideEffectLocalFile,
				RequiresApproval:        true,
				Availability:            AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:             IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem_mount_create",
				CanonicalName:   "filesystem_mount_create",
				Namespace:       "filesystem",
				ModelName:       "filesystem_mount_create",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Connect a user-selected local directory as a filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "interactive",
				RequiresUserPresence: true,
				WorksOffline:         true,
				InputSchema:          mountCreateInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem_mount_create",
				SideEffect:           SideEffectLocalFile,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem_mount_list",
				CanonicalName:   "filesystem_mount_list",
				Namespace:       "filesystem",
				ModelName:       "filesystem_mount_list",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "List connected local filesystem mounts.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          emptyToolInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem_mount_list",
				SideEffect:           SideEffectRead,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem_mount_pause",
				CanonicalName:   "filesystem_mount_pause",
				Namespace:       "filesystem",
				ModelName:       "filesystem_mount_pause",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Pause access to a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountReferenceInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem_mount_pause",
				SideEffect:           SideEffectLocalFile,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem_mount_resume",
				CanonicalName:   "filesystem_mount_resume",
				Namespace:       "filesystem",
				ModelName:       "filesystem_mount_resume",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Resume access to a paused local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountReferenceInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem_mount_resume",
				SideEffect:           SideEffectLocalFile,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem_mount_revoke",
				CanonicalName:   "filesystem_mount_revoke",
				Namespace:       "filesystem",
				ModelName:       "filesystem_mount_revoke",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Permanently revoke a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountReferenceInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem_mount_revoke",
				SideEffect:           SideEffectDestructive,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem_mount_status",
				CanonicalName:   "filesystem_mount_status",
				Namespace:       "filesystem",
				ModelName:       "filesystem_mount_status",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Read the status of one or all connected local filesystem mounts.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountReferenceInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem_mount_status",
				SideEffect:           SideEffectRead,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem_mount_stat",
				CanonicalName:   "filesystem_mount_stat",
				Namespace:       "filesystem",
				ModelName:       "filesystem_mount_stat",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Read metadata for a path inside a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountPathInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem_mount_stat",
				SideEffect:           SideEffectRead,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem_mount_list_directory",
				CanonicalName:   "filesystem_mount_list_directory",
				Namespace:       "filesystem",
				ModelName:       "filesystem_mount_list_directory",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "List a directory inside a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountPathInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem_mount_list_directory",
				SideEffect:           SideEffectRead,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem_mount_read",
				CanonicalName:   "filesystem_mount_read",
				Namespace:       "filesystem",
				ModelName:       "filesystem_mount_read",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Read a file inside a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountPathInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem_mount_read",
				SideEffect:           SideEffectRead,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem_mount_write",
				CanonicalName:   "filesystem_mount_write",
				Namespace:       "filesystem",
				ModelName:       "filesystem_mount_write",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Write a file inside a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountWriteInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem_mount_write",
				SideEffect:           SideEffectLocalFile,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem_mount_mkdir",
				CanonicalName:   "filesystem_mount_mkdir",
				Namespace:       "filesystem",
				ModelName:       "filesystem_mount_mkdir",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Create a directory inside a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountPathInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem_mount_mkdir",
				SideEffect:           SideEffectLocalFile,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem_mount_rename",
				CanonicalName:   "filesystem_mount_rename",
				Namespace:       "filesystem",
				ModelName:       "filesystem_mount_rename",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Rename a path inside a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountRenameInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem_mount_rename",
				SideEffect:           SideEffectLocalFile,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem_mount_delete",
				CanonicalName:   "filesystem_mount_delete",
				Namespace:       "filesystem",
				ModelName:       "filesystem_mount_delete",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Delete a path inside a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountDeleteInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem_mount_delete",
				SideEffect:           SideEffectDestructive,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem_mount_truncate",
				CanonicalName:   "filesystem_mount_truncate",
				Namespace:       "filesystem",
				ModelName:       "filesystem_mount_truncate",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Resize a file inside a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountTruncateInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem_mount_truncate",
				SideEffect:           SideEffectLocalFile,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem_mount_chmod",
				CanonicalName:   "filesystem_mount_chmod",
				Namespace:       "filesystem",
				ModelName:       "filesystem_mount_chmod",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Change permissions on a path inside a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountChangeModeInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem_mount_chmod",
				SideEffect:           SideEffectLocalFile,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "filesystem_mount_watch",
				CanonicalName:   "filesystem_mount_watch",
				Namespace:       "filesystem",
				ModelName:       "filesystem_mount_watch",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "List paths changed since a given time in a connected local filesystem mount.",
				Version:              "1",
				PrivacyClass:         "local_file",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          mountWatchInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:filesystem_mount_watch",
				SideEffect:           SideEffectRead,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		companionBrowserDescriptor("browser_open"),
		companionBrowserDescriptor("browser_snapshot"),
		companionBrowserDescriptor("browser_screenshot", withCompanionBrowser),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser_handoff",
				CanonicalName:   "browser_handoff",
				Namespace:       "browser",
				ModelName:       "browser_handoff",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:              "Hand browser control to the user for an interactive step.",
				Version:                  "1",
				PrivacyClass:             "user_browser",
				EstimatedLatency:         "interactive",
				RequiresUserPresence:     true,
				RequiresRequesterDevice:  true,
				ApprovalScope:            BrowserApprovalScope,
				RequiresCompanionBrowser: true,
				WorksOffline:             false,
				InputSchema:              browserHandoffInputSchema(),
				OutputSchema:             ToolInvokeOutputSchema(),
				PolicyResource:           "tool:browser_handoff",
				SideEffect:               SideEffectConnect,
				Availability:             AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:              IdempotencyMetadata{Scope: "operation"},
			},
		}),
		companionBrowserDescriptor("browser_click"),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser_fill",
				CanonicalName:   "browser_fill",
				Namespace:       "browser",
				ModelName:       "browser_fill",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:             "Fill text into a target in the user's local browser.",
				Version:                 "1",
				PrivacyClass:            "user_browser",
				EstimatedLatency:        "interactive",
				RequiresUserPresence:    false,
				RequiresRequesterDevice: true,
				ApprovalScope:           BrowserApprovalScope,
				WorksOffline:            false,
				InputSchema:             browserFillInputSchema(),
				OutputSchema:            ToolInvokeOutputSchema(),
				PolicyResource:          "tool:browser_fill",
				SideEffect:              SideEffectExternalWrite,
				Availability:            AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:             IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser_select",
				CanonicalName:   "browser_select",
				Namespace:       "browser",
				ModelName:       "browser_select",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:             "Select a value in the user's local browser.",
				Version:                 "1",
				PrivacyClass:            "user_browser",
				EstimatedLatency:        "interactive",
				RequiresUserPresence:    false,
				RequiresRequesterDevice: true,
				ApprovalScope:           BrowserApprovalScope,
				WorksOffline:            false,
				InputSchema:             browserSelectInputSchema(),
				OutputSchema:            ToolInvokeOutputSchema(),
				PolicyResource:          "tool:browser_select",
				SideEffect:              SideEffectExternalWrite,
				Availability:            AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:             IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser_press",
				CanonicalName:   "browser_press",
				Namespace:       "browser",
				ModelName:       "browser_press",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:             "Press a key in the user's local browser.",
				Version:                 "1",
				PrivacyClass:            "user_browser",
				EstimatedLatency:        "interactive",
				RequiresUserPresence:    false,
				RequiresRequesterDevice: true,
				ApprovalScope:           BrowserApprovalScope,
				WorksOffline:            false,
				InputSchema:             browserPressInputSchema(),
				OutputSchema:            ToolInvokeOutputSchema(),
				PolicyResource:          "tool:browser_press",
				SideEffect:              SideEffectExternalWrite,
				Availability:            AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:             IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser_wait",
				CanonicalName:   "browser_wait",
				Namespace:       "browser",
				ModelName:       "browser_wait",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:             "Wait for a browser target or a bounded interval.",
				Version:                 "1",
				PrivacyClass:            "user_browser",
				EstimatedLatency:        "interactive",
				RequiresUserPresence:    false,
				RequiresRequesterDevice: true,
				ApprovalScope:           BrowserApprovalScope,
				WorksOffline:            false,
				InputSchema:             browserWaitInputSchema(),
				OutputSchema:            ToolInvokeOutputSchema(),
				PolicyResource:          "tool:browser_wait",
				SideEffect:              SideEffectRead,
				Availability:            AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:             IdempotencyMetadata{Scope: "operation"},
			},
		}),
	})
}

func CompanionLLMDescriptors() []Descriptor {
	return MustCanonicalizeBuiltInDescriptors([]Descriptor{
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "llm_text",
				CanonicalName:   "llm_text",
				Namespace:       "llm",
				ModelName:       "llm_text",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Generate text with the companion's local language model.",
				Version:              "1",
				PrivacyClass:         "model_input",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          TextLLMInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:llm_text",
				SideEffect:           SideEffectComputation,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "llm_structured",
				CanonicalName:   "llm_structured",
				Namespace:       "llm",
				ModelName:       "llm_structured",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Generate schema-constrained output with the companion's local language model.",
				Version:              "1",
				PrivacyClass:         "model_input",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          StructuredLLMInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:llm_structured",
				SideEffect:           SideEffectComputation,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "embedding_create",
				CanonicalName:   "embedding_create",
				Namespace:       "embedding",
				ModelName:       "embedding_create",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Create embeddings with the companion's local embedding model.",
				Version:              "1",
				PrivacyClass:         "model_input",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          EmbeddingInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:embedding_create",
				SideEffect:           SideEffectComputation,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            AttentionTriageToolName,
				CanonicalName:   AttentionTriageToolName,
				Namespace:       "attention",
				ModelName:       AttentionTriageToolName,
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:          "Classify whether a pending companion job needs remote attention.",
				Version:              "1",
				PrivacyClass:         "model_input",
				EstimatedLatency:     "low",
				RequiresUserPresence: false,
				WorksOffline:         true,
				InputSchema:          attentionTriageInputSchema(),
				OutputSchema:         ToolInvokeOutputSchema(),
				PolicyResource:       "tool:attention.triage",
				SideEffect:           SideEffectComputation,
				Availability:         AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:          IdempotencyMetadata{Scope: "operation"},
			},
		}),
	})
}

func DeviceBrowserDescriptors() []Descriptor {
	return MustCanonicalizeBuiltInDescriptors([]Descriptor{
		deviceBrowserDescriptor("browser_open", "Open an exact HTTP or HTTPS URL in the device browser."),
		deviceBrowserDescriptor("browser_snapshot", "Read the current device browser page structure."),
		deviceBrowserDescriptor("browser_click", "Click one exact target from the current device browser snapshot."),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser_fill",
				CanonicalName:   "browser_fill",
				Namespace:       "browser",
				ModelName:       "browser_fill",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:             "Fill text into a target in the device browser.",
				Version:                 "1",
				PrivacyClass:            "device_browser",
				EstimatedLatency:        "interactive",
				RequiresUserPresence:    false,
				RequiresRequesterDevice: true,
				ApprovalScope:           BrowserApprovalScope,
				WorksOffline:            false,
				InputSchema:             browserFillInputSchema(),
				OutputSchema:            ToolInvokeOutputSchema(),
				PolicyResource:          "tool:browser_fill",
				SideEffect:              SideEffectExternalWrite,
				Availability:            AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:             IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser_select",
				CanonicalName:   "browser_select",
				Namespace:       "browser",
				ModelName:       "browser_select",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:             "Select a value in the device browser.",
				Version:                 "1",
				PrivacyClass:            "device_browser",
				EstimatedLatency:        "interactive",
				RequiresUserPresence:    false,
				RequiresRequesterDevice: true,
				ApprovalScope:           BrowserApprovalScope,
				WorksOffline:            false,
				InputSchema:             browserSelectInputSchema(),
				OutputSchema:            ToolInvokeOutputSchema(),
				PolicyResource:          "tool:browser_select",
				SideEffect:              SideEffectExternalWrite,
				Availability:            AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:             IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser_press",
				CanonicalName:   "browser_press",
				Namespace:       "browser",
				ModelName:       "browser_press",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:             "Press a key in the device browser.",
				Version:                 "1",
				PrivacyClass:            "device_browser",
				EstimatedLatency:        "interactive",
				RequiresUserPresence:    false,
				RequiresRequesterDevice: true,
				ApprovalScope:           BrowserApprovalScope,
				WorksOffline:            false,
				InputSchema:             browserPressInputSchema(),
				OutputSchema:            ToolInvokeOutputSchema(),
				PolicyResource:          "tool:browser_press",
				SideEffect:              SideEffectExternalWrite,
				Availability:            AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:             IdempotencyMetadata{Scope: "operation"},
			},
		}),
		NewDescriptor(DescriptorDefinition{
			Identity: DescriptorIdentity{
				Name:            "browser_wait",
				CanonicalName:   "browser_wait",
				Namespace:       "browser",
				ModelName:       "browser_wait",
				ModelVisibility: ModelVisibilityHidden,
			},
			Metadata: DescriptorMetadata{
				Description:             "Wait for a browser target or a bounded interval.",
				Version:                 "1",
				PrivacyClass:            "device_browser",
				EstimatedLatency:        "interactive",
				RequiresUserPresence:    false,
				RequiresRequesterDevice: true,
				ApprovalScope:           BrowserApprovalScope,
				WorksOffline:            false,
				InputSchema:             browserWaitInputSchema(),
				OutputSchema:            ToolInvokeOutputSchema(),
				PolicyResource:          "tool:browser_wait",
				SideEffect:              SideEffectRead,
				Availability:            AvailabilityMetadata{State: AvailabilityOK},
				Idempotency:             IdempotencyMetadata{Scope: "operation"},
			},
		}),
	})
}
