export const memoryText = {
  ko: {
    loading: "기억을 불러오는 중",
    pageTitle: "기억 · 김인턴",
    title: "기억",
    description:
      "김인턴이 기억하는 사실을 확인하고, 더 이상 맞지 않는 기억은 잊게 하세요.",
    relatedViews: "관련 화면",
    clearSearch: "검색 지우기",
    visibleCountTemplate: "{count}개 표시",
    browseDescription: "대화에서 기억한 중요한 사실이 여기에 모입니다.",
    noSearchDescription: "다른 표현으로 검색하거나 검색을 지워 기억 목록을 확인하세요.",
    searchPrompt: "기억 검색",
    searchPlaceholder: "내용이나 단서로 걸러보기",
    searchResults: "검색 결과",
    currentMemories: "현재 기억",
    current: "현재",
    previousMemory: "지난 기억",
    dateUnavailable: "날짜 없음",
    noSearchResults: "검색과 일치하는 기억이 없습니다.",
    selectMemory: "기억을 선택하면 언제 기억했고 언제 떠올렸는지 확인할 수 있습니다.",
    retry: "다시 시도",
    showPrevious: "지난 기억 포함",
    refresh: "새로고침",
    cancel: "취소",
    save: "저장",
    factListTab: "기억 목록",
    scheduleTab: "예약 작업",
    always: "늘 기억함",
    happened: "있었던 일",
    myMemory: "내 기억",
    companyMemory: "회사 공용",
    layersTitle: "기억의 층",
    layersRule: "위층일수록 먼저 떠오릅니다. 아래층이 이미 아는 내용은 위층에 다시 적지 않습니다.",
    allLayers: "전체",
    allLayersReader: "볼 수 있는 모든 층",
    readByYou: "나만 봅니다",
    readByCircleTemplate: "{circle}만 봅니다",
    readByEveryone: "회사 전원이 봅니다",
    recordFloor: "회사 기록",
    recordFloorDescription: "업무·일정·근태처럼 기록에 있는 것은 기억하지 않고, 필요할 때 기록에서 확인합니다.",
    recallTitle: "떠올려 보기",
    recallPlaceholder: "예: 이사회 언제 열려?",
    recallAction: "떠올리기",
    recallDescription: "질문하면 층마다 맞는 기억을 찾아 가까운 층부터 보여 줍니다. 떠올려 봐도 기억은 강해지지 않습니다.",
    recallEmpty: "떠오르는 기억이 없습니다.",
    recallFailed: "떠올리지 못했습니다. 다시 시도해 주세요.",
    layer: "층",
    occurredAt: "일어난 때",
    validUntil: "이때까지 유효",
    importance: "중요도",
    importanceTemplate: "{count}/5",
    createdAt: "기억한 날",
    lastRecalledAt: "마지막으로 떠올린 때",
    neverRecalled: "아직 떠올린 적 없음",
    triggerPhrases: "떠올리는 단서",
    triggerPhrasesDescription: "이 기억이 어떤 상황에서 떠오를지 미리 적어둔 말입니다.",
    triggerPhrasesPending: "아직 단서를 적지 않았습니다.",
    memoryDetails: "저장된 기억",
    forget: "잊기",
    forgetTitle: "기억 잊기",
    forgetDescription:
      "이 기억은 더 이상 업무에 쓰이지 않습니다. 원한다면 이유를 남겨 두세요.",
    forgetReasonLabel: "이유 (선택)",
    forgetReasonPlaceholder: "예: 팀이 바뀜",
    forgetAction: "잊기",
    forgetFailed: "기억을 잊게 하지 못했습니다.",
    loadFailed: "기억을 불러오지 못했습니다. 다시 시도해 주세요.",
    noVisibleMemory: "아직 볼 수 있는 기억이 없습니다.",
    scheduleDescription: "김인턴이 실행할 예정인 예약 작업입니다.",
    scheduleIncludeExpired: "만료된 예약 포함",
    scheduleTitle: "예약 작업",
    schedulePrompt: "요청",
    scheduleStatus: "상태",
    scheduleKind: "유형",
    scheduleNextRun: "다음 실행",
    scheduleExpiresAt: "종료일",
    scheduleTiming: "일정",
    scheduleRunCount: "실행",
    scheduleFailures: "실패",
    scheduleActions: "작업",
    scheduleLoading: "예약 작업을 불러오는 중입니다.",
    scheduleEmpty: "아직 예약 작업이 없습니다.",
    scheduleLoadFailed: "예약 작업을 불러오지 못했습니다.",
    scheduleUpdateFailed: "예약 작업을 저장하지 못했습니다.",
    scheduleDeleteFailed: "예약 작업을 삭제하지 못했습니다.",
    schedulePageSummaryTemplate: "{total}개 중 {from}–{to}",
    schedulePagination: "예약 작업 페이지",
    schedulePreviousPage: "이전",
    scheduleNextPage: "다음",
    scheduleStatusActive: "예약됨",
    scheduleStatusCompleted: "완료됨",
    scheduleStatusExpired: "만료됨",
    scheduleStatusInactive: "중지됨",
    scheduleStatusRetrying: "재시도 예정",
    scheduleKindCron: "정기 반복",
    scheduleKindInterval: "간격 반복",
    scheduleKindOnce: "1회 예약",
    scheduleKindUnknown: "예약",
    scheduleEdit: "수정",
    scheduleDetails: "실행 정보",
    scheduleDelete: "삭제",
    scheduleEditTitle: "예약 작업 수정",
    scheduleEditDescription: "실행 방식과 반복 조건을 변경합니다.",
    scheduleDeleteTitle: "예약 작업 삭제",
    scheduleDeleteDescription: '"{value}" 예약 작업을 완전히 삭제합니다.',
    scheduleDeleteAction: "삭제",
    scheduleNameLabel: "이름",
    scheduleRunAtLabel: "실행 시각",
    scheduleIntervalMinuteLabel: "간격(분)",
    scheduleCronExpressionLabel: "Cron 표현식",
    scheduleTimeZoneLabel: "시간대",
    scheduleMaxRunCountLabel: "최대 실행 횟수",
    scheduleRepeatPolicyLabel: "반복 종료",
    scheduleRepeatUnbounded: "제한 없음",
    scheduleRepeatFinite: "종료 조건 있음",
    scheduleRunCountUnlimitedTemplate: "{count}회",
    scheduleRunCountLimitedTemplate: "{count}/{limit}회",
    scheduleFailureCountTemplate: "{count}회",
    scheduleOnce: "1회 실행",
    scheduleTimingUnavailable: "일정 없음",
    scheduleTimeUnavailable: "다음 실행 없음",
    scheduleNoExpiration: "제한 없음",
    scheduleCronDailyTemplate: "매일 {time}",
    scheduleCronWeekdaysTemplate: "평일 {time}",
    scheduleCronWeeklyTemplate: "매주 {weekday} {time}",
    scheduleWeekdaySunday: "일요일",
    scheduleWeekdayMonday: "월요일",
    scheduleWeekdayTuesday: "화요일",
    scheduleWeekdayWednesday: "수요일",
    scheduleWeekdayThursday: "목요일",
    scheduleWeekdayFriday: "금요일",
    scheduleWeekdaySaturday: "토요일",
    scheduleHourIntervalSingularTemplate: "{count}시간마다",
    scheduleHourIntervalTemplate: "{count}시간마다",
    scheduleMinuteIntervalSingularTemplate: "{count}분마다",
    scheduleMinuteIntervalTemplate: "{count}분마다",
    scheduleSecondIntervalSingularTemplate: "{count}초마다",
    scheduleSecondIntervalTemplate: "{count}초마다",
  },
  en: {
    loading: "Loading memories",
    pageTitle: "Memory · intern kim",
    title: "Memory",
    description:
      "Review the facts intern kim remembers and have it forget the ones that no longer hold.",
    relatedViews: "Related views",
    clearSearch: "Clear search",
    visibleCountTemplate: "{count} shown",
    browseDescription: "Important facts remembered from conversations appear here.",
    noSearchDescription: "Try another word or clear the search to browse memories.",
    searchPrompt: "Search memories",
    searchPlaceholder: "Filter by content or cue",
    searchResults: "Search results",
    currentMemories: "Current memories",
    current: "current",
    previousMemory: "past memory",
    dateUnavailable: "date unavailable",
    noSearchResults: "No memory matches this search.",
    selectMemory: "Select a memory to see when it was remembered and last recalled.",
    retry: "Retry",
    showPrevious: "Include past",
    refresh: "Refresh",
    cancel: "Cancel",
    save: "Save",
    factListTab: "Memory list",
    scheduleTab: "Schedules",
    always: "always",
    happened: "happened",
    myMemory: "My memory",
    companyMemory: "Company-wide",
    layersTitle: "Memory layers",
    layersRule: "Nearer layers come to mind first. What a layer beneath already knows is not written again above it.",
    allLayers: "All",
    allLayersReader: "Every layer you can see",
    readByYou: "Only you",
    readByCircleTemplate: "Only {circle}",
    readByEveryone: "Everyone in the company",
    recordFloor: "Company records",
    recordFloorDescription: "Tasks, schedules and attendance are not remembered; they are looked up in the records when needed.",
    recallTitle: "Try recalling",
    recallPlaceholder: "e.g. When does the board meet?",
    recallAction: "Recall",
    recallDescription: "Ask a question to see which memories each layer brings to mind, nearest first. Trying this does not strengthen them.",
    recallEmpty: "Nothing comes to mind.",
    recallFailed: "Could not recall. Try again.",
    layer: "Layer",
    occurredAt: "When it happened",
    validUntil: "Valid until",
    importance: "Importance",
    importanceTemplate: "{count}/5",
    createdAt: "Remembered on",
    lastRecalledAt: "Last recalled",
    neverRecalled: "never recalled",
    triggerPhrases: "Recalled by",
    triggerPhrasesDescription: "Phrases rehearsed in advance for the situations that should bring this memory back.",
    triggerPhrasesPending: "No phrases rehearsed yet.",
    memoryDetails: "Stored memory",
    forget: "Forget",
    forgetTitle: "Forget this memory",
    forgetDescription:
      "This memory will no longer be used in any task. Leave a reason if you like.",
    forgetReasonLabel: "Reason (optional)",
    forgetReasonPlaceholder: "e.g. moved to another team",
    forgetAction: "Forget",
    forgetFailed: "The memory could not be forgotten.",
    loadFailed: "Memories could not be loaded. Please try again.",
    noVisibleMemory: "No visible memory yet.",
    scheduleDescription: "Scheduled work internkim will run later.",
    scheduleIncludeExpired: "Include expired",
    scheduleTitle: "Schedule",
    schedulePrompt: "Prompt",
    scheduleStatus: "Status",
    scheduleKind: "Type",
    scheduleNextRun: "Next run",
    scheduleExpiresAt: "Ends",
    scheduleTiming: "Schedule",
    scheduleRunCount: "Runs",
    scheduleFailures: "Failures",
    scheduleActions: "Actions",
    scheduleLoading: "Loading schedules.",
    scheduleEmpty: "No schedules yet.",
    scheduleLoadFailed: "Schedules could not be loaded.",
    scheduleUpdateFailed: "Schedule could not be saved.",
    scheduleDeleteFailed: "Schedule could not be deleted.",
    schedulePageSummaryTemplate: "{from}–{to} of {total}",
    schedulePagination: "Schedule pages",
    schedulePreviousPage: "Previous",
    scheduleNextPage: "Next",
    scheduleStatusActive: "scheduled",
    scheduleStatusCompleted: "completed",
    scheduleStatusExpired: "expired",
    scheduleStatusInactive: "stopped",
    scheduleStatusRetrying: "retry scheduled",
    scheduleKindCron: "recurring",
    scheduleKindInterval: "interval",
    scheduleKindOnce: "one-time",
    scheduleKindUnknown: "schedule",
    scheduleEdit: "Edit",
    scheduleDetails: "Run details",
    scheduleDelete: "Delete",
    scheduleEditTitle: "Edit schedule",
    scheduleEditDescription: "Change timing and repeat settings.",
    scheduleDeleteTitle: "Delete schedule",
    scheduleDeleteDescription: 'Permanently delete the "{value}" schedule.',
    scheduleDeleteAction: "Delete",
    scheduleNameLabel: "Name",
    scheduleRunAtLabel: "Run at",
    scheduleIntervalMinuteLabel: "Interval minutes",
    scheduleCronExpressionLabel: "Cron expression",
    scheduleTimeZoneLabel: "Time zone",
    scheduleMaxRunCountLabel: "Maximum runs",
    scheduleRepeatPolicyLabel: "Repeat ending",
    scheduleRepeatUnbounded: "No limit",
    scheduleRepeatFinite: "Has end condition",
    scheduleRunCountUnlimitedTemplate: "{count} runs",
    scheduleRunCountLimitedTemplate: "{count}/{limit} runs",
    scheduleFailureCountTemplate: "{count}",
    scheduleOnce: "one-time run",
    scheduleTimingUnavailable: "schedule unavailable",
    scheduleTimeUnavailable: "next run unavailable",
    scheduleNoExpiration: "no end",
    scheduleCronDailyTemplate: "Every day at {time}",
    scheduleCronWeekdaysTemplate: "Weekdays at {time}",
    scheduleCronWeeklyTemplate: "Every {weekday} at {time}",
    scheduleWeekdaySunday: "Sunday",
    scheduleWeekdayMonday: "Monday",
    scheduleWeekdayTuesday: "Tuesday",
    scheduleWeekdayWednesday: "Wednesday",
    scheduleWeekdayThursday: "Thursday",
    scheduleWeekdayFriday: "Friday",
    scheduleWeekdaySaturday: "Saturday",
    scheduleHourIntervalSingularTemplate: "Every {count} hour",
    scheduleHourIntervalTemplate: "Every {count} hours",
    scheduleMinuteIntervalSingularTemplate: "Every {count} minute",
    scheduleMinuteIntervalTemplate: "Every {count} minutes",
    scheduleSecondIntervalSingularTemplate: "Every {count} second",
    scheduleSecondIntervalTemplate: "Every {count} seconds",
  },
} as const;

export type MemoryText = {
  readonly [Key in keyof typeof memoryText.ko]: string;
};
