import type { PageText } from '$lib/i18n/page-text.svelte';

export const memoryText = {
	ko: {
		pageTitle: '기억 · 김인턴',
		title: '기억',
		description: '김인턴이 기억하고 있는 것을 확인하고 정리합니다.',
		refresh: '새로고침',
		cancel: '취소',
		save: '저장',
		factListTab: '기억 목록',
		scheduleTab: '예약 작업',
		factFilterPlaceholder: '내용이나 서클로 걸러보기',
		factFilterKindAll: '모든 종류',
		factFilterScopeAll: '모든 범위',
		factFilterReset: '필터 초기화',
		factKindIdentity: '신원',
		factKindPreference: '선호',
		factKindFact: '사실',
		factKindTemporary: '기한부',
		factKindEpisode: '사건',
		factScopePersonal: '개인',
		factScopeCircle: '서클',
		factScopeWorkspace: '작업공간',
		factListCountTemplate: '총 {total}개 중 {visible}개 표시',
		factListEmpty: '조건에 맞는 기억이 없습니다.',
		factDeleteDescription: '이 기억을 잊습니다. 김인턴이 다시 떠올리지 않습니다.',
		factForgetReason: '웹에서 사용자가 잊어 달라고 요청함',
		factReinforcedTemplate: '{count}회 확인',
		profileTitle: '프로필',
		validAtUnavailable: '날짜 없음',
		myMemory: '내 기억',
		memoryDelete: '삭제',
		memoryDeleteTitle: '기억 삭제',
		memoryDeleteAction: '삭제',
		memoryDeleteFailed: '기억을 삭제하지 못했습니다.',
		loadFailed: '기억을 불러오지 못했습니다.',
		noVisibleMemory: '아직 볼 수 있는 기억이 없습니다.',
		scheduleDescription: '김인턴이 실행할 예정인 예약 작업입니다.',
		scheduleIncludeExpired: '만료된 예약 포함',
		scheduleTitle: '예약 작업',
		schedulePrompt: 'requested',
		scheduleStatus: '상태',
		scheduleKind: '유형',
		scheduleNextRun: '다음 실행',
		scheduleExpiresAt: '종료일',
		scheduleTiming: '일정',
		scheduleRunCount: '실행',
		scheduleFailures: '실패',
		scheduleActions: '작업',
		scheduleLoading: '예약 작업을 불러오는 중입니다.',
		scheduleEmpty: '아직 예약 작업이 없습니다.',
		scheduleLoadFailed: '예약 작업을 불러오지 못했습니다.',
		scheduleUpdateFailed: '예약 작업을 저장하지 못했습니다.',
		scheduleDeleteFailed: '예약 작업을 삭제하지 못했습니다.',
		schedulePageSummaryTemplate: '{total}개 중 {from}–{to}',
		schedulePagination: '예약 작업 페이지',
		schedulePreviousPage: '이전',
		scheduleNextPage: '다음',
		scheduleStatusActive: '예약됨',
		scheduleStatusCompleted: '완료됨',
		scheduleStatusExpired: '만료됨',
		scheduleStatusInactive: '중지됨',
		scheduleStatusRetrying: '재시도 예정',
		scheduleKindCron: '정기 반복',
		scheduleKindInterval: '간격 반복',
		scheduleKindOnce: '1회 예약',
		scheduleKindUnknown: '예약',
		scheduleEdit: '수정',
		scheduleDelete: '삭제',
		scheduleEditTitle: '예약 작업 수정',
		scheduleEditDescription: '실행 방식과 반복 조건을 변경합니다.',
		scheduleDeleteTitle: '예약 작업 삭제',
		scheduleDeleteDescription: '"{value}" 예약 작업을 완전히 삭제합니다.',
		scheduleDeleteAction: '삭제',
		scheduleNameLabel: '이름',
		scheduleRunAtLabel: '실행 시각',
		scheduleIntervalMinuteLabel: '간격(분)',
		scheduleCronExpressionLabel: 'Cron 표현식',
		scheduleTimeZoneLabel: '시간대',
		scheduleMaxRunCountLabel: '최대 실행 횟수',
		scheduleRepeatPolicyLabel: '반복 종료',
		scheduleRepeatUnbounded: '제한 없음',
		scheduleRepeatFinite: '종료 조건 있음',
		scheduleRunCountUnlimitedTemplate: '{count}회',
		scheduleRunCountLimitedTemplate: '{count}/{limit}회',
		scheduleFailureCountTemplate: '{count}회',
		scheduleOnce: '1회 실행',
		scheduleTimingUnavailable: '일정 없음',
		scheduleTimeUnavailable: '다음 실행 없음',
		scheduleNoExpiration: '제한 없음',
		scheduleCronDailyTemplate: '매일 {time}',
		scheduleCronWeekdaysTemplate: '평일 {time}',
		scheduleCronWeeklyTemplate: '매주 {weekday} {time}',
		scheduleWeekdaySunday: '일요일',
		scheduleWeekdayMonday: '월요일',
		scheduleWeekdayTuesday: '화요일',
		scheduleWeekdayWednesday: '수요일',
		scheduleWeekdayThursday: '목요일',
		scheduleWeekdayFriday: '금요일',
		scheduleWeekdaySaturday: '토요일',
		scheduleHourIntervalSingularTemplate: '{count}시간마다',
		scheduleHourIntervalTemplate: '{count}시간마다',
		scheduleMinuteIntervalSingularTemplate: '{count}분마다',
		scheduleMinuteIntervalTemplate: '{count}분마다',
		scheduleSecondIntervalSingularTemplate: '{count}초마다',
		scheduleSecondIntervalTemplate: '{count}초마다'
	},
	en: {
		pageTitle: 'Memory · intern kim',
		title: 'Memory',
		description: 'What intern kim remembers, and the means to tidy it.',
		refresh: 'Refresh',
		cancel: 'Cancel',
		save: 'Save',
		factListTab: 'Memory list',
		scheduleTab: 'Schedules',
		factFilterPlaceholder: 'Filter by content or circle',
		factFilterKindAll: 'All kinds',
		factFilterScopeAll: 'All scopes',
		factFilterReset: 'Reset filters',
		factKindIdentity: 'identity',
		factKindPreference: 'preference',
		factKindFact: 'fact',
		factKindTemporary: 'temporary',
		factKindEpisode: 'episode',
		factScopePersonal: 'personal',
		factScopeCircle: 'circle',
		factScopeWorkspace: 'workspace',
		factListCountTemplate: 'Showing {visible} of {total}',
		factListEmpty: 'No memory matches the filters.',
		factDeleteDescription: 'Forgets this memory. intern kim will not recall it again.',
		factForgetReason: 'the person asked to forget it in the web app',
		factReinforcedTemplate: 'confirmed {count} times',
		profileTitle: 'Profile',
		validAtUnavailable: 'no date',
		myMemory: 'My memory',
		memoryDelete: 'Delete',
		memoryDeleteTitle: 'Delete memory',
		memoryDeleteAction: 'Delete',
		memoryDeleteFailed: 'Memory could not be deleted.',
		loadFailed: 'Memory could not be loaded.',
		noVisibleMemory: 'No visible memory yet.',
		scheduleDescription: 'Scheduled work internkim will run later.',
		scheduleIncludeExpired: 'Include expired',
		scheduleTitle: 'Schedule',
		schedulePrompt: 'Prompt',
		scheduleStatus: 'Status',
		scheduleKind: 'Type',
		scheduleNextRun: 'Next run',
		scheduleExpiresAt: 'Ends',
		scheduleTiming: 'Schedule',
		scheduleRunCount: 'Runs',
		scheduleFailures: 'Failures',
		scheduleActions: 'Actions',
		scheduleLoading: 'Loading schedules.',
		scheduleEmpty: 'No schedules yet.',
		scheduleLoadFailed: 'Schedules could not be loaded.',
		scheduleUpdateFailed: 'Schedule could not be saved.',
		scheduleDeleteFailed: 'Schedule could not be deleted.',
		schedulePageSummaryTemplate: '{from}–{to} of {total}',
		schedulePagination: 'Schedule pages',
		schedulePreviousPage: 'Previous',
		scheduleNextPage: 'Next',
		scheduleStatusActive: 'scheduled',
		scheduleStatusCompleted: 'completed',
		scheduleStatusExpired: 'expired',
		scheduleStatusInactive: 'stopped',
		scheduleStatusRetrying: 'retry scheduled',
		scheduleKindCron: 'recurring',
		scheduleKindInterval: 'interval',
		scheduleKindOnce: 'one-time',
		scheduleKindUnknown: 'schedule',
		scheduleEdit: 'Edit',
		scheduleDelete: 'Delete',
		scheduleEditTitle: 'Edit schedule',
		scheduleEditDescription: 'Change timing and repeat settings.',
		scheduleDeleteTitle: 'Delete schedule',
		scheduleDeleteDescription: 'Permanently delete the "{value}" schedule.',
		scheduleDeleteAction: 'Delete',
		scheduleNameLabel: 'Name',
		scheduleRunAtLabel: 'Run at',
		scheduleIntervalMinuteLabel: 'Interval minutes',
		scheduleCronExpressionLabel: 'Cron expression',
		scheduleTimeZoneLabel: 'Time zone',
		scheduleMaxRunCountLabel: 'Maximum runs',
		scheduleRepeatPolicyLabel: 'Repeat ending',
		scheduleRepeatUnbounded: 'No limit',
		scheduleRepeatFinite: 'Has end condition',
		scheduleRunCountUnlimitedTemplate: '{count} runs',
		scheduleRunCountLimitedTemplate: '{count}/{limit} runs',
		scheduleFailureCountTemplate: '{count}',
		scheduleOnce: 'one-time run',
		scheduleTimingUnavailable: 'schedule unavailable',
		scheduleTimeUnavailable: 'next run unavailable',
		scheduleNoExpiration: 'no end',
		scheduleCronDailyTemplate: 'Every day at {time}',
		scheduleCronWeekdaysTemplate: 'Weekdays at {time}',
		scheduleCronWeeklyTemplate: 'Every {weekday} at {time}',
		scheduleWeekdaySunday: 'Sunday',
		scheduleWeekdayMonday: 'Monday',
		scheduleWeekdayTuesday: 'Tuesday',
		scheduleWeekdayWednesday: 'Wednesday',
		scheduleWeekdayThursday: 'Thursday',
		scheduleWeekdayFriday: 'Friday',
		scheduleWeekdaySaturday: 'Saturday',
		scheduleHourIntervalSingularTemplate: 'Every {count} hour',
		scheduleHourIntervalTemplate: 'Every {count} hours',
		scheduleMinuteIntervalSingularTemplate: 'Every {count} minute',
		scheduleMinuteIntervalTemplate: 'Every {count} minutes',
		scheduleSecondIntervalSingularTemplate: 'Every {count} second',
		scheduleSecondIntervalTemplate: 'Every {count} seconds'
	}
} as const;

export type MemoryText = PageText<typeof memoryText>;
