export const memoryText = {
	ko: {
		pageTitle: '기억 · 김인턴',
		title: '기억',
		description: '김인턴이 볼 수 있는 기억을 네트워크 그래프로 확인합니다.',
		configured: '설정됨',
		unconfigured: '미설정',
		reachable: '연결됨',
		unreachable: '연결 불가',
		searchPlaceholder: '기억 검색',
		search: '검색',
		refresh: '새로고침',
		graphTab: '기억 지도',
		scheduleTab: '예약 작업',
		namespaces: '네임스페이스',
		episodes: '에피소드',
		facts: '기억',
		memoryDetails: '저장된 기억',
		source: '출처',
		score: '신뢰도',
		scoreUnavailable: '신뢰도 미제공',
		loadFailed: '기억 그래프를 불러오지 못했습니다.',
		noVisibleMemory: '아직 볼 수 있는 기억이 없습니다.',
		workspace: '작업공간',
		searchError: '검색',
		ingestionError: '수집',
		scheduleDescription: '김인턴이 실행할 예정인 예약 작업입니다.',
		scheduleTitle: '예약 작업',
		scheduleStatus: '상태',
		scheduleKind: '유형',
		scheduleNextRun: '다음 실행',
		scheduleTiming: '일정',
		scheduleLoading: '예약 작업을 불러오는 중입니다.',
		scheduleEmpty: '아직 예약 작업이 없습니다.',
		scheduleLoadFailed: '예약 작업을 불러오지 못했습니다.',
		schedulePageSummaryTemplate: '{start}-{end} / {total}',
		schedulePagination: '예약 작업 페이지',
		scheduleMorePages: '더 많은 페이지',
		schedulePreviousPage: '이전',
		scheduleNextPage: '다음',
		scheduleStatusActive: '예약됨',
		scheduleStatusInactive: '중지됨',
		scheduleStatusRetrying: '재시도 예정',
		scheduleKindCron: '정기 반복',
		scheduleKindInterval: '간격 반복',
		scheduleKindOnce: '1회 예약',
		scheduleKindUnknown: '예약',
		scheduleOnce: '1회 실행',
		scheduleTimingUnavailable: '일정 없음',
		scheduleTimeUnavailable: '다음 실행 없음',
		scheduleCronDailyTemplate: '매일 {time}',
		scheduleCronWeekdaysTemplate: '평일 {time}',
		scheduleCronWeeklyTemplate: '매주 {weekday} {time}',
		scheduleWeekdaySunday: '일요일',
		scheduleWeekdayMonday: '월요일',
		scheduleWeekdayTuesday: '화요일',
		scheduleWeekdayWednesday: '수요일',
		scheduleWeekdayThursday: '목요일',
		scheduleWeekdayFriday: '금요일',
		scheduleWeekdaySaturday: '토요일',
		scheduleHourIntervalSingularTemplate: '{count}시간마다',
		scheduleHourIntervalTemplate: '{count}시간마다',
		scheduleMinuteIntervalSingularTemplate: '{count}분마다',
		scheduleMinuteIntervalTemplate: '{count}분마다',
		scheduleSecondIntervalSingularTemplate: '{count}초마다',
		scheduleSecondIntervalTemplate: '{count}초마다'
	},
	en: {
		pageTitle: 'Memory · intern kim',
		title: 'Memory',
		description: 'Your visible Blueclaw memory as a network graph.',
		configured: 'configured',
		unconfigured: 'unconfigured',
		reachable: 'reachable',
		unreachable: 'unreachable',
		searchPlaceholder: 'Search memory facts',
		search: 'Search',
		refresh: 'Refresh',
		graphTab: 'Memory map',
		scheduleTab: 'Schedules',
		namespaces: 'namespaces',
		episodes: 'episodes',
		facts: 'facts',
		memoryDetails: 'Stored memory',
		source: 'source',
		score: 'score',
		scoreUnavailable: 'score unavailable',
		loadFailed: 'Memory graph could not be loaded.',
		noVisibleMemory: 'No visible memory yet.',
		workspace: 'workspace',
		searchError: 'search',
		ingestionError: 'ingestion',
		scheduleDescription: 'Scheduled work InternKim will run later.',
		scheduleTitle: 'Schedule',
		scheduleStatus: 'Status',
		scheduleKind: 'Type',
		scheduleNextRun: 'Next run',
		scheduleTiming: 'Schedule',
		scheduleLoading: 'Loading schedules.',
		scheduleEmpty: 'No schedules yet.',
		scheduleLoadFailed: 'Schedules could not be loaded.',
		schedulePageSummaryTemplate: '{start}-{end} of {total}',
		schedulePagination: 'Schedule pages',
		scheduleMorePages: 'More pages',
		schedulePreviousPage: 'Previous',
		scheduleNextPage: 'Next',
		scheduleStatusActive: 'scheduled',
		scheduleStatusInactive: 'stopped',
		scheduleStatusRetrying: 'retry scheduled',
		scheduleKindCron: 'recurring',
		scheduleKindInterval: 'interval',
		scheduleKindOnce: 'one-time',
		scheduleKindUnknown: 'schedule',
		scheduleOnce: 'one-time run',
		scheduleTimingUnavailable: 'schedule unavailable',
		scheduleTimeUnavailable: 'next run unavailable',
		scheduleCronDailyTemplate: 'Every day at {time}',
		scheduleCronWeekdaysTemplate: 'Weekdays at {time}',
		scheduleCronWeeklyTemplate: 'Every {weekday} at {time}',
		scheduleWeekdaySunday: 'Sunday',
		scheduleWeekdayMonday: 'Monday',
		scheduleWeekdayTuesday: 'Tuesday',
		scheduleWeekdayWednesday: 'Wednesday',
		scheduleWeekdayThursday: 'Thursday',
		scheduleWeekdayFriday: 'Friday',
		scheduleWeekdaySaturday: 'Saturday',
		scheduleHourIntervalSingularTemplate: 'Every {count} hour',
		scheduleHourIntervalTemplate: 'Every {count} hours',
		scheduleMinuteIntervalSingularTemplate: 'Every {count} minute',
		scheduleMinuteIntervalTemplate: 'Every {count} minutes',
		scheduleSecondIntervalSingularTemplate: 'Every {count} second',
		scheduleSecondIntervalTemplate: 'Every {count} seconds'
	}
} as const;

export type MemoryText = { readonly [Key in keyof typeof memoryText.ko]: string };
