export const organizationDirectoryText = {
	ko: {
		title: '조직도',
		search: '검색',
		searchPlaceholder: '이름, 직책, 이메일 검색',
		filter: '필터',
		organization: '조직',
		allOrganizations: '회사',
		organizationNavigation: '조직',
		organizationActions: '조직 작업',
		addOrganization: '조직 추가',
		openOrganizations: '조직 목록',
		editOrganizations: '편집',
		saveOrganizations: '저장',
		cancelOrganizationEdit: '취소',
		expandOrganization: '펼치기',
		collapseOrganization: '접기',
		companyResponsible: '회사 책임자',
		organizationResponsible: '조직 책임자',
		dragTopLevel: '회사 바로 아래 · 최상위',
		dragUnderPrefix: '하위로 이동',
		editPerson: '수정하기',
		loading: '조직도를 불러오고 있습니다.',
		empty: '표시할 조직도 구성원이 없습니다.',
		loadError: '조직도를 불러오지 못했습니다.',
		memberCountUnit: '명',
		primaryOrganization: '소속 팀',
		directSupervisor: '직속 상관',
		noSupervisor: '없음',
		noTitle: '직책 미입력',
		unassignedTeam: '팀 미지정',
		position: '직책',
		hireDate: '입사일',
		notProvided: '미입력',
		personDetail: '직원 상세',
		closeDetail: '상세 닫기',
		basicInformation: '기본 정보',
		email: '이메일'
	},
	en: {
		title: 'Org chart',
		search: 'Search',
		searchPlaceholder: 'Search name, title, email',
		filter: 'Filter',
		organization: 'Organization',
		allOrganizations: 'Company',
		organizationNavigation: 'Organization',
		organizationActions: 'Organization actions',
		addOrganization: 'Add organization',
		openOrganizations: 'Organizations',
		editOrganizations: 'Edit',
		saveOrganizations: 'Save',
		cancelOrganizationEdit: 'Cancel',
		expandOrganization: 'Expand',
		collapseOrganization: 'Collapse',
		companyResponsible: 'Company owner',
		organizationResponsible: 'Organization owner',
		dragTopLevel: 'Directly under the company · Top level',
		dragUnderPrefix: 'Move under',
		editPerson: 'Edit',
		loading: 'Loading the org chart.',
		empty: 'No org chart members to show.',
		loadError: 'Could not load the org chart.',
		memberCountUnit: ' people',
		primaryOrganization: 'Team',
		directSupervisor: 'Direct manager',
		noSupervisor: 'None',
		noTitle: 'No title',
		unassignedTeam: 'Unassigned',
		position: 'Position',
		hireDate: 'Hire date',
		notProvided: 'Not provided',
		personDetail: 'Person detail',
		closeDetail: 'Close detail',
		basicInformation: 'Basic information',
		email: 'Email'
	}
} as const;
