export const organizationDirectoryText = {
	ko: {
		title: '조직',
		inviteMember: '구성원 초대',
		inviteDescription: '이름과 이메일로 초대하면 임시 비밀번호가 나옵니다. 이름은 메신저에 그대로 쓰입니다.',
		inviteName: '이름',
		inviteEmail: '이메일',
		invite: '초대',
		inviteHandOver: '본인에게 전달하세요. 로그인 후 패스키를 등록하면 비밀번호는 더 필요 없습니다.',
		inviteFailed: '초대하지 못했습니다.',
		cancel: '취소',
		done: 'completed',
		search: '검색',
		selectEmployee: '직원 선택',
		selectOrganization: '조직 선택',
		searchPlaceholder: '이름 또는 직책 검색',
		filter: '필터',
		organization: '조직',
		allOrganizations: '전체',
		allEmployees: '전체',
		organizationNavigation: '조직',
		organizationActions: '조직 작업',
		addOrganization: '조직 추가',
		openOrganizations: '목차',
		editOrganizations: '편집',
		saveOrganizations: '저장',
		cancelOrganizationEdit: '취소',
		expandOrganization: '펼치기',
		collapseOrganization: '접기',
		companyRepresentative: '대표',
		responsible: '책임자',
		sendEmail: '메일 보내기',
		callPhone: '전화 걸기',
		sendDirectMessage: 'DM 보내기',
		phoneNumber: '전화번호',
		tenureYearUnit: '년',
		tenureMonthUnit: '개월',
		dragTopLevel: '전체 바로 아래 · 최상위',
		dragUnderPrefix: '하위로 이동',
		editPerson: '수정하기',
		empty: '표시할 조직도 구성원이 없습니다.',
		loadError: '조직도를 불러오지 못했습니다.',
		memberCountUnit: '명',
		primaryOrganization: '소속 팀',
		directSupervisor: '직속 상관',
		noSupervisor: '없음',
		noTitle: '직책 미입력',
		unassignedTeam: '팀 미지정',
		position: '직책',
		hireDate: '입사일',
		notProvided: '미입력',
		personDetail: '직원 상세',
		closeDetail: '상세 닫기',
		discardEditsTitle: '저장하지 않은 변경사항이 있습니다',
		discardEditsDescription: '지금 닫으면 수정한 내용이 사라집니다.',
		keepEditing: '계속 수정',
		discardEdits: '닫기',
		basicInformation: '기본 정보',
		email: '이메일'
	},
	en: {
		inviteMember: 'Invite someone',
		inviteDescription: 'Invite by name and address; a temporary password comes back. The name is what the messenger shows.',
		inviteName: 'Name',
		inviteEmail: 'Email',
		invite: 'Invite',
		inviteHandOver: 'Hand this over. Once they sign in and set up a passkey, no password is needed.',
		inviteFailed: 'The invitation did not go through.',
		cancel: 'Cancel',
		done: 'Done',
		title: 'Organization',
		search: 'Search',
		selectEmployee: 'Select employee',
		selectOrganization: 'Select organization',
		searchPlaceholder: 'Search name or title',
		filter: 'Filter',
		organization: 'Organization',
		allOrganizations: 'All',
		allEmployees: 'All',
		organizationNavigation: 'Organization',
		organizationActions: 'Organization actions',
		addOrganization: 'Add organization',
		openOrganizations: 'Contents',
		editOrganizations: 'Edit',
		saveOrganizations: 'Save',
		cancelOrganizationEdit: 'Cancel',
		expandOrganization: 'Expand',
		collapseOrganization: 'Collapse',
		companyRepresentative: 'Owner',
		responsible: 'Head',
		sendEmail: 'Send email',
		callPhone: 'Call',
		sendDirectMessage: 'Send direct message',
		phoneNumber: 'Phone',
		tenureYearUnit: 'y',
		tenureMonthUnit: 'm',
		dragTopLevel: 'Directly under all organizations · Top level',
		dragUnderPrefix: 'Move under',
		editPerson: 'Edit',
		empty: 'No org chart members to show.',
		loadError: 'Could not load the org chart.',
		memberCountUnit: ' people',
		primaryOrganization: 'Team',
		directSupervisor: 'Direct manager',
		noSupervisor: 'None',
		noTitle: 'No title',
		unassignedTeam: 'Unassigned',
		position: 'Position',
		hireDate: 'Hire date',
		notProvided: 'Not provided',
		personDetail: 'Person detail',
		closeDetail: 'Close detail',
		discardEditsTitle: 'This profile has unsaved changes',
		discardEditsDescription: 'Closing now throws away what you edited.',
		keepEditing: 'Keep editing',
		discardEdits: 'Close',
		basicInformation: 'Basic information',
		email: 'Email'
	}
} as const;
