export const tasksText = {
	ko: {
		pageTitle: '작업 기록 · 김인턴',
		title: '작업 기록',
		description: '에이전트 작업 실행과 이벤트 타임라인을 확인합니다.',
		refresh: '새로고침',
		statusAll: '전체',
		statusFailed: '실패',
		statusRunning: '진행 중',
		statusCompleted: '완료',
		empty: '표시할 작업이 없습니다.',
		loadError: '작업 목록을 불러오지 못했습니다.',
		detailLoadError: '작업 상세를 불러오지 못했습니다.',
		backToList: '작업 목록',
		promptLabel: '요청',
		resultLabel: '결과',
		failureReasonLabel: '실패 사유',
		timelineTitle: '이벤트 타임라인',
		llmCalls: 'LLM 호출',
		llmLatency: 'LLM 지연 합계',
		toolCalls: '도구 실행',
		eventCount: '이벤트',
		updatedAt: '갱신',
		createdAt: '생성',
		laneLLM: 'LLM',
		laneTool: '도구',
		laneFailure: '실패',
		laneControl: '제어'
	},
	en: {
		pageTitle: 'Task Runs · InternKim',
		title: 'Task Runs',
		description: 'Inspect agent task runs and their event timelines.',
		refresh: 'Refresh',
		statusAll: 'All',
		statusFailed: 'Failed',
		statusRunning: 'Running',
		statusCompleted: 'Completed',
		empty: 'No task runs to show.',
		loadError: 'Could not load task runs.',
		detailLoadError: 'Could not load task detail.',
		backToList: 'Task runs',
		promptLabel: 'Prompt',
		resultLabel: 'Result',
		failureReasonLabel: 'Failure reason',
		timelineTitle: 'Event timeline',
		llmCalls: 'LLM calls',
		llmLatency: 'Total LLM latency',
		toolCalls: 'Tool calls',
		eventCount: 'Events',
		updatedAt: 'Updated',
		createdAt: 'Created',
		laneLLM: 'LLM',
		laneTool: 'Tool',
		laneFailure: 'Failure',
		laneControl: 'Control'
	}
};

export type TasksText = { readonly [Key in keyof typeof tasksText.ko]: string };
