export const tasksText = {
	ko: {
		pageTitle: '작업 기록 · 김인턴',
		title: '작업 기록',
		description: '에이전트 작업 실행과 이벤트 타임라인을 확인합니다.',
		refresh: '새로고침',
		statusAll: '전체',
		statusFailed: '실패',
		statusRunning: '진행 중',
		statusCompleted: '완료',
		statusPlanned: '계획됨',
		statusWaitingUserInput: '입력 대기',
		statusWaitingApproval: '승인 대기',
		statusBlocked: '차단됨',
		statusInterrupted: '중단됨',
		statusCancelled: '취소됨',
		columnRequester: '요청자',
		columnRequest: '요청',
		columnStatus: '상태',
		columnUpdated: '갱신',
		empty: '표시할 작업이 없습니다.',
		loadError: '작업 목록을 불러오지 못했습니다.',
		paginationSummary: '{total}개 중 {from}–{to}',
		paginationLabel: '작업 기록 페이지',
		paginationPrevious: '이전',
		paginationNext: '다음',
		detailLoadError: '작업 상세를 불러오지 못했습니다.',
		backToList: '작업 목록',
		promptLabel: '요청',
		resultLabel: '결과',
		failureReasonLabel: '실패 사유',
		timelineTitle: '이벤트 타임라인',
		llmCalls: 'LLM 호출',
		llmLatency: 'LLM 지연 합계',
		llmTokens: '토큰',
		llmCached: '캐시 토큰',
		llmCost: '비용',
		toolCalls: '도구 실행',
		eventCount: '이벤트',
		updatedAt: '갱신',
		createdAt: '생성',
		laneLLM: 'LLM',
		laneTool: '도구',
		laneFailure: '실패',
		laneControl: '제어',
		serviceLogsTitle: '서비스 로그',
		serviceLogsLoad: '로그 불러오기',
		serviceLogsEmpty: '관련 로그가 없습니다.',
		serviceLogsError: '로그를 불러오지 못했습니다.'
	},
	en: {
		pageTitle: 'Task Runs · InternKim',
		title: 'Task Runs',
		description: 'Inspect agent task runs and their event timelines.',
		refresh: 'Refresh',
		statusAll: 'All',
		statusFailed: 'Failed',
		statusRunning: 'Running',
		statusCompleted: 'Completed',
		statusPlanned: 'Planned',
		statusWaitingUserInput: 'Waiting input',
		statusWaitingApproval: 'Waiting approval',
		statusBlocked: 'Blocked',
		statusInterrupted: 'Interrupted',
		statusCancelled: 'Cancelled',
		columnRequester: 'Requester',
		columnRequest: 'Request',
		columnStatus: 'Status',
		columnUpdated: 'Updated',
		empty: 'No task runs to show.',
		loadError: 'Could not load task runs.',
		paginationSummary: '{from}–{to} of {total}',
		paginationLabel: 'Task run pages',
		paginationPrevious: 'Previous',
		paginationNext: 'Next',
		detailLoadError: 'Could not load task detail.',
		backToList: 'Task runs',
		promptLabel: 'Prompt',
		resultLabel: 'Result',
		failureReasonLabel: 'Failure reason',
		timelineTitle: 'Event timeline',
		llmCalls: 'LLM calls',
		llmLatency: 'Total LLM latency',
		llmTokens: 'Tokens',
		llmCached: 'Cached',
		llmCost: 'Cost',
		toolCalls: 'Tool calls',
		eventCount: 'Events',
		updatedAt: 'Updated',
		createdAt: 'Created',
		laneLLM: 'LLM',
		laneTool: 'Tool',
		laneFailure: 'Failure',
		laneControl: 'Control',
		serviceLogsTitle: 'Service logs',
		serviceLogsLoad: 'Load logs',
		serviceLogsEmpty: 'No correlated log lines.',
		serviceLogsError: 'Could not load service logs.'
	}
};

export type TasksText = { readonly [Key in keyof typeof tasksText.ko]: string };
