export const tasksText = {
	ko: {
		pageTitle: '작업 기록 · 김인턴',
		title: '작업 기록',
		description: '최근 실행, 상태, 비용을 한 화면에서 확인합니다.',
		refresh: '새로고침',
		statusAll: '전체',
		statusFailed: '실패',
		statusRunning: '진행 중',
		statusCompleted: '완료',
		statusPlanned: '계획됨',
		statusWaitingUserInput: '입력 대기',
		statusWaitingApproval: '승인 대기',
		statusBlocked: '차단됨',
		statusInterrupted: '중단됨',
		statusCancelled: '취소됨',
		columnRequester: '요청자',
		columnRequest: '요청',
		columnStatus: '상태',
		columnCost: '비용',
		columnUpdated: '갱신',
		columnActions: '행 메뉴',
		empty: '표시할 작업이 없습니다.',
		loadError: '작업 목록을 불러오지 못했습니다.',
		deleteError: '작업 기록을 삭제하지 못했습니다.',
		deleteTaskTitle: '작업 기록 삭제',
		deleteTaskDescription: '{id} 작업 기록과 이벤트를 삭제합니다. 이 작업은 되돌릴 수 없습니다.',
		deleteTask: '삭제',
		cancelDelete: '취소',
		deleteTaskAction: '작업 기록 삭제',
		paginationSummary: '{total}개 중 {from}–{to}',
		paginationLabel: '작업 기록 페이지',
		paginationPrevious: '이전',
		paginationNext: '다음',
		detailLoadError: '작업 상세를 불러오지 못했습니다.',
		backToList: '작업 목록',
		promptLabel: '요청',
		resultLabel: '결과',
		failureReasonLabel: '실패 사유',
		timelineTitle: '이벤트 타임라인',
		llmCalls: 'LLM 호출',
		llmLatency: 'LLM 지연 합계',
		llmTokens: '토큰',
		llmCached: '캐시 토큰',
		llmCost: '비용',
		toolCalls: '도구 실행',
		taskCount: '작업',
		eventCount: '이벤트',
		dailyCostTitle: '날짜별 비용',
		dailyCostScopeAll: '현재 필터 전체',
		dailyCostScopeLimited: '최근 {count}개 작업 기준',
		dailyCostMeta: '{tasks}개 작업 · {calls}회 LLM',
		updatedAt: '갱신',
		createdAt: '생성',
		laneLLM: 'LLM',
		laneTool: '도구',
		laneFailure: '실패',
		laneControl: '제어',
		serviceLogsTitle: '서비스 로그',
		serviceLogsDescription: '작업 ID로 필터링된 Blueclaw 로그를 확인합니다.',
		serviceLogsPrompt: '필요할 때만 로그를 불러옵니다.',
		serviceLogsLoad: '로그 불러오기',
		serviceLogsEmpty: '관련 로그가 없습니다.',
		serviceLogsError: '로그를 불러오지 못했습니다.',
		taskSummaryTitle: '작업 요약',
		requesterLabel: '요청자',
		copyForAI: '상세 복사',
		copyPrompt: '요청 복사',
		copyResult: '결과 복사',
		copyEvent: '이벤트 복사',
		copyVisibleEvents: '표시 중인 이벤트 복사',
		copyLogs: '로그 복사',
		timelineTab: '타임라인',
		briefTab: '요청/결과',
		logsTab: '로그',
		allEvents: '전체',
		visibleEvents: '{total}개 중 {count}개 표시',
		searchEvents: '이벤트 검색',
		noMatchingEvents: '조건에 맞는 이벤트가 없습니다.'
	},
	en: {
		pageTitle: 'Task Runs · InternKim',
		title: 'Task Runs',
		description: 'Review recent runs, status, and cost in one place.',
		refresh: 'Refresh',
		statusAll: 'All',
		statusFailed: 'Failed',
		statusRunning: 'Running',
		statusCompleted: 'Completed',
		statusPlanned: 'Planned',
		statusWaitingUserInput: 'Waiting input',
		statusWaitingApproval: 'Waiting approval',
		statusBlocked: 'Blocked',
		statusInterrupted: 'Interrupted',
		statusCancelled: 'Cancelled',
		columnRequester: 'Requester',
		columnRequest: 'Request',
		columnStatus: 'Status',
		columnCost: 'Cost',
		columnUpdated: 'Updated',
		columnActions: 'Row actions',
		empty: 'No task runs to show.',
		loadError: 'Could not load task runs.',
		deleteError: 'Could not delete the task run.',
		deleteTaskTitle: 'Delete Task Run',
		deleteTaskDescription: 'Delete task run {id} and its events. This cannot be undone.',
		deleteTask: 'Delete',
		cancelDelete: 'Cancel',
		deleteTaskAction: 'Delete task run',
		paginationSummary: '{from}–{to} of {total}',
		paginationLabel: 'Task run pages',
		paginationPrevious: 'Previous',
		paginationNext: 'Next',
		detailLoadError: 'Could not load task detail.',
		backToList: 'Task runs',
		promptLabel: 'Prompt',
		resultLabel: 'Result',
		failureReasonLabel: 'Failure reason',
		timelineTitle: 'Event timeline',
		llmCalls: 'LLM calls',
		llmLatency: 'Total LLM latency',
		llmTokens: 'Tokens',
		llmCached: 'Cached',
		llmCost: 'Cost',
		toolCalls: 'Tool calls',
		taskCount: 'tasks',
		eventCount: 'Events',
		dailyCostTitle: 'Daily cost',
		dailyCostScopeAll: 'Current filter',
		dailyCostScopeLimited: 'Latest {count} tasks',
		dailyCostMeta: '{tasks} tasks · {calls} LLM calls',
		updatedAt: 'Updated',
		createdAt: 'Created',
		laneLLM: 'LLM',
		laneTool: 'Tool',
		laneFailure: 'Failure',
		laneControl: 'Control',
		serviceLogsTitle: 'Service logs',
		serviceLogsDescription: 'Inspect Blueclaw logs filtered by task ID.',
		serviceLogsPrompt: 'Load logs only when needed.',
		serviceLogsLoad: 'Load logs',
		serviceLogsEmpty: 'No correlated log lines.',
		serviceLogsError: 'Could not load service logs.',
		taskSummaryTitle: 'Task summary',
		requesterLabel: 'Requester',
		copyForAI: 'Copy detail',
		copyPrompt: 'Copy prompt',
		copyResult: 'Copy result',
		copyEvent: 'Copy event',
		copyVisibleEvents: 'Copy visible events',
		copyLogs: 'Copy logs',
		timelineTab: 'Timeline',
		briefTab: 'Prompt/result',
		logsTab: 'Logs',
		allEvents: 'All',
		visibleEvents: 'Showing {count} of {total}',
		searchEvents: 'Search events',
		noMatchingEvents: 'No events match these filters.'
	}
};

export type TasksText = { readonly [Key in keyof typeof tasksText.ko]: string };
