export const orgchartText = {
	ko: {
		title: '조직도',
		description: '상급자 기준 보고 체계를 한눈에 보여줍니다. 편집을 켜면 기존 사용자에게 조직도 메타데이터를 붙일 수 있습니다.',
		jobTitle: '직책',
		jobTitlePlaceholder: '백엔드 엔지니어',
		group: '그룹',
		organization: '소속 조직',
		groupPlaceholder: '엔지니어링',
		manageGroups: '그룹 관리',
		addGroup: '추가',
		addOrganization: '조직 추가',
		newGroup: '새 조직',
		supervisor: '직속 상관',
		editMode: '편집',
		save: '저장',
		cancel: '취소',
		unsavedChanges: '저장하지 않은 조직도 변경사항이 있습니다. 각 카드에서 저장 또는 취소를 먼저 선택해 주세요.',
		none: '없음'
	},
	en: {
		title: 'Org chart',
		description: 'See the reporting hierarchy at a glance. Turn on edit to attach org chart metadata to existing users.',
		jobTitle: 'Job title',
		jobTitlePlaceholder: 'Backend engineer',
		group: 'Group',
		organization: 'Organization',
		groupPlaceholder: 'Engineering',
		manageGroups: 'Manage groups',
		addGroup: 'Add',
		addOrganization: 'Add organization',
		newGroup: 'New organization',
		supervisor: 'Direct manager',
		editMode: 'Edit',
		save: 'Save',
		cancel: 'Cancel',
		unsavedChanges: 'There are unsaved org chart changes. Save or cancel each card before closing edit mode.',
		none: 'None'
	}
} as const;
