export const orgchartText = {
	ko: {
		title: '조직도',
		description: '상급자 기준 보고 체계를 한눈에 보여줍니다. 편집을 켜면 기존 사용자에게 조직도 메타데이터를 붙일 수 있습니다.',
		jobTitle: '직책',
		jobTitlePlaceholder: '백엔드 엔지니어',
		group: '그룹',
		primaryGroup: '주 소속 조직',
		groupMemberships: '참여 조직',
		groupPlaceholder: '엔지니어링',
		manageGroups: '그룹 관리',
		addGroup: '추가',
		addOrganization: '조직 추가',
		newGroup: '새 조직',
		positionLevel: '직책 레벨',
		positionLevelError: '1 이상의 숫자를 입력하세요.',
		supervisor: '상위 담당자',
		projects: '담당 프로젝트',
		projectsPlaceholder: '프로젝트 입력 후 Enter',
		teamRole: '팀 안 역할',
		teamRolePlaceholder: '디자인 시스템',
		employmentStatus: '재직 상태',
		employmentStatusLabels: {
			active: '재직',
			leave: '휴직',
			resigned: '퇴사'
		},
		visibility: '조직도 표시 여부',
		visible: '표시',
		hidden: '숨김',
		editMode: '편집',
		save: '저장',
		cancel: '취소',
		none: '없음'
	},
	en: {
		title: 'Org chart',
		description: 'See the reporting hierarchy at a glance. Turn on edit to attach org chart metadata to existing users.',
		jobTitle: 'Job title',
		jobTitlePlaceholder: 'Backend engineer',
		group: 'Group',
		primaryGroup: 'Primary organization',
		groupMemberships: 'Participating organizations',
		groupPlaceholder: 'Engineering',
		manageGroups: 'Manage groups',
		addGroup: 'Add',
		addOrganization: 'Add organization',
		newGroup: 'New organization',
		positionLevel: 'Position level',
		positionLevelError: 'Enter a number greater than or equal to 1.',
		supervisor: 'Manager',
		projects: 'Projects',
		projectsPlaceholder: 'Type a project and press Enter',
		teamRole: 'Team role',
		teamRolePlaceholder: 'Design systems',
		employmentStatus: 'Employment status',
		employmentStatusLabels: {
			active: 'Active',
			leave: 'Leave',
			resigned: 'Resigned'
		},
		visibility: 'Org chart visibility',
		visible: 'Visible',
		hidden: 'Hidden',
		editMode: 'Edit',
		save: 'Save',
		cancel: 'Cancel',
		none: 'None'
	}
} as const;
