import { orgchartText } from './orgchart-text';

export const adminText = {
	ko: {
		title: '김인턴',
		subtitle: 'Mattermost에서 사용하는 사내 AI 하드웨어',
		accessProtected: '접근 보호됨',
		heroTitle: '대화는 Mattermost에서 시작하세요.',
		heroDescription: '초대받은 팀원은 Mattermost에서 김인턴에게 바로 일을 맡길 수 있습니다.',
		openMattermost: 'Mattermost 열기',
		devicePending: '기기 등록이 끝나면 전용 Mattermost 주소와 초대 관리가 표시됩니다.',
		sections: {
			device: '기기',
			users: '사용자',
			orgchart: '조직도',
			credentials: '인증 정보',
			backup: '백업',
			bot: '봇',
			settings: '설정',
			network: '네트워크'
		},
		messages: {
			adminAuthRequired: '관리자 인증이 필요합니다.',
			adminAuthRequiredOnDevice: '관리자 인증이 필요합니다. 기기 주소의 /admin에서 Cloudflare Access로 로그인해 주세요.',
			deviceUnreachable: '기기에 연결할 수 없습니다.',
			botProfileLoadError: '봇 프로필을 불러오지 못했습니다.',
			botProfileSaveError: '봇 프로필 저장에 실패했습니다.',
			credentialsLoadError: '인증 정보 상태를 불러오지 못했습니다.',
			openRouterSaveError: 'OpenRouter 키 저장에 실패했습니다.',
			openRouterDeleteError: 'OpenRouter 키 삭제에 실패했습니다.',
			usersLoadError: '초대 목록을 불러오지 못했습니다.',
			userInviteError: '사용자 초대에 실패했습니다.',
			userSaveError: '사용자 저장에 실패했습니다.',
			userRemoveError: '사용자 제거에 실패했습니다.',
			backupStartError: '백업을 시작하지 못했습니다.',
			restoreStartError: '복구를 시작하지 못했습니다.',
			restoreUploadError: '복구 파일 업로드에 실패했습니다.',
			restoreUploadProgress: '복구 파일 업로드 중...'
		},
		device: {
			title: '기기 관리',
			description: '원격 기기의 상태와 관리자 인증을 확인합니다.',
			fleetIDPlaceholder: 'fleet id',
			check: '확인',
			online: '온라인',
			unreachable: '연결 불가',
			admin: '관리자',
			accessEmailMissing: 'Access 이메일 없음',
			claimFailed: '관리자 등록 실패',
			notAdmin: '관리자 아님',
			firstAdminClaimPending: '첫 관리자 등록 대기'
		},
		deviceUpdate: {
			title: '기기 업데이트',
			description: 'R2에 게시된 release set을 확인하고 수동으로 적용합니다.',
			currentRevision: '현재 버전',
			latestRevision: '최신 버전',
			jobPhase: '진행 상태',
			components: '최신 release 구성',
			recentReleases: '최근 release',
			currentBadge: '설치됨',
			noReleases: '표시할 release가 없습니다.',
			notAvailable: '없음',
			refresh: '새로고침',
			upgrade: '업그레이드',
			downgrade: '다운그레이드',
			upgradeConfirm: '{release} 버전으로 업그레이드할까요?',
			downgradeConfirm: '{release} 버전으로 다운그레이드할까요? 현재 설치된 버전보다 오래된 release입니다.',
			notice: '설치된 버전이 아닌 release를 선택해 업그레이드하거나 다운그레이드할 수 있습니다.',
			loadError: '업데이트 상태를 불러오지 못했습니다.',
			applyError: '업데이트를 시작하지 못했습니다.',
			states: {
				current: '최신 상태',
				updateAvailable: '업데이트 가능',
				updating: '업데이트 중',
				unknown: '확인 불가',
				idle: '대기',
				checking: '확인 중',
				downloading: '다운로드 중',
				verifying: '검증 중',
				installing: '설치 중',
				restarting: '재시작 중',
				running: '진행 중',
				completed: '완료',
				failed: '실패',
				alreadyCurrent: '최신 상태'
			}
		},
		bot: {
			title: '봇 프로필',
			description: '사용자에게 보이는 이름과 공개 설명을 바꿉니다. 내부 username은 internkim으로 유지됩니다.',
			identityNotice: 'identity extension은 Blueclaw 프롬프트에만 들어가고 Mattermost 설명에는 노출되지 않습니다.',
			displayNamePlaceholder: '표시 이름',
			englishDisplayNamePlaceholder: '영문 표시 이름',
			publicDescriptionPlaceholder: '공개 설명',
			aliasesPlaceholder: '별칭, 한 줄에 하나씩',
			identityExtensionPlaceholder: '프롬프트 전용 identity extension',
			save: '프로필 저장'
		},
		credentials: {
			title: '인증 정보',
			description: '웹 검색과 원격 제공자에 쓰는 키를 관리자만 등록합니다.',
			configured: '등록됨',
			missing: '없음',
			loading: '상태를 불러오는 중...',
			noKey: '등록된 키가 없습니다.',
			save: '테스트 후 저장',
			delete: '삭제',
			openRouterApiKeyPlaceholder: 'OpenRouter API 키',
			notice: '키는 저장 전에 검증되고, LLM이나 도구 결과에는 노출되지 않습니다.'
		},
		settings: {
			title: '작업공간 설정',
			description: '근태와 운영 화면에서 사용할 작업공간 설정입니다.',
			timeZone: '시간대',
			timeZonePlaceholder: 'system 또는 Asia/Seoul',
			timeZoneHint: '비워두거나 system으로 두면 기기 설정을 사용합니다. IANA timezone만 저장됩니다.',
			workspaceLanguageTitle: '작업공간 언어',
			workspaceLanguageDescription: 'Mattermost 채널 표시명을 이 언어로 일괄 업데이트합니다.',
			workspaceLanguageKorean: '한국어',
			workspaceLanguageEnglish: 'English',
			save: '저장',
			loadError: '설정을 불러오지 못했습니다.',
			saveSuccess: '저장되었습니다.',
			saveError: '설정을 저장하지 못했습니다.'
		},
		wifiProfiles: {
			title: 'WiFi',
			description: '이더넷 연결 중 WiFi를 추가하거나 비밀번호를 변경하세요. 저장 후 이더넷을 뽑으면 자동으로 WiFi로 전환됩니다.',
			active: '연결됨',
			ssidLabel: 'SSID',
			passwordLabel: '비밀번호',
			passwordPlaceholder: 'WPA 비밀번호',
			addTitle: 'WiFi 추가',
			ssidPlaceholder: '네트워크 이름',
			add: '추가',
			updatePassword: '비밀번호 변경',
			save: '저장',
			remove: '삭제',
			removeConfirm: '이 WiFi 연결을 삭제할까요?',
			empty: '등록된 WiFi가 없습니다.',
			loadError: 'WiFi 목록을 불러오지 못했습니다.',
			addError: 'WiFi 추가에 실패했습니다.',
			updateError: '비밀번호 변경에 실패했습니다.',
			removeError: 'WiFi 삭제에 실패했습니다.'
		},
		attendanceLocations: {
			title: '출근 장소',
			description: 'Mattermost 출근 버튼에 표시할 장소입니다. 최소 하나는 유지됩니다.',
			add: '추가',
			color: '장소 색상',
			placeholder: '사무실',
			default: '기본',
			remove: '장소 삭제',
			save: '저장',
			loadError: '출근 장소를 불러오지 못했습니다.',
			saveSuccess: '저장되었습니다.',
			saveError: '출근 장소를 저장하지 못했습니다.'
		},
		backup: {
			title: '암호화 백업',
			description: 'passphrase는 브라우저에서 원격 기기로만 전송됩니다.',
			create: '암호화 백업 만들기',
			download: '백업 다운로드',
			passphrasePlaceholder: '백업 passphrase',
			restoreConfirmPlaceholder: 'RESTORE 입력',
			manifestReady: 'manifest 준비됨',
			backupFallback: '백업',
			restoreTitle: '복구',
			restoreDescription: '복구하려는 대상 기기를 확인한 뒤 RESTORE를 입력하세요.',
			restore: '기기 복구'
		},
		users: {
			title: '허용된 사용자',
			description: '초대하면 Mattermost 계정과 임시 비밀번호가 만들어집니다. 비밀번호는 한 번만 표시됩니다.',
			deviceOnly: '초대 목록은 등록된 기기 주소에서 관리할 수 있습니다.',
			member: '일반',
			operationsAdmin: '운영자',
			admin: '관리자',
			handle: '핸들',
			realName: '이름',
			realNamePlaceholder: '홍길동',
			email: '이메일',
			hireDate: '입사일',
			note: '메모',
			noteEdit: '메모 편집',
			notePlaceholder: '사람별 비고를 입력하세요.',
			role: '권한',
			groups: '그룹',
			userCount: '사용자',
			adminCount: '관리자',
			handlePlaceholder: 'handle',
			emailPlaceholder: 'name@company.com',
			groupTitle: '그룹 관리',
			groupDescription: 'staff는 기본 그룹이며 삭제할 수 없습니다. Mattermost 연동 그룹은 circle-* 비공개 채널과 동기화됩니다.',
			groupID: '그룹 ID',
			groupName: '그룹 이름',
			groupIDPlaceholder: 'c-level',
			groupNamePlaceholder: 'C-Level',
			addGroup: '그룹 추가',
			mattermostManaged: 'Mattermost 비공개 채널과 동기화됩니다.',
			staffRequired: 'staff는 기본 그룹이라 삭제할 수 없습니다.',
			person: '사용자',
			actions: '작업',
			noMattermost: 'Mattermost 계정 없음',
			inviteTitle: '새 직원 초대',
			inviteDescription: '입사일은 업무 탭과 멤버 목록 정렬 기준으로 사용됩니다.',
			directoryTitle: '직원 디렉터리',
			directoryDescription: '입사일이 빠른 직원부터 업무 탭에 표시됩니다.',
			invite: '초대',
			passwordNotice: '비밀번호는 한 번만 표시됩니다. 관리자가 리셋하면 해당 사용자의 김인턴 DM 내역도 삭제됩니다.',
			temporaryPasswordTitle: 'Mattermost 로그인',
			temporaryPasswordNotice: '이 비밀번호는 다시 볼 수 없습니다. 사용자에게 안전한 채널로 전달하세요.',
			loading: '초대 목록을 불러오는 중...',
			empty: '등록된 사용자가 없습니다.',
			incomplete: '실명과 handle을 입력해 저장하세요.',
			cancel: '취소',
			save: '저장',
			resetPassword: '비밀번호 리셋',
			resetPasswordConfirm: 'Mattermost 비밀번호를 새로 만들고 이 사용자의 김인턴 DM 내역을 삭제합니다. 계속할까요?',
			resetPasswordError: '비밀번호 리셋에 실패했습니다.',
			makeMember: '일반으로 변경',
			makeAdmin: '관리자로 변경',
			remove: '삭제'
		},
		orgchart: orgchartText.ko
	},
	en: {
		title: 'intern kim',
		subtitle: 'Internal AI hardware for Mattermost and Slack',
		accessProtected: 'Access protected',
		heroTitle: 'Start conversations in Mattermost.',
		heroDescription: 'Invited teammates can assign work to Intern Kim directly from Mattermost and Slack.',
		openMattermost: 'Open Mattermost',
		devicePending: 'After device registration, the dedicated Mattermost address and invite controls will appear here.',
		sections: {
			device: 'Device',
			users: 'Users',
			orgchart: 'Org chart',
			credentials: 'Credentials',
			backup: 'Backup',
			bot: 'Bot',
			settings: 'Settings',
			network: 'Network'
		},
		messages: {
			adminAuthRequired: 'Admin authentication is required.',
			adminAuthRequiredOnDevice: 'Admin authentication is required. Sign in with Cloudflare Access at /admin on the device address.',
			deviceUnreachable: 'Could not connect to the device.',
			botProfileLoadError: 'Could not load the bot profile.',
			botProfileSaveError: 'Could not save the bot profile.',
			credentialsLoadError: 'Could not load credential status.',
			openRouterSaveError: 'Could not save the OpenRouter key.',
			openRouterDeleteError: 'Could not delete the OpenRouter key.',
			usersLoadError: 'Could not load the invite list.',
			userInviteError: 'Could not invite the user.',
			userSaveError: 'Could not save the user.',
			userRemoveError: 'Could not remove the user.',
			backupStartError: 'Could not start the backup.',
			restoreStartError: 'Could not start the restore.',
			restoreUploadError: 'Could not upload the restore file.',
			restoreUploadProgress: 'Uploading restore file...'
		},
		device: {
			title: 'Device Admin',
			description: 'Check remote device status and admin authentication.',
			fleetIDPlaceholder: 'fleet id',
			check: 'Check',
			online: 'online',
			unreachable: 'unreachable',
			admin: 'admin',
			accessEmailMissing: 'Access email missing',
			claimFailed: 'claim failed',
			notAdmin: 'not admin',
			firstAdminClaimPending: 'first admin claim pending'
		},
		deviceUpdate: {
			title: 'Device Update',
			description: 'Check and manually apply the release set published to R2.',
			currentRevision: 'Current version',
			latestRevision: 'Latest version',
			jobPhase: 'Progress',
			components: 'Latest release components',
			recentReleases: 'Recent releases',
			currentBadge: 'installed',
			noReleases: 'No releases to show.',
			notAvailable: 'none',
			refresh: 'Refresh',
			upgrade: 'Upgrade',
			downgrade: 'Downgrade',
			upgradeConfirm: 'Upgrade to {release}?',
			downgradeConfirm: 'Downgrade to {release}? This release is older than the installed version.',
			notice: 'Choose any release that is not currently installed to upgrade or downgrade.',
			loadError: 'Could not load update status.',
			applyError: 'Could not start the update.',
			states: {
				current: 'current',
				updateAvailable: 'update available',
				updating: 'updating',
				unknown: 'unknown',
				idle: 'idle',
				checking: 'checking',
				downloading: 'downloading',
				verifying: 'verifying',
				installing: 'installing',
				restarting: 'restarting',
				running: 'running',
				completed: 'completed',
				failed: 'failed',
				alreadyCurrent: 'current'
			}
		},
		bot: {
			title: 'Bot Profile',
			description: 'Change the user-facing name and public description. The internal username stays internkim.',
			identityNotice: 'The identity extension is only added to the Blueclaw prompt and is not exposed in the Mattermost description.',
			displayNamePlaceholder: 'display name',
			englishDisplayNamePlaceholder: 'English display name',
			publicDescriptionPlaceholder: 'public description',
			aliasesPlaceholder: 'aliases, one per line',
			identityExtensionPlaceholder: 'prompt-only identity extension',
			save: 'Save profile'
		},
		credentials: {
			title: 'Credentials',
			description: 'Admin-only keys for web search and remote providers.',
			configured: 'configured',
			missing: 'missing',
			loading: 'Loading status...',
			noKey: 'No key is configured.',
			save: 'Test & Save',
			delete: 'Delete',
			openRouterApiKeyPlaceholder: 'OpenRouter API key',
			notice: 'Keys are validated before saving and are never exposed to the LLM or tool results.'
		},
		settings: {
			title: 'Workspace Settings',
			description: 'Workspace settings used by attendance and operations screens.',
			timeZone: 'Time zone',
			timeZonePlaceholder: 'system or Asia/Seoul',
			timeZoneHint: 'Leave empty or set system to use the device setting. Only IANA time zones are saved.',
			workspaceLanguageTitle: 'Workspace language',
			workspaceLanguageDescription: 'Update Mattermost channel display names in this language.',
			workspaceLanguageKorean: '한국어',
			workspaceLanguageEnglish: 'English',
			save: 'Save',
			loadError: 'Could not load settings.',
			saveSuccess: 'Saved.',
			saveError: 'Could not save settings.'
		},
		attendanceLocations: {
			title: 'Attendance locations',
			description: 'Locations shown on the Mattermost attendance button. Keep at least one location.',
			add: 'Add',
			color: 'Location color',
			placeholder: 'Office',
			default: 'Default',
			remove: 'Remove location',
			save: 'Save',
			loadError: 'Could not load attendance locations.',
			saveSuccess: 'Saved.',
			saveError: 'Could not save attendance locations.'
		},
		wifiProfiles: {
			title: 'WiFi',
			description: 'Add or update WiFi credentials while on ethernet. After saving, unplug ethernet and the device will connect automatically.',
			active: 'Connected',
			ssidLabel: 'SSID',
			passwordLabel: 'Password',
			passwordPlaceholder: 'WPA password',
			addTitle: 'Add WiFi',
			ssidPlaceholder: 'Network name',
			add: 'Add',
			updatePassword: 'Change password',
			save: 'Save',
			remove: 'Remove',
			removeConfirm: 'Remove this WiFi connection?',
			empty: 'No WiFi profiles found.',
			loadError: 'Could not load WiFi profiles.',
			addError: 'Could not add WiFi.',
			updateError: 'Could not update password.',
			removeError: 'Could not remove WiFi.'
		},
		backup: {
			title: 'Encrypted Backup',
			description: 'The passphrase is sent only from this browser to the remote device.',
			create: 'Create encrypted backup',
			download: 'Download backup',
			passphrasePlaceholder: 'backup passphrase',
			restoreConfirmPlaceholder: 'type RESTORE',
			manifestReady: 'manifest ready',
			backupFallback: 'backup',
			restoreTitle: 'Restore',
			restoreDescription: 'Confirm the target device, then type RESTORE.',
			restore: 'Restore device'
		},
		users: {
			title: 'Allowed Users',
			description: 'Inviting a user creates a Mattermost account and one-time temporary password.',
			deviceOnly: 'Invites can be managed from a registered device address.',
			member: 'Member',
			operationsAdmin: 'Operator',
			admin: 'Admin',
			handle: 'Handle',
			realName: 'Name',
			realNamePlaceholder: 'Jane Kim',
			email: 'Email',
			hireDate: 'Hire date',
			note: 'Note',
			noteEdit: 'Edit note',
			notePlaceholder: 'Add an internal note for this person.',
			role: 'Role',
			groups: 'Groups',
			userCount: 'users',
			adminCount: 'admin',
			handlePlaceholder: 'handle',
			emailPlaceholder: 'name@company.com',
			groupTitle: 'Group management',
			groupDescription: 'staff is required and cannot be removed. Mattermost-managed groups sync with circle-* private channels.',
			groupID: 'Group ID',
			groupName: 'Group name',
			groupIDPlaceholder: 'c-level',
			groupNamePlaceholder: 'C-Level',
			addGroup: 'Add group',
			mattermostManaged: 'Synced with a Mattermost private channel.',
			staffRequired: 'staff is required and cannot be removed.',
			person: 'Person',
			actions: 'Actions',
			noMattermost: 'No Mattermost account',
			inviteTitle: 'Invite employee',
			inviteDescription: 'Hire date controls the Flow tab and member order.',
			directoryTitle: 'Employee directory',
			directoryDescription: 'Flow tabs show earlier hire dates first.',
			invite: 'Invite',
			passwordNotice: 'Passwords are shown once. Admin resets also delete that user’s Intern Kim DM history.',
			temporaryPasswordTitle: 'Mattermost login',
			temporaryPasswordNotice: 'This password cannot be shown again. Share it with the user through a safe channel.',
			loading: 'Loading invited users...',
			empty: 'No users are registered.',
			incomplete: 'Add a real name and handle, then save.',
			cancel: 'Cancel',
			save: 'Save',
			resetPassword: 'Reset password',
			resetPasswordConfirm: 'This creates a new Mattermost password and deletes this user’s Intern Kim DM history. Continue?',
			resetPasswordError: 'Could not reset the password.',
			makeMember: 'Make member',
			makeAdmin: 'Make admin',
			remove: 'Remove'
		},
		orgchart: orgchartText.en
	}
} as const;
