package browser

// Wire protocol between the companion Go daemon and the browser extension's
// background service worker, exchanged as JSON text frames over
// ws://127.0.0.1:<port> (see ExtensionWebSocketBridge). Every message shares
// the ExtensionBridgeMessage envelope; only the fields relevant to Type are
// populated. RequestID correlates a daemon request with its extension
// response and is generated by the requester.
//
// Extension -> daemon:
//
//	ready        {type:"ready", ready:{extensionVersion, tabID}}
//	domSnapshot  {type:"domSnapshot", requestID, snapshot:{...}}
//	resolvedRef  {type:"resolvedRef", requestID, resolvedRef:{...}}
//	navigated    {type:"navigated", requestID, snapshot:{...}}
//	error        {type:"error", requestID, error}
//
// Daemon -> extension:
//
//	requestSnapshot {type:"requestSnapshot", requestID}
//	resolveRef      {type:"resolveRef", requestID, ref}
//	navigate        {type:"navigate", requestID, url}
//
// rect and viewport values are CSS pixels in the page's own coordinate
// space, exactly as reported by getBoundingClientRect() and the window
// object. The daemon combines them with chrome offset math (see
// elementCenterScreenPoint) to reach OS screen coordinates; the extension
// must not attempt that conversion itself.
type ExtensionBridgeMessageType string

const (
	ExtensionBridgeMessageReady           ExtensionBridgeMessageType = "ready"
	ExtensionBridgeMessageRequestSnapshot ExtensionBridgeMessageType = "requestSnapshot"
	ExtensionBridgeMessageDOMSnapshot     ExtensionBridgeMessageType = "domSnapshot"
	ExtensionBridgeMessageResolveRef      ExtensionBridgeMessageType = "resolveRef"
	ExtensionBridgeMessageResolvedRef     ExtensionBridgeMessageType = "resolvedRef"
	ExtensionBridgeMessageNavigate        ExtensionBridgeMessageType = "navigate"
	ExtensionBridgeMessageNavigated       ExtensionBridgeMessageType = "navigated"
	ExtensionBridgeMessageError           ExtensionBridgeMessageType = "error"
)

type ExtensionBridgeMessage struct {
	Type        ExtensionBridgeMessageType `json:"type"`
	RequestID   string                     `json:"requestID,omitempty"`
	Ready       *ExtensionReadyPayload     `json:"ready,omitempty"`
	Snapshot    *ExtensionDOMSnapshot      `json:"snapshot,omitempty"`
	Ref         string                     `json:"ref,omitempty"`
	ResolvedRef *ExtensionResolvedRef      `json:"resolvedRef,omitempty"`
	URL         string                     `json:"url,omitempty"`
	Error       string                     `json:"error,omitempty"`
}

type ExtensionReadyPayload struct {
	ExtensionVersion string `json:"extensionVersion"`
	TabID            int    `json:"tabID"`
}

type ExtensionElementRect struct {
	X      float64 `json:"x"`
	Y      float64 `json:"y"`
	Width  float64 `json:"width"`
	Height float64 `json:"height"`
}

type ExtensionElementDescriptor struct {
	Ref  string               `json:"ref"`
	Tag  string               `json:"tag"`
	Role string               `json:"role,omitempty"`
	Text string               `json:"text,omitempty"`
	Rect ExtensionElementRect `json:"rect"`
}

// ExtensionViewportGeometry carries the window measurements the daemon needs
// to translate a viewport-relative element rect into OS screen coordinates:
// screenX/screenY locate the browser window on the desktop, and the
// outer/inner deltas capture the chrome (tab strip, address bar, borders)
// surrounding the page viewport.
type ExtensionViewportGeometry struct {
	ScreenX          float64 `json:"screenX"`
	ScreenY          float64 `json:"screenY"`
	DevicePixelRatio float64 `json:"devicePixelRatio"`
	OuterWidth       float64 `json:"outerWidth"`
	InnerWidth       float64 `json:"innerWidth"`
	OuterHeight      float64 `json:"outerHeight"`
	InnerHeight      float64 `json:"innerHeight"`
}

type ExtensionDOMSnapshot struct {
	URL      string                       `json:"url"`
	Title    string                       `json:"title"`
	Elements []ExtensionElementDescriptor `json:"elements"`
	Viewport ExtensionViewportGeometry    `json:"viewport"`
}

type ExtensionResolvedRef struct {
	Ref      string                    `json:"ref"`
	Found    bool                      `json:"found"`
	Rect     ExtensionElementRect      `json:"rect"`
	Viewport ExtensionViewportGeometry `json:"viewport"`
}
