export const dataRoomText = {
	ko: {
		title: '데이터룸',
		allDocuments: '전체 자료',
		categories: '분류',
		name: '이름',
		category: '분류',
		date: '문서 날짜',
		empty: '보관된 자료가 없습니다.',
		refresh: '새로고침',
		retry: '다시 시도',
		close: '닫기',
		share: '링크 공유',
		summary: '요약',
		noSummary: '등록된 요약이 없습니다.',
		download: '원본 다운로드',
		documentNumber: '문서 번호',
		counterpart: '상대방',
		status: '상태',
		tags: '태그',
		loadFailed: '자료를 불러오지 못했습니다.',
		permissions: '데이터룸 권한',
		permissionsDescription: '직원별로 읽을 수 있는 자료를 역할로 지정합니다.',
		save: '저장',
		roles: '역할',
		noRoles: '부여된 역할 없음',
		chooseRoles: '역할 선택',
		directRolesDescription: '직접 부여된 역할을 변경합니다. 소속 그룹의 권한은 추가로 적용됩니다.',
		createRole: '커스텀 역할 추가',
		readerRole: '열람 역할',
		roleCode: '역할 코드',
		roleName: '역할 이름 (영어)',
		koreanRoleName: '역할 이름 (한국어)',
		roleDescription:
			'대분류를 선택하면 현재와 이후 추가되는 모든 하위 분류에 접근할 수 있습니다. 저장하면 기존 사용자와 공유 링크에도 적용됩니다.'
	},
	en: {
		title: 'Dataroom',
		allDocuments: 'All documents',
		categories: 'Categories',
		name: 'Name',
		category: 'Category',
		date: 'Document date',
		empty: 'No documents yet.',
		refresh: 'Refresh',
		retry: 'Retry',
		close: 'Close',
		share: 'Share link',
		summary: 'Summary',
		noSummary: 'No summary available.',
		download: 'Download original',
		documentNumber: 'Document number',
		counterpart: 'Counterpart',
		status: 'Status',
		tags: 'Tags',
		loadFailed: 'Could not load documents.',
		permissions: 'Dataroom permissions',
		permissionsDescription: 'Assign reader roles to each employee.',
		save: 'Save',
		roles: 'Roles',
		noRoles: 'No assigned roles',
		chooseRoles: 'Choose roles',
		directRolesDescription: 'Change direct assignments. Circle permissions also apply.',
		createRole: 'Add custom role',
		readerRole: 'Reader role',
		roleCode: 'Role code',
		roleName: 'Role name (English)',
		koreanRoleName: 'Role name (Korean)',
		roleDescription:
			'A parent grants access to all current and future children. Saving also changes access for existing recipients and share links.'
	}
} as const;
