export const dataRoomText = {
	ko: {
		title: '데이터룸',
		allDocuments: '전체 자료',
		categories: '분류',
		name: '이름',
		category: '분류',
		date: '문서 날짜',
		empty: '보관된 자료가 없습니다.',
		refresh: '새로고침',
		retry: '다시 시도',
		close: '닫기',
		share: '링크 공유',
		summary: '요약',
		noSummary: '등록된 요약이 없습니다.',
		download: '원본 다운로드',
		documentNumber: '문서 번호',
		counterpart: '상대방',
		status: '상태',
		tags: '태그',
		loadFailed: '자료를 불러오지 못했습니다.',
		previous: '이전 자료',
		next: '다음 자료',
		details: '자료 정보',
		noFile: '이 자료에는 보관된 파일이 없습니다.',
		noPreview: '미리볼 수 있는 내용이 없습니다.',
		textPreviewNotice: '원본 대신 원본에서 추출한 텍스트를 표시합니다.',
		search: '자료 검색',
		noResults: '조건에 맞는 자료가 없습니다.',
		documentCount: '건',
		fileType: '형식',
		folders: '폴더',
		viewOnly: '열람 전용',
		downloadAllowed: '다운로드 허용',
		accessUntil: '열람 가능 기한',
		sharedRoom: '공유받은 데이터룸',
		confidential: '기밀 자료입니다. 허용된 검토 목적으로만 사용하세요.',
		circles: '서클',
		circlesDescription: '서클은 공유 폴더와 공유 기억, 데이터룸에서 읽을 분류를 함께 묶습니다. 사람마다 속할 서클을 고릅니다.',
		save: '저장',
		noCircles: '속한 서클 없음',
		chooseCircles: '서클 선택',
		createCircle: '서클 추가',
		circle: '서클',
		circleID: '서클 ID',
		circleName: '이름 (영어)',
		koreanCircleName: '이름 (한국어)',
		circleDescription:
			'이 서클 사람들이 읽을 분류를 고릅니다. 대분류를 고르면 현재와 이후 추가되는 하위 분류까지 포함합니다. 저장하면 이 서클의 사람과 공유 링크에 바로 적용됩니다.'
	},
	en: {
		title: 'Dataroom',
		allDocuments: 'All documents',
		categories: 'Categories',
		name: 'Name',
		category: 'Category',
		date: 'Document date',
		empty: 'No documents yet.',
		refresh: 'Refresh',
		retry: 'Retry',
		close: 'Close',
		share: 'Share link',
		summary: 'Summary',
		noSummary: 'No summary available.',
		download: 'Download original',
		documentNumber: 'Document number',
		counterpart: 'Counterpart',
		status: 'Status',
		tags: 'Tags',
		loadFailed: 'Could not load documents.',
		previous: 'Previous document',
		next: 'Next document',
		details: 'Document details',
		noFile: 'This document keeps no file.',
		noPreview: 'There is nothing to preview.',
		textPreviewNotice: 'Showing the text extracted from the original.',
		search: 'Search documents',
		noResults: 'No documents match.',
		documentCount: 'documents',
		fileType: 'Type',
		folders: 'Folders',
		viewOnly: 'View only',
		downloadAllowed: 'Downloads allowed',
		accessUntil: 'Access until',
		sharedRoom: 'Shared data room',
		confidential: 'Confidential. Use only for the authorized review.',
		circles: 'Circles',
		circlesDescription: 'A circle gives its people a shared folder, a shared memory and the data room categories it reads. Choose the circles each person belongs to.',
		save: 'Save',
		noCircles: 'No circles',
		chooseCircles: 'Choose circles',
		createCircle: 'Add circle',
		circle: 'Circle',
		circleID: 'Circle ID',
		circleName: 'Name (English)',
		koreanCircleName: 'Name (Korean)',
		circleDescription:
			'Choose the categories this circle reads. A parent includes all current and future children. Saving changes access right away for its people and share links.'
	}
} as const;
