#!/usr/bin/env python3
import os
import sys
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parent.parent

os.chdir(REPOSITORY_ROOT)
os.execvp("go", ["go", "run", "./cmd/internkim", "verify", "blueclaw-pointer", *sys.argv[1:]])
