export const flowText = {
	ko: {
		pageTitle: '업무 · 김인턴',
		product: '김인턴',
		title: '업무',
		description: '이번 주 업무, 요청, 중단 상태와 구성원별 흐름을 한 화면에서 봅니다.',
		previousWeek: '이전 주',
		nextWeek: '다음 주',
		currentWeek: '이번 주',
		currentWeekAction: '이번 주로 이동',
		selectWeekDate: '날짜로 주차 이동',
		refresh: '새로고침',
		metrics: {
			total: '전체 업무',
			completed: '완료',
			completedDistance: '구성원 누적 거리',
			distanceUnit: 'km',
			requested: '요청',
			blocked: '멈춘 일',
			requestedDescription: '타인 시트에 추가 요청',
			blockedDescription: '일시정지 + 중단'
		},
		tabs: {
			report: '보고',
			tasks: '업무',
			definitions: '정의',
			members: '구성원'
		},
		report: {
			personalScoreTitle: '개인 상세 점수',
			personalScoreDescription: '최근 5주와 5개월의 완료 거리 기준 가중 점수입니다.',
			weeklyScoreDetail: '주간 점수',
			monthlyScoreDetail: '월간 점수',
			scorePeriod: '기간',
			scoreCompletedDistance: '완료 거리',
			scoreCumulativeAverage: '누적 평균',
			scoreUnitScore: '단위 점수',
			scoreWeight: '가중치',
			scoreWeightedScore: '가중 점수',
			scoreTotal: '총점',
			scoreEmpty: '현재 사용자 점수 데이터가 없습니다.',
			weekPeriodLabel: '{count}주 전',
			currentWeekPeriodLabel: '이번 주',
			monthPeriodLabel: '{count}개월 전',
			currentMonthPeriodLabel: '이번 달',
			weeklyStatus: '이번 주간 업무 일별 종류 거리 분포',
			weeklyStatusDescription: '월요일부터 일요일까지 업무 종류별 거리 비중을 봅니다.',
			memberDistance: '구성원 점수',
			memberDistanceDescription: '최근 5주와 5개월의 완료 거리 가중 점수입니다.',
			weeklyDistanceTrend: '주간 통계',
			weeklyDistanceTrendDescription: '지난주와 이번주의 일별 팀 거리 합을 비교합니다.',
			monthlyDistanceTrend: '월간 통계',
			monthlyDistanceTrendDescription: '지난달과 이번달의 일별 팀 거리 합을 비교합니다.',
			businessDistance: '이번 주간 사업 거리 분포',
			businessDistanceDescription: '이번 주 거리 합이 어느 사업에 몰려 있는지 봅니다.',
			empty: '이번 주 데이터 없음',
			weekdays: ['월', '화', '수', '목', '금', '토', '일'],
			fallbackType: '기타',
			fallbackBusiness: '기타',
			memberScoreLabel: '점수',
			weeklyScoreLabel: '주간',
			monthlyScoreLabel: '월간',
			scoreUnit: '점',
			teamAverageLabel: '팀 평균',
			memberScrollHint: '{count}명 전체 · 목록 안에서 스크롤',
			currentWeekTrend: '이번 주',
			previousWeekTrend: '지난 주',
			currentMonthTrend: '이번 달',
			previousMonthTrend: '지난 달',
			monthlyDayLabelTemplate: '{day}일'
		},
		definitions: {
			size: '크기',
			sizeDescription: '거리(km)는 업무 크기 기준입니다. 완료 업무는 종료일 기준으로 거리와 점수에 반영됩니다.',
			sizeName: '크기',
			distance: '거리(km)',
			maxHours: '최대 예상 시간(H)',
			developmentExample: '예시(개발)',
			otherExample: '예시(기타)',
			note: '비고',
			business: '사업',
			type: '종류',
			businessDescription: '사업은 업무가 속한 단위입니다. 값이 하나 이하이면 업무 추가 화면에서 숨깁니다.',
			typeDescription: '업무 종류는 모든 업무에 필요합니다.',
			newBusiness: '사업 추가',
			newType: '종류 추가',
			add: '추가',
			autoSave: '추가와 삭제는 즉시 저장됩니다.',
			save: '정의 저장',
			saving: '저장 중...',
			saved: '저장됨',
			saveError: '정의를 저장하지 못했습니다.',
			adminOnly: '정의 편집은 관리자만 가능합니다.',
			removeAction: '삭제',
			cancel: '취소',
			removeBusinessTitle: '사업 삭제',
			removeBusinessDescription: '"{value}" 사업을 삭제하시겠어요? 이 작업은 즉시 적용됩니다.',
			removeTypeTitle: '종류 삭제',
			removeTypeDescription: '"{value}" 종류를 삭제하시겠어요? 이 작업은 즉시 적용됩니다.'
		},
		filters: {
			searchPlaceholder: '내용, 목표, 참여자 검색',
			filterButton: '필터',
			filterCount: '필터 {count}',
			status: '상태',
			owner: '담당자',
			participants: '참여자',
			allParticipants: '전체 참여자',
			noParticipantFilter: '전체 참여자',
			business: '사업',
			type: '종류',
			all: '전체',
			reset: '초기화',
			addTask: '업무 추가'
		},
		task: {
			quickAddPlaceholder: '예: 10분 회의',
			quickAdd: 'AI로 업무 추가',
			quickAddClose: 'AI 업무 추가 닫기',
			quickAddBackdropClose: 'AI 업무 추가 팝업 배경 닫기',
			quickAddHint: '짧게 적으면 AI가 종류, 크기, 상태를 추정해 이번 주 업무로 추가합니다.',
			quickAddError: 'AI 업무 추가에 실패했습니다.',
			quickAddDuplicate: '이미 있는 업무로 보여 추가하지 않았습니다.',
			quickAddDuplicateAction: '그래도 추가',
			editTitle: '업무 수정',
			createTitle: '업무 요청',
			content: '내용',
			contentPlaceholder: '업무 내용',
			goal: '목표',
			goalPlaceholder: '완료 기준',
			owner: '담당자',
			status: '상태',
			business: '사업',
			businessFallback: '기타',
			type: '종류',
			size: '크기',
			startDate: '시작일',
			endDate: '종료일',
			participants: '참여자',
			participantsPlaceholder: '이름을 입력해 추가',
			removeParticipantAction: '{name} 제거',
			requestReason: '요청 사유',
			reason: '사유',
			dateRule: '진행은 시작일, 완료는 종료일을 기준으로 주간 코드에 반영됩니다. 날짜가 없는 예정/요청은 현재 주간에 표시됩니다.',
			readOnly: '관리자 또는 참여자만 수정할 수 있습니다.',
			deleteAction: '업무 삭제',
			deleteTitle: '업무 삭제',
			deleteDescription: '"{task}" 업무를 삭제하시겠어요?',
			deleteConfirm: '삭제',
			cancel: '취소',
			deleteError: '업무를 삭제하지 못했습니다.',
			save: '업무 저장',
			saving: '저장 중...',
			deleting: '삭제 중...',
			saveError: '업무를 저장하지 못했습니다.',
			empty: '조건에 맞는 업무가 없습니다.',
			viewTabs: {
				board: '보드',
				list: '목록'
			},
			board: {
				addTask: '{status} 업무 추가'
			}
		},
		table: {
			owner: '담당자',
			business: '사업',
			type: '종류',
			content: '내용',
			participants: '참여자',
			size: '크기',
			status: '상태',
			startDate: '시작일',
			endDate: '종료일',
			pagination: {
				label: '업무 목록 페이지',
				previous: '이전',
				next: '다음',
				summary: '{total}개 중 {from}–{to}'
			}
		},
		members: {
			title: '구성원',
			name: '이름',
			email: '이메일',
			hireDate: '입사일',
			role: '권한',
			mattermost: 'Mattermost',
			active: '진행',
			completed: '완료',
			distance: '거리',
			empty: '구성원이 아직 없습니다.'
		},
		status: {
			예정: '예정',
			요청: '요청',
			진행: '진행',
			완료: '완료',
			기각: '기각',
			일시정지: '일시정지',
			중단: '중단'
		},
		statusDescriptions: {
			예정: '',
			요청: '',
			진행: '',
			완료: '',
			기각: '반려됨',
			일시정지: '재개 가능',
			중단: '종료 처리'
		},
		user: {
			logout: '로그아웃',
			signedOut: '게스트'
		},
		loadError: '업무 데이터를 불러오지 못했습니다.'
	},
	en: {
		pageTitle: 'Flow · Intern Kim',
		product: 'Intern Kim',
		title: 'Flow',
		description: 'Review this week’s tasks, requests, stopped work, and member progress in one place.',
		previousWeek: 'Previous',
		nextWeek: 'Next',
		currentWeek: 'This week',
		currentWeekAction: 'Go to this week',
		selectWeekDate: 'Go to date',
		refresh: 'Refresh',
		metrics: {
			total: 'Total tasks',
			completed: 'Completed',
			completedDistance: 'Member distance total',
			distanceUnit: 'km',
			requested: 'Requested',
			blocked: 'Blocked',
			requestedDescription: 'Tasks requested on another member sheet',
			blockedDescription: 'Paused + stopped'
		},
		tabs: {
			report: 'Report',
			tasks: 'Tasks',
			definitions: 'Definitions',
			members: 'Members'
		},
		report: {
			personalScoreTitle: 'Personal score detail',
			personalScoreDescription: 'Weighted score from completed distance over the last 5 weeks and 5 months.',
			weeklyScoreDetail: 'Weekly score',
			monthlyScoreDetail: 'Monthly score',
			scorePeriod: 'Period',
			scoreCompletedDistance: 'Completed distance',
			scoreCumulativeAverage: 'Cumulative average',
			scoreUnitScore: 'Unit score',
			scoreWeight: 'Weight',
			scoreWeightedScore: 'Weighted score',
			scoreTotal: 'Total',
			scoreEmpty: 'No score data for the current user.',
			weekPeriodLabel: '{count} weeks ago',
			currentWeekPeriodLabel: 'This week',
			monthPeriodLabel: '{count} months ago',
			currentMonthPeriodLabel: 'This month',
			weeklyStatus: 'Weekly daily type distance',
			weeklyStatusDescription: 'See the daily share of distance by work type from Monday to Sunday.',
			memberDistance: 'Member score',
			memberDistanceDescription: 'Weighted score from completed distance over the last 5 weeks and 5 months.',
			weeklyDistanceTrend: 'Weekly statistics',
			weeklyDistanceTrendDescription: 'Compare daily team distance totals from this week and last week.',
			monthlyDistanceTrend: 'Monthly statistics',
			monthlyDistanceTrendDescription: 'Compare daily team distance totals from this month and last month.',
			businessDistance: 'Weekly business distance',
			businessDistanceDescription: 'See which businesses generated this week’s distance.',
			empty: 'No data for this week',
			weekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
			fallbackType: 'Other',
			fallbackBusiness: 'Other',
			memberScoreLabel: 'Score',
			weeklyScoreLabel: 'Weekly',
			monthlyScoreLabel: 'Monthly',
			scoreUnit: ' pts',
			teamAverageLabel: 'Team average',
			memberScrollHint: '{count} members total · scroll inside list',
			currentWeekTrend: 'This week',
			previousWeekTrend: 'Last week',
			currentMonthTrend: 'This month',
			previousMonthTrend: 'Last month',
			monthlyDayLabelTemplate: 'Day {day}'
		},
		definitions: {
			size: 'Size',
			sizeDescription: 'Distance (km) is the task size baseline. Completed work is counted toward distance and score by its end date.',
			sizeName: 'Size',
			distance: 'Distance (km)',
			maxHours: 'Max hours',
			developmentExample: 'Dev example',
			otherExample: 'Other example',
			note: 'Note',
			business: 'Business',
			type: 'Type',
			businessDescription: 'Businesses are the units tasks belong to. If there is one value or fewer, the business picker is hidden when adding tasks.',
			typeDescription: 'Every task needs a type.',
			newBusiness: 'Add business',
			newType: 'Add type',
			add: 'Add',
			autoSave: 'Adds and removals save immediately.',
			save: 'Save definitions',
			saving: 'Saving...',
			saved: 'Saved',
			saveError: 'Could not save definitions.',
			adminOnly: 'Only admins can edit definitions.',
			removeAction: 'Remove',
			cancel: 'Cancel',
			removeBusinessTitle: 'Remove business',
			removeBusinessDescription: 'Remove the "{value}" business? This change applies immediately.',
			removeTypeTitle: 'Remove type',
			removeTypeDescription: 'Remove the "{value}" type? This change applies immediately.'
		},
		filters: {
			searchPlaceholder: 'Search content, goal, or participant',
			filterButton: 'Filters',
			filterCount: 'Filters {count}',
			status: 'Status',
			owner: 'Owner',
			participants: 'Participants',
			allParticipants: 'All participants',
			noParticipantFilter: 'All participants',
			business: 'Business',
			type: 'Type',
			all: 'All',
			reset: 'Reset',
			addTask: 'Add task'
		},
		task: {
			quickAddPlaceholder: 'Example: 10-minute meeting',
			quickAdd: 'Add with AI',
			quickAddClose: 'Close add with AI',
			quickAddBackdropClose: 'Close add with AI backdrop',
			quickAddHint: 'Write a short note and AI will infer the type, size, and status for this week’s task.',
			quickAddError: 'Could not add the task with AI.',
			quickAddDuplicate: 'This looks like an existing task, so it was not added.',
			quickAddDuplicateAction: 'Add anyway',
			editTitle: 'Edit task',
			createTitle: 'Request task',
			content: 'Content',
			contentPlaceholder: 'Task content',
			goal: 'Goal',
			goalPlaceholder: 'Completion criteria',
			owner: 'Owner',
			status: 'Status',
			business: 'Business',
			businessFallback: 'Other',
			type: 'Type',
			size: 'Size',
			startDate: 'Start date',
			endDate: 'End date',
			participants: 'Participants',
			participantsPlaceholder: 'Type a name to add',
			removeParticipantAction: 'Remove {name}',
			requestReason: 'Request reason',
			reason: 'Reason',
			dateRule: 'In progress uses the start date, and completed uses the end date for the week code. Planned/requested tasks without dates appear in the current week.',
			readOnly: 'Only admins or participants can edit this task.',
			deleteAction: 'Delete task',
			deleteTitle: 'Delete task',
			deleteDescription: 'Delete "{task}"?',
			deleteConfirm: 'Delete',
			cancel: 'Cancel',
			deleteError: 'Could not delete the task.',
			save: 'Save task',
			saving: 'Saving...',
			deleting: 'Deleting...',
			saveError: 'Could not save the task.',
			empty: 'No tasks match these filters.',
			viewTabs: {
				board: 'Board',
				list: 'List'
			},
			board: {
				addTask: 'Add {status} task'
			}
		},
		table: {
			owner: 'Owner',
			business: 'Business',
			type: 'Type',
			content: 'Content',
			participants: 'Participants',
			size: 'Size',
			status: 'Status',
			startDate: 'Start date',
			endDate: 'End date',
			pagination: {
				label: 'Task list pages',
				previous: 'Previous',
				next: 'Next',
				summary: '{from}–{to} of {total}'
			}
		},
		members: {
			title: 'Members',
			name: 'Name',
			email: 'Email',
			hireDate: 'Hire date',
			role: 'Role',
			mattermost: 'Mattermost',
			active: 'Active',
			completed: 'Completed',
			distance: 'Distance',
			empty: 'No members yet.'
		},
		status: {
			예정: 'Planned',
			요청: 'Requested',
			진행: 'In progress',
			완료: 'Completed',
			기각: 'Rejected',
			일시정지: 'Paused',
			중단: 'Stopped'
		},
		statusDescriptions: {
			예정: '',
			요청: '',
			진행: '',
			완료: '',
			기각: 'Rejected',
			일시정지: 'Can resume',
			중단: 'Closed out'
		},
		user: {
			logout: 'Sign out',
			signedOut: 'Guest'
		},
		loadError: 'Could not load Flow data.'
	}
} as const;
