export const enFlowText = {
	"pageTitle": "Flow · Intern Kim",
	"product": "Intern Kim",
	"title": "Flow",
	"description": "Review this week’s tasks, requests, stopped work, and member progress in one place.",
	"previousWeek": "Previous",
	"nextWeek": "Next",
	"currentWeek": "This week",
	"currentWeekAction": "Go to this week",
	"selectWeekDate": "Go to date",
	"refresh": "Refresh",
	"metrics": {
		"total": "Total tasks",
		"completed": "Completed",
		"completedDistance": "Member distance total",
		"distanceUnit": "km",
		"requested": "Requested",
		"blocked": "Blocked",
		"requestedDescription": "Tasks requested on another member sheet",
		"blockedDescription": "Paused + stopped"
	},
	"tabs": {
		"report": "Report",
		"tasks": "Tasks",
		"definitions": "Definitions",
		"members": "Members"
	},
	"report": {
		"weeklyStatus": "Weekly daily type distance",
		"weeklyStatusDescription": "See the daily share of distance by work type from Monday to Sunday.",
		"memberDistance": "Member score",
		"memberDistanceDescription": "Weighted score from completed distance over the last 5 weeks and 5 months.",
		"weeklyDistanceTrend": "Weekly statistics",
		"weeklyDistanceTrendDescription": "Compare daily team distance totals from this week and last week.",
		"monthlyDistanceTrend": "Monthly statistics",
		"monthlyDistanceTrendDescription": "Compare daily team distance totals from this month and last month.",
		"businessDistance": "Weekly business distance",
		"businessDistanceDescription": "See which business items generated this week’s distance.",
		"empty": "No data for this week",
		"weekdays": [
			"Mon",
			"Tue",
			"Wed",
			"Thu",
			"Fri",
			"Sat",
			"Sun"
		],
		"fallbackType": "Other",
		"fallbackBusiness": "Unassigned",
		"memberScoreLabel": "Score",
		"scoreUnit": " pts",
		"teamAverageLabel": "Team average",
		"memberScrollHint": "{count} members total · scroll inside list",
		"currentWeekTrend": "This week",
		"previousWeekTrend": "Last week",
		"currentMonthTrend": "This month",
		"previousMonthTrend": "Last month",
		"monthlyDayLabelTemplate": "Day {day}"
	},
	"definitions": {
		"size": "Size",
		"sizeDescription": "Distance (km) is the task size baseline. Completed work is counted toward distance and score by its end date.",
		"sizeName": "Size",
		"distance": "Distance (km)",
		"maxHours": "Max hours",
		"developmentExample": "Dev example",
		"otherExample": "Other example",
		"note": "Note",
		"category": "Project",
		"type": "Type",
		"categoryDescription": "Projects are the business units tasks belong to. If there is one or fewer value, the project picker is hidden when adding tasks.",
		"typeDescription": "Every task needs a type.",
		"newCategory": "Add project",
		"newType": "Add type",
		"add": "Add",
		"save": "Save definitions",
		"saving": "Saving...",
		"saveError": "Could not save definitions.",
		"adminOnly": "Only admins can edit definitions.",
		"removeAction": "Remove",
		"cancel": "Cancel",
		"removeCategoryTitle": "Remove project",
		"removeCategoryDescription": "Remove the \"{value}\" project? This change applies immediately.",
		"removeTypeTitle": "Remove type",
		"removeTypeDescription": "Remove the \"{value}\" type? This change applies immediately."
	},
	"filters": {
		"searchPlaceholder": "Search content, goal, or owner",
		"status": "Status",
		"owner": "Owner",
		"business": "Project",
		"type": "Type",
		"all": "All",
		"reset": "Reset",
		"addTask": "Add task"
	},
	"task": {
		"quickAddPlaceholder": "Example: 10-minute meeting",
		"quickAdd": "Add with AI",
		"quickAddHint": "Write a short note and AI will infer the type, size, and status for this week’s task.",
		"quickAddError": "Could not add the task with AI.",
		"quickAddDuplicate": "This looks like an existing task, so it was not added.",
		"quickAddDuplicateAction": "Add anyway",
		"editTitle": "Edit task",
		"createTitle": "Request task",
		"content": "Content",
		"contentPlaceholder": "Task content",
		"goal": "Goal",
		"goalPlaceholder": "Completion criteria",
		"owner": "Owner",
		"status": "Status",
		"business": "Project",
		"category": "Project",
		"type": "Type",
		"size": "Size",
		"flag": "Flag",
		"startDate": "Start date",
		"endDate": "End date",
		"participants": "Participants",
		"participantsPlaceholder": "Type a name to add",
		"requestReason": "Request reason",
		"reason": "Reason",
		"dateRule": "In progress uses the start date, and completed uses the end date for the week code. Planned/requested tasks without dates appear in the current week.",
		"save": "Save task",
		"saving": "Saving...",
		"saveError": "Could not save the task.",
		"empty": "No tasks match these filters."
	},
	"table": {
		"owner": "Owner",
		"business": "Project",
		"type": "Type",
		"content": "Content",
		"participants": "Participants",
		"size": "Size",
		"status": "Status",
		"startDate": "Start date",
		"endDate": "End date",
		"flag": "Flag",
		"pagination": {
			"previous": "Previous",
			"next": "Next",
			"summary": "{from}–{to} of {total}"
		}
	},
	"members": {
		"title": "Members",
		"name": "Name",
		"email": "Email",
		"hireDate": "Hire date",
		"role": "Role",
		"mattermost": "Mattermost",
		"active": "Active",
		"completed": "Completed",
		"distance": "Distance",
		"empty": "No members yet."
	},
	"status": {
		"예정": "Planned",
		"요청": "Requested",
		"진행": "In progress",
		"완료": "Completed",
		"기각": "Rejected",
		"일시정지": "Paused",
		"중단": "Stopped"
	},
	"statusDescriptions": {
		"예정": "",
		"요청": "",
		"진행": "",
		"완료": "",
		"기각": "Rejected",
		"일시정지": "Can resume",
		"중단": "Closed out"
	},
	"user": {
		"logout": "Sign out",
		"signedOut": "Guest"
	},
	"loadError": "Could not load Flow data."
} as const;
