export const flowText = {
	ko: {
		pageTitle: 'Flow · Intern Kim',
		product: 'Intern Kim',
		title: 'Flow',
		description: '이번 주 업무, 요청, 중단 상태와 구성원별 흐름을 한 화면에서 봅니다.',
		previousWeek: '이전 주',
		nextWeek: '다음 주',
		currentWeek: '이번 주',
		refresh: '새로고침',
		metrics: {
			total: '전체 업무',
			completed: '완료',
			requested: '요청',
			blocked: '멈춘 일',
			requestedDescription: '타인 시트에 추가 요청',
			blockedDescription: '일시정지 + 중단'
		},
		tabs: {
			report: '보고',
			tasks: '업무',
			definitions: '정의',
			members: '구성원'
		},
		report: {
			weeklyStatus: '주간 상태',
			weeklyStatusDescription: '상태별 업무 분포와 막힌 일을 빠르게 확인합니다.',
			memberScores: '구성원 거리',
			memberScoresDescription: '완료와 진행 업무 기준의 주간 업무 거리입니다.',
			businessDistance: '대분류별 업무',
			typeBreakdown: '종류별 업무'
		},
		definitions: {
			size: '크기',
			sizeDescription: '거리(Km)는 업무의 크기를 이해하기 위한 공통 언어입니다. 평가는 아니라 일정 안정화, 집중 유지, 과부하와 늘어짐 방지를 위한 기준입니다.',
			sizeName: '크기',
			distance: '거리(Km)',
			maxHours: '최대 예상 시간(H)',
			developmentExample: '예시(개발)',
			otherExample: '예시(기타)',
			note: '비고',
			category: '대분류',
			type: '종류',
			categoryDescription: '대분류는 기본 공란입니다. 값이 하나 이하이면 업무 추가 화면에서 숨깁니다.',
			typeDescription: '업무 종류는 모든 업무에 필요합니다.',
			newCategory: '대분류 추가',
			newType: '종류 추가',
			add: '추가',
			save: '정의 저장',
			saving: '저장 중...',
			saveError: '정의를 저장하지 못했습니다.',
			adminOnly: '정의 편집은 관리자만 가능합니다.',
			removeAction: '삭제',
			cancel: '취소',
			removeCategoryTitle: '대분류 삭제',
			removeCategoryDescription: '"{value}" 대분류를 삭제하시겠어요? 이 작업은 즉시 적용됩니다.',
			removeTypeTitle: '종류 삭제',
			removeTypeDescription: '"{value}" 종류를 삭제하시겠어요? 이 작업은 즉시 적용됩니다.'
		},
		filters: {
			searchPlaceholder: '내용, 목표, 담당자 검색',
			status: '상태',
			owner: '담당자',
			business: '대분류',
			type: '종류',
			all: '전체',
			reset: '초기화',
			addTask: '업무 추가'
		},
		task: {
			quickAddPlaceholder: '예: 10분 회의',
			quickAdd: 'AI로 업무 추가',
			quickAddHint: '짧게 적으면 AI가 종류, 크기, 상태를 추정해 이번 주 업무로 추가합니다.',
			quickAddError: 'AI 업무 추가에 실패했습니다.',
			editTitle: '업무 수정',
			createTitle: '업무 요청',
			content: '내용',
			contentPlaceholder: '업무 내용',
			goal: '목표',
			goalPlaceholder: '완료 기준',
			owner: '담당자',
			status: '상태',
			business: '대분류',
			category: '대분류',
			type: '종류',
			size: '크기',
			flag: '플래그',
			startDate: '시작일',
			endDate: '종료일',
			participants: '참여자',
			participantsPlaceholder: '이름을 입력해 추가',
			requestReason: '요청 사유',
			reason: '사유',
			dateRule: '진행은 시작일, 완료는 종료일을 기준으로 주간 코드에 반영됩니다. 날짜가 없는 예정/요청은 현재 주간에 표시됩니다.',
			save: '업무 저장',
			saving: '저장 중...',
			saveError: '업무를 저장하지 못했습니다.',
			empty: '조건에 맞는 업무가 없습니다.'
		},
		table: {
			owner: '담당자',
			business: '대분류',
			type: '종류',
			content: '내용',
			participants: '참여자',
			size: '크기',
			status: '상태',
			startDate: '시작일',
			endDate: '종료일',
			flag: '플래그',
			pagination: {
				previous: '이전',
				next: '다음',
				summary: '{total}개 중 {from}–{to}'
			}
		},
		members: {
			title: '구성원',
			name: '이름',
			email: '이메일',
			hireDate: '입사일',
			role: '권한',
			mattermost: 'Mattermost',
			active: '진행',
			completed: '완료',
			score: '거리',
			empty: '구성원이 아직 없습니다.'
		},
		status: {
			예정: '예정',
			요청: '요청',
			진행: '진행',
			완료: '완료',
			기각: '기각',
			일시정지: '일시정지',
			중단: '중단'
		},
		user: {
			logout: '로그아웃',
			signedOut: '게스트'
		},
		loadError: 'Flow 데이터를 불러오지 못했습니다.'
	},
	en: {
		pageTitle: 'Flow · Intern Kim',
		product: 'Intern Kim',
		title: 'Flow',
		description: 'Review this week’s tasks, requests, stopped work, and member progress in one place.',
		previousWeek: 'Previous',
		nextWeek: 'Next',
		currentWeek: 'This week',
		refresh: 'Refresh',
		metrics: {
			total: 'Total tasks',
			completed: 'Completed',
			requested: 'Requested',
			blocked: 'Blocked',
			requestedDescription: 'Tasks requested on another member sheet',
			blockedDescription: 'Paused + stopped'
		},
		tabs: {
			report: 'Report',
			tasks: 'Tasks',
			definitions: 'Definitions',
			members: 'Members'
		},
		report: {
			weeklyStatus: 'Weekly status',
			weeklyStatusDescription: 'Quickly see status distribution and blocked work.',
			memberScores: 'Member distance',
			memberScoresDescription: 'Weekly work distance based on completed and active work.',
			businessDistance: 'By category',
			typeBreakdown: 'By type'
		},
		definitions: {
			size: 'Size',
			sizeDescription: 'Distance (km) is a shared language for task size. It is not an evaluation score; it helps stabilize schedules, keep focus, and prevent overload or task drift.',
			sizeName: 'Size',
			distance: 'Distance (km)',
			maxHours: 'Max hours',
			developmentExample: 'Dev example',
			otherExample: 'Other example',
			note: 'Note',
			category: 'Category',
			type: 'Type',
			categoryDescription: 'Categories are blank by default. If there is one or fewer value, the category picker is hidden when adding tasks.',
			typeDescription: 'Every task needs a type.',
			newCategory: 'Add category',
			newType: 'Add type',
			add: 'Add',
			save: 'Save definitions',
			saving: 'Saving...',
			saveError: 'Could not save definitions.',
			adminOnly: 'Only admins can edit definitions.',
			removeAction: 'Remove',
			cancel: 'Cancel',
			removeCategoryTitle: 'Remove category',
			removeCategoryDescription: 'Remove the "{value}" category? This change applies immediately.',
			removeTypeTitle: 'Remove type',
			removeTypeDescription: 'Remove the "{value}" type? This change applies immediately.'
		},
		filters: {
			searchPlaceholder: 'Search content, goal, or owner',
			status: 'Status',
			owner: 'Owner',
			business: 'Category',
			type: 'Type',
			all: 'All',
			reset: 'Reset',
			addTask: 'Add task'
		},
		task: {
			quickAddPlaceholder: 'Example: 10-minute meeting',
			quickAdd: 'Add with AI',
			quickAddHint: 'Write a short note and AI will infer the type, size, and status for this week’s task.',
			quickAddError: 'Could not add the task with AI.',
			editTitle: 'Edit task',
			createTitle: 'Request task',
			content: 'Content',
			contentPlaceholder: 'Task content',
			goal: 'Goal',
			goalPlaceholder: 'Completion criteria',
			owner: 'Owner',
			status: 'Status',
			business: 'Category',
			category: 'Category',
			type: 'Type',
			size: 'Size',
			flag: 'Flag',
			startDate: 'Start date',
			endDate: 'End date',
			participants: 'Participants',
			participantsPlaceholder: 'Type a name to add',
			requestReason: 'Request reason',
			reason: 'Reason',
			dateRule: 'In progress uses the start date, and completed uses the end date for the week code. Planned/requested tasks without dates appear in the current week.',
			save: 'Save task',
			saving: 'Saving...',
			saveError: 'Could not save the task.',
			empty: 'No tasks match these filters.'
		},
		table: {
			owner: 'Owner',
			business: 'Category',
			type: 'Type',
			content: 'Content',
			participants: 'Participants',
			size: 'Size',
			status: 'Status',
			startDate: 'Start date',
			endDate: 'End date',
			flag: 'Flag',
			pagination: {
				previous: 'Previous',
				next: 'Next',
				summary: '{from}–{to} of {total}'
			}
		},
		members: {
			title: 'Members',
			name: 'Name',
			email: 'Email',
			hireDate: 'Hire date',
			role: 'Role',
			mattermost: 'Mattermost',
			active: 'Active',
			completed: 'Completed',
			score: 'Distance',
			empty: 'No members yet.'
		},
		status: {
			예정: 'Planned',
			요청: 'Requested',
			진행: 'In progress',
			완료: 'Completed',
			기각: 'Rejected',
			일시정지: 'Paused',
			중단: 'Stopped'
		},
		user: {
			logout: 'Sign out',
			signedOut: 'Guest'
		},
		loadError: 'Could not load Flow data.'
	}
} as const;
